//
//  Strings.swift
//  Plotwist
//

import Foundation

enum L10n {
  static var current: Strings { strings[Language.current] ?? strings[.enUS]! }

  private static let strings: [Language: Strings] = [
    .enUS: Strings(
      // Login
      loginLabel: "Email or username",
      loginPlaceholder: "Email or username",
      passwordLabel: "Password",
      passwordPlaceholder: "*********",
      accessButton: "Access",
      doNotHaveAccount: "Don't have an account?",
      createNow: "Create now",
      loginRequired: "Please enter your email or username.",
      passwordRequired: "Please enter your password.",
      passwordLength: "Your password must be at least 8 characters long.",
      invalidCredentials: "Invalid login credentials.",
      continueWithGoogle: "Continue with Google",
      continueWithApple: "Continue with Apple",
      or: "or",
      // Sign Up
      startNow: "Start now",
      startYourJourney: "Start your journey in just a few steps.",
      emailLabel: "Email",
      emailPlaceholder: "email@domain.com",
      continueButton: "Continue",
      alreadyHaveAccount: "Already have an account?",
      accessNow: "Access now",
      selectUsername: "Select your username",
      selectUsernameDescription:
        "Choose your username and finish your sign-up to start using the platform.",
      usernamePlaceholder: "john-doe",
      finishSignUp: "Finish sign-up",
      emailRequired: "Please enter your email.",
      emailInvalid: "Please enter a valid email.",
      usernameRequired: "Please enter a username.",
      emailAlreadyTaken: "This email is already in use.",
      usernameAlreadyTaken: "This username is already taken.",
      signUpSuccess: "Registration successful. Welcome! 🎉",
      // Search
      searchPlaceholder: "Search movies, series, people...",
      movies: "Movies",
      tvSeries: "TV Series",
      people: "People",
      noResults: "No results found.",
      cancel: "Cancel",
      popularMovies: "Popular Movies",
      popularTVSeries: "Popular TV Series",
      popularAnimes: "Popular Animes",
      popularDoramas: "Popular Doramas",
      animes: "Animes",
      doramas: "Doramas",
      seeAllMovies: "See all movies",
      seeAllTVSeries: "See all series",
      seeAllAnimes: "See all animes",
      seeAllDoramas: "See all doramas",
      settings: "Settings",
      theme: "Theme",
      themeSystem: "System",
      themeLight: "Light",
      themeDark: "Dark",
      language: "Language",
      done: "Done",
      signOut: "Sign Out",
      // Reviews
      whatDidYouThink: "What did you think?",
      review: "Review",
      reviewed: "Reviewed",
      shareYourOpinion: "Share your opinion here...",
      containSpoilers: "Contains spoilers",
      submitReview: "Submit review",
      editReview: "Edit review",
      reviewRequired: "Please write your review.",
      reviewSuccess: "Review submitted successfully!",
      reviewUpdateSuccess: "Review updated successfully!",
      reviewDeleteSuccess: "Review deleted successfully!",
      tabReviews: "Reviews",
      reviewSingular: "Review",
      tabWhereToWatch: "Where to Watch",
      tabCredits: "Credits",
      tabRecommendations: "Recommendations",
      tabSimilar: "Similar",
      tabImages: "Images",
      tabVideos: "Videos",
      beFirstToReview: "Be the first to leave your opinion",
      seeAll: "See all reviews",
      showMore: "Show more",
      // Movie Categories
      nowPlaying: "Now Playing",
      popular: "Popular",
      topRated: "Top Rated",
      upcoming: "Upcoming",
      discover: "Discover",
      // TV Series Categories
      airingToday: "Airing Today",
      onTheAir: "On The Air",
      // Images
      images: "Images",
      backdrops: "Backdrops",
      posters: "Posters",
      noImagesFound: "No images found.",
      deleteReview: "Delete Review",
      deleteReviewConfirmation: "Are you sure you want to delete this review?",
      delete: "Delete",
      // Status
      updateStatus: "Update Status",
      watched: "Watched",
      watching: "Watching",
      watchlist: "Watchlist",
      dropped: "Dropped"
    ),
    .ptBR: Strings(
      loginLabel: "E-mail ou nome de usuário",
      loginPlaceholder: "E-mail ou nome de usuário",
      passwordLabel: "Senha",
      passwordPlaceholder: "*********",
      accessButton: "Acessar",
      doNotHaveAccount: "Não tem uma conta?",
      createNow: "Crie agora",
      loginRequired: "Por favor, insira seu e-mail ou nome de usuário.",
      passwordRequired: "Por favor, insira sua senha.",
      passwordLength: "Sua senha deve ter pelo menos 8 caracteres.",
      invalidCredentials: "Credenciais de login inválidas.",
      continueWithGoogle: "Continuar com Google",
      continueWithApple: "Continuar com Apple",
      or: "ou",
      startNow: "Comece agora",
      startYourJourney: "Comece sua jornada em poucos passos.",
      emailLabel: "E-mail",
      emailPlaceholder: "email@dominio.com",
      continueButton: "Continuar",
      alreadyHaveAccount: "Já tem uma conta?",
      accessNow: "Acesse agora",
      selectUsername: "Escolha seu nome de usuário",
      selectUsernameDescription:
        "Escolha seu nome de usuário e finalize seu cadastro para começar a usar a plataforma.",
      usernamePlaceholder: "joao-silva",
      finishSignUp: "Finalizar cadastro",
      emailRequired: "Por favor, insira seu e-mail.",
      emailInvalid: "Por favor, insira um e-mail válido.",
      usernameRequired: "Por favor, insira um nome de usuário.",
      emailAlreadyTaken: "Este e-mail já está em uso.",
      usernameAlreadyTaken: "Este nome de usuário já está em uso.",
      signUpSuccess: "Cadastro realizado com sucesso. Bem-vindo! 🎉",
      searchPlaceholder: "Buscar filmes, séries, pessoas...",
      movies: "Filmes",
      tvSeries: "Séries de TV",
      people: "Pessoas",
      noResults: "Nenhum resultado encontrado.",
      cancel: "Cancelar",
      popularMovies: "Filmes Populares",
      popularTVSeries: "Séries Populares",
      popularAnimes: "Animes Populares",
      popularDoramas: "Doramas Populares",
      animes: "Animes",
      doramas: "Doramas",
      seeAllMovies: "Ver todos os filmes",
      seeAllTVSeries: "Ver todas as séries",
      seeAllAnimes: "Ver todos os animes",
      seeAllDoramas: "Ver todos os doramas",
      settings: "Configurações",
      theme: "Tema",
      themeSystem: "Sistema",
      themeLight: "Claro",
      themeDark: "Escuro",
      language: "Idioma",
      done: "Concluído",
      signOut: "Sair",
      whatDidYouThink: "O que você achou?",
      review: "Avaliar",
      reviewed: "Avaliado",
      shareYourOpinion: "Compartilhe sua opinião aqui...",
      containSpoilers: "Contém spoilers",
      submitReview: "Enviar avaliação",
      editReview: "Editar avaliação",
      reviewRequired: "Por favor, escreva sua avaliação.",
      reviewSuccess: "Avaliação enviada com sucesso!",
      reviewUpdateSuccess: "Avaliação atualizada com sucesso!",
      reviewDeleteSuccess: "Avaliação excluída com sucesso!",
      tabReviews: "Avaliações",
      reviewSingular: "Avaliação",
      tabWhereToWatch: "Onde Assistir",
      tabCredits: "Elenco",
      tabRecommendations: "Recomendações",
      tabSimilar: "Similares",
      tabImages: "Imagens",
      tabVideos: "Vídeos",
      beFirstToReview: "Seja o primeiro a deixar sua opinião",
      seeAll: "Ver todas as avaliações",
      showMore: "Ver mais",
      nowPlaying: "Em Cartaz",
      popular: "Popular",
      topRated: "Mais Bem Avaliados",
      upcoming: "Em Breve",
      discover: "Descobrir",
      airingToday: "No Ar Hoje",
      onTheAir: "Em Exibição",
      images: "Imagens",
      backdrops: "Backdrops",
      posters: "Pôsteres",
      noImagesFound: "Nenhuma imagem encontrada.",
      deleteReview: "Excluir Avaliação",
      deleteReviewConfirmation: "Tem certeza que deseja excluir esta avaliação?",
      delete: "Excluir",
      updateStatus: "Atualizar Status",
      watched: "Assistido",
      watching: "Assistindo",
      watchlist: "Lista",
      dropped: "Abandonado"
    ),
    .esES: Strings(
      loginLabel: "Correo electrónico o nombre de usuario",
      loginPlaceholder: "Correo electrónico o nombre de usuario",
      passwordLabel: "Contraseña",
      passwordPlaceholder: "*********",
      accessButton: "Acceder",
      doNotHaveAccount: "¿No tienes una cuenta?",
      createNow: "Crea una ahora",
      loginRequired: "Por favor, introduce tu correo electrónico o nombre de usuario.",
      passwordRequired: "Por favor, introduce tu contraseña.",
      passwordLength: "Tu contraseña debe tener al menos 8 caracteres.",
      invalidCredentials: "Credenciales de inicio de sesión no válidas.",
      continueWithGoogle: "Continuar con Google",
      continueWithApple: "Continuar con Apple",
      or: "o",
      startNow: "Empieza ahora",
      startYourJourney: "Comienza tu viaje en unos pocos pasos.",
      emailLabel: "Correo electrónico",
      emailPlaceholder: "email@dominio.com",
      continueButton: "Continuar",
      alreadyHaveAccount: "¿Ya tienes una cuenta?",
      accessNow: "Accede ahora",
      selectUsername: "Selecciona tu nombre de usuario",
      selectUsernameDescription:
        "Elige tu nombre de usuario y finaliza tu registro para comenzar a usar la plataforma.",
      usernamePlaceholder: "juan-perez",
      finishSignUp: "Finalizar registro",
      emailRequired: "Por favor, introduce tu correo electrónico.",
      emailInvalid: "Por favor, introduce un correo electrónico válido.",
      usernameRequired: "Por favor, introduce un nombre de usuario.",
      emailAlreadyTaken: "Este correo electrónico ya está en uso.",
      usernameAlreadyTaken: "Este nombre de usuario ya está en uso.",
      signUpSuccess: "Registro exitoso. ¡Bienvenido! 🎉",
      searchPlaceholder: "Buscar películas, series, personas...",
      movies: "Películas",
      tvSeries: "Series de TV",
      people: "Personas",
      noResults: "No se encontraron resultados.",
      cancel: "Cancelar",
      popularMovies: "Películas Populares",
      popularTVSeries: "Series Populares",
      popularAnimes: "Animes Populares",
      popularDoramas: "Doramas Populares",
      animes: "Animes",
      doramas: "Doramas",
      seeAllMovies: "Ver todas las películas",
      seeAllTVSeries: "Ver todas las series",
      seeAllAnimes: "Ver todos los animes",
      seeAllDoramas: "Ver todos los doramas",
      settings: "Configuración",
      theme: "Tema",
      themeSystem: "Sistema",
      themeLight: "Claro",
      themeDark: "Oscuro",
      language: "Idioma",
      done: "Listo",
      signOut: "Cerrar sesión",
      whatDidYouThink: "¿Qué te pareció?",
      review: "Reseñar",
      reviewed: "Reseñado",
      shareYourOpinion: "Comparte tu opinión aquí...",
      containSpoilers: "Contiene spoilers",
      submitReview: "Enviar reseña",
      editReview: "Editar reseña",
      reviewRequired: "Por favor, escribe tu reseña.",
      reviewSuccess: "¡Reseña enviada con éxito!",
      reviewUpdateSuccess: "¡Reseña actualizada con éxito!",
      reviewDeleteSuccess: "¡Reseña eliminada con éxito!",
      tabReviews: "Reseñas",
      reviewSingular: "Reseña",
      tabWhereToWatch: "Dónde Ver",
      tabCredits: "Créditos",
      tabRecommendations: "Recomendaciones",
      tabSimilar: "Similares",
      tabImages: "Imágenes",
      tabVideos: "Videos",
      beFirstToReview: "Sé el primero en dejar tu opinión",
      seeAll: "Ver todas las reseñas",
      showMore: "Ver más",
      nowPlaying: "En Cartelera",
      popular: "Popular",
      topRated: "Mejor Valoradas",
      upcoming: "Próximamente",
      discover: "Descubrir",
      airingToday: "En Emisión Hoy",
      onTheAir: "En Emisión",
      images: "Imágenes",
      backdrops: "Fondos",
      posters: "Pósters",
      noImagesFound: "No se encontraron imágenes.",
      deleteReview: "Eliminar Reseña",
      deleteReviewConfirmation: "¿Estás seguro de que deseas eliminar esta reseña?",
      delete: "Eliminar",
      updateStatus: "Actualizar Estado",
      watched: "Visto",
      watching: "Viendo",
      watchlist: "Lista",
      dropped: "Abandonado"
    ),
    .frFR: Strings(
      loginLabel: "E-mail ou nom d'utilisateur",
      loginPlaceholder: "E-mail ou nom d'utilisateur",
      passwordLabel: "Mot de passe",
      passwordPlaceholder: "*********",
      accessButton: "Accéder",
      doNotHaveAccount: "Vous n'avez pas de compte?",
      createNow: "Créez-en un maintenant",
      loginRequired: "Veuillez entrer votre e-mail ou nom d'utilisateur.",
      passwordRequired: "Veuillez entrer votre mot de passe.",
      passwordLength: "Votre mot de passe doit contenir au moins 8 caractères.",
      invalidCredentials: "Identifiants de connexion invalides.",
      continueWithGoogle: "Continuer avec Google",
      continueWithApple: "Continuer avec Apple",
      or: "ou",
      startNow: "Commencez maintenant",
      startYourJourney: "Commencez votre voyage en quelques étapes.",
      emailLabel: "E-mail",
      emailPlaceholder: "email@domaine.com",
      continueButton: "Continuer",
      alreadyHaveAccount: "Vous avez déjà un compte?",
      accessNow: "Connectez-vous",
      selectUsername: "Choisissez votre nom d'utilisateur",
      selectUsernameDescription:
        "Choisissez votre nom d'utilisateur et terminez votre inscription pour commencer à utiliser la plateforme.",
      usernamePlaceholder: "jean-dupont",
      finishSignUp: "Terminer l'inscription",
      emailRequired: "Veuillez entrer votre e-mail.",
      emailInvalid: "Veuillez entrer un e-mail valide.",
      usernameRequired: "Veuillez entrer un nom d'utilisateur.",
      emailAlreadyTaken: "Cet e-mail est déjà utilisé.",
      usernameAlreadyTaken: "Ce nom d'utilisateur est déjà utilisé.",
      signUpSuccess: "Inscription réussie. Bienvenue! 🎉",
      searchPlaceholder: "Rechercher films, séries, personnes...",
      movies: "Films",
      tvSeries: "Séries TV",
      people: "Personnes",
      noResults: "Aucun résultat trouvé.",
      cancel: "Annuler",
      popularMovies: "Films Populaires",
      popularTVSeries: "Séries Populaires",
      popularAnimes: "Animes Populaires",
      popularDoramas: "Doramas Populaires",
      animes: "Animes",
      doramas: "Doramas",
      seeAllMovies: "Voir tous les films",
      seeAllTVSeries: "Voir toutes les séries",
      seeAllAnimes: "Voir tous les animes",
      seeAllDoramas: "Voir tous les doramas",
      settings: "Paramètres",
      theme: "Thème",
      themeSystem: "Système",
      themeLight: "Clair",
      themeDark: "Sombre",
      language: "Langue",
      done: "Terminé",
      signOut: "Déconnexion",
      whatDidYouThink: "Qu'en avez-vous pensé?",
      review: "Évaluer",
      reviewed: "Évalué",
      shareYourOpinion: "Partagez votre opinion ici...",
      containSpoilers: "Contient des spoilers",
      submitReview: "Soumettre l'avis",
      editReview: "Modifier l'avis",
      reviewRequired: "Veuillez écrire votre avis.",
      reviewSuccess: "Avis soumis avec succès!",
      reviewUpdateSuccess: "Avis mis à jour avec succès!",
      reviewDeleteSuccess: "Avis supprimé avec succès!",
      tabReviews: "Avis",
      reviewSingular: "Avis",
      tabWhereToWatch: "Où Regarder",
      tabCredits: "Crédits",
      tabRecommendations: "Recommandations",
      tabSimilar: "Similaires",
      tabImages: "Images",
      tabVideos: "Vidéos",
      beFirstToReview: "Soyez le premier à donner votre avis",
      seeAll: "Voir tous les avis",
      showMore: "Voir plus",
      nowPlaying: "À l'Affiche",
      popular: "Populaire",
      topRated: "Mieux Notés",
      upcoming: "Prochainement",
      discover: "Découvrir",
      airingToday: "Diffusé Aujourd'hui",
      onTheAir: "En Cours",
      images: "Images",
      backdrops: "Fonds d'écran",
      posters: "Affiches",
      noImagesFound: "Aucune image trouvée.",
      deleteReview: "Supprimer l'avis",
      deleteReviewConfirmation: "Êtes-vous sûr de vouloir supprimer cet avis?",
      delete: "Supprimer",
      updateStatus: "Mettre à jour le statut",
      watched: "Vu",
      watching: "En cours",
      watchlist: "À voir",
      dropped: "Abandonné"
    ),
    .deDE: Strings(
      loginLabel: "E-Mail oder Benutzername",
      loginPlaceholder: "E-Mail oder Benutzername",
      passwordLabel: "Passwort",
      passwordPlaceholder: "*********",
      accessButton: "Zugreifen",
      doNotHaveAccount: "Haben Sie kein Konto?",
      createNow: "Jetzt erstellen",
      loginRequired: "Bitte geben Sie Ihre E-Mail-Adresse oder Ihren Benutzernamen ein.",
      passwordRequired: "Bitte geben Sie Ihr Passwort ein.",
      passwordLength: "Ihr Passwort muss mindestens 8 Zeichen lang sein.",
      invalidCredentials: "Ungültige Anmeldeinformationen.",
      continueWithGoogle: "Weiter mit Google",
      continueWithApple: "Weiter mit Apple",
      or: "oder",
      startNow: "Jetzt starten",
      startYourJourney: "Beginnen Sie Ihre Reise in wenigen Schritten.",
      emailLabel: "E-Mail",
      emailPlaceholder: "email@domain.de",
      continueButton: "Weiter",
      alreadyHaveAccount: "Haben Sie bereits ein Konto?",
      accessNow: "Jetzt anmelden",
      selectUsername: "Wählen Sie Ihren Benutzernamen",
      selectUsernameDescription:
        "Wählen Sie Ihren Benutzernamen und schließen Sie Ihre Registrierung ab, um die Plattform zu nutzen.",
      usernamePlaceholder: "max-mustermann",
      finishSignUp: "Registrierung abschließen",
      emailRequired: "Bitte geben Sie Ihre E-Mail-Adresse ein.",
      emailInvalid: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
      usernameRequired: "Bitte geben Sie einen Benutzernamen ein.",
      emailAlreadyTaken: "Diese E-Mail-Adresse wird bereits verwendet.",
      usernameAlreadyTaken: "Dieser Benutzername ist bereits vergeben.",
      signUpSuccess: "Registrierung erfolgreich. Willkommen! 🎉",
      searchPlaceholder: "Filme, Serien, Personen suchen...",
      movies: "Filme",
      tvSeries: "TV-Serien",
      people: "Personen",
      noResults: "Keine Ergebnisse gefunden.",
      cancel: "Abbrechen",
      popularMovies: "Beliebte Filme",
      popularTVSeries: "Beliebte Serien",
      popularAnimes: "Beliebte Animes",
      popularDoramas: "Beliebte Doramas",
      animes: "Animes",
      doramas: "Doramas",
      seeAllMovies: "Alle Filme anzeigen",
      seeAllTVSeries: "Alle Serien anzeigen",
      seeAllAnimes: "Alle Animes anzeigen",
      seeAllDoramas: "Alle Doramas anzeigen",
      settings: "Einstellungen",
      theme: "Design",
      themeSystem: "System",
      themeLight: "Hell",
      themeDark: "Dunkel",
      language: "Sprache",
      done: "Fertig",
      signOut: "Abmelden",
      whatDidYouThink: "Was haben Sie gedacht?",
      review: "Bewerten",
      reviewed: "Bewertet",
      shareYourOpinion: "Teilen Sie Ihre Meinung hier...",
      containSpoilers: "Enthält Spoiler",
      submitReview: "Bewertung abschicken",
      editReview: "Bewertung bearbeiten",
      reviewRequired: "Bitte schreiben Sie Ihre Bewertung.",
      reviewSuccess: "Bewertung erfolgreich eingereicht!",
      reviewUpdateSuccess: "Bewertung erfolgreich aktualisiert!",
      reviewDeleteSuccess: "Bewertung erfolgreich gelöscht!",
      tabReviews: "Bewertungen",
      reviewSingular: "Bewertung",
      tabWhereToWatch: "Wo Ansehen",
      tabCredits: "Besetzung",
      tabRecommendations: "Empfehlungen",
      tabSimilar: "Ähnliche",
      tabImages: "Bilder",
      tabVideos: "Videos",
      beFirstToReview: "Sei der Erste, der seine Meinung teilt",
      seeAll: "Alle Bewertungen anzeigen",
      showMore: "Mehr anzeigen",
      nowPlaying: "Jetzt im Kino",
      popular: "Beliebt",
      topRated: "Bestbewertet",
      upcoming: "Demnächst",
      discover: "Entdecken",
      airingToday: "Heute im TV",
      onTheAir: "Auf Sendung",
      images: "Bilder",
      backdrops: "Hintergründe",
      posters: "Poster",
      noImagesFound: "Keine Bilder gefunden.",
      deleteReview: "Bewertung löschen",
      deleteReviewConfirmation: "Möchten Sie diese Bewertung wirklich löschen?",
      delete: "Löschen",
      updateStatus: "Status aktualisieren",
      watched: "Gesehen",
      watching: "Schaue ich",
      watchlist: "Watchlist",
      dropped: "Abgebrochen"
    ),
    .itIT: Strings(
      loginLabel: "E-mail o nome utente",
      loginPlaceholder: "E-mail o nome utente",
      passwordLabel: "Password",
      passwordPlaceholder: "*********",
      accessButton: "Accedi",
      doNotHaveAccount: "Non hai un account?",
      createNow: "Crea ora",
      loginRequired: "Inserisci il tuo indirizzo e-mail o nome utente.",
      passwordRequired: "Inserisci la tua password.",
      passwordLength: "La tua password deve contenere almeno 8 caratteri.",
      invalidCredentials: "Credenziali di accesso non valide.",
      continueWithGoogle: "Continua con Google",
      continueWithApple: "Continua con Apple",
      or: "o",
      startNow: "Inizia ora",
      startYourJourney: "Inizia il tuo viaggio in pochi passi.",
      emailLabel: "E-mail",
      emailPlaceholder: "email@dominio.com",
      continueButton: "Continua",
      alreadyHaveAccount: "Hai già un account?",
      accessNow: "Accedi ora",
      selectUsername: "Scegli il tuo nome utente",
      selectUsernameDescription:
        "Scegli il tuo nome utente e completa la registrazione per iniziare a usare la piattaforma.",
      usernamePlaceholder: "mario-rossi",
      finishSignUp: "Completa registrazione",
      emailRequired: "Inserisci la tua e-mail.",
      emailInvalid: "Inserisci un'e-mail valida.",
      usernameRequired: "Inserisci un nome utente.",
      emailAlreadyTaken: "Questa email è già in uso.",
      usernameAlreadyTaken: "Questo nome utente è già in uso.",
      signUpSuccess: "Registrazione completata. Benvenuto! 🎉",
      searchPlaceholder: "Cerca film, serie, persone...",
      movies: "Film",
      tvSeries: "Serie TV",
      people: "Persone",
      noResults: "Nessun risultato trovato.",
      cancel: "Annulla",
      popularMovies: "Film Popolari",
      popularTVSeries: "Serie Popolari",
      popularAnimes: "Anime Popolari",
      popularDoramas: "Dorama Popolari",
      animes: "Anime",
      doramas: "Dorama",
      seeAllMovies: "Vedi tutti i film",
      seeAllTVSeries: "Vedi tutte le serie",
      seeAllAnimes: "Vedi tutti gli anime",
      seeAllDoramas: "Vedi tutti i dorama",
      settings: "Impostazioni",
      theme: "Tema",
      themeSystem: "Sistema",
      themeLight: "Chiaro",
      themeDark: "Scuro",
      language: "Lingua",
      done: "Fatto",
      signOut: "Esci",
      whatDidYouThink: "Cosa ne pensi?",
      review: "Recensire",
      reviewed: "Recensito",
      shareYourOpinion: "Condividi la tua opinione qui...",
      containSpoilers: "Contiene spoiler",
      submitReview: "Invia recensione",
      editReview: "Modifica recensione",
      reviewRequired: "Scrivi la tua recensione.",
      reviewSuccess: "Recensione inviata con successo!",
      reviewUpdateSuccess: "Recensione aggiornata con successo!",
      reviewDeleteSuccess: "Recensione eliminata con successo!",
      tabReviews: "Recensioni",
      reviewSingular: "Recensione",
      tabWhereToWatch: "Dove Guardare",
      tabCredits: "Cast",
      tabRecommendations: "Raccomandazioni",
      tabSimilar: "Simili",
      tabImages: "Immagini",
      tabVideos: "Video",
      beFirstToReview: "Sii il primo a lasciare la tua opinione",
      seeAll: "Vedi tutte le recensioni",
      showMore: "Mostra di più",
      nowPlaying: "In Sala",
      popular: "Popolari",
      topRated: "Più Votati",
      upcoming: "Prossimamente",
      discover: "Scopri",
      airingToday: "In Onda Oggi",
      onTheAir: "In Onda",
      images: "Immagini",
      backdrops: "Sfondi",
      posters: "Locandine",
      noImagesFound: "Nessuna immagine trovata.",
      deleteReview: "Elimina recensione",
      deleteReviewConfirmation: "Sei sicuro di voler eliminare questa recensione?",
      delete: "Elimina",
      updateStatus: "Aggiorna stato",
      watched: "Visto",
      watching: "In visione",
      watchlist: "Da vedere",
      dropped: "Abbandonato"
    ),
    .jaJP: Strings(
      loginLabel: "メールアドレスまたはユーザー名",
      loginPlaceholder: "メールアドレスまたはユーザー名",
      passwordLabel: "パスワード",
      passwordPlaceholder: "*********",
      accessButton: "アクセス",
      doNotHaveAccount: "アカウントをお持ちではありませんか？",
      createNow: "今すぐ作成",
      loginRequired: "メールアドレスまたはユーザー名を入力してください。",
      passwordRequired: "パスワードを入力してください。",
      passwordLength: "パスワードは8文字以上でなければなりません。",
      invalidCredentials: "ログイン認証情報が無効です。",
      continueWithGoogle: "Googleで続ける",
      continueWithApple: "Appleで続ける",
      or: "または",
      startNow: "今すぐ始める",
      startYourJourney: "数ステップで旅を始めましょう。",
      emailLabel: "メールアドレス",
      emailPlaceholder: "email@domain.com",
      continueButton: "続ける",
      alreadyHaveAccount: "すでにアカウントをお持ちですか？",
      accessNow: "ログイン",
      selectUsername: "ユーザー名を選択",
      selectUsernameDescription: "ユーザー名を選択し、プラットフォームの利用を開始するためにサインアップを完了してください。",
      usernamePlaceholder: "taro-yamada",
      finishSignUp: "登録を完了",
      emailRequired: "メールアドレスを入力してください。",
      emailInvalid: "有効なメールアドレスを入力してください。",
      usernameRequired: "ユーザー名を入力してください。",
      emailAlreadyTaken: "このメールアドレスは既に使用されています。",
      usernameAlreadyTaken: "このユーザー名は既に使用されています。",
      signUpSuccess: "登録が完了しました。ようこそ！🎉",
      searchPlaceholder: "映画、シリーズ、人物を検索...",
      movies: "映画",
      tvSeries: "テレビシリーズ",
      people: "人物",
      noResults: "結果が見つかりません。",
      cancel: "キャンセル",
      popularMovies: "人気の映画",
      popularTVSeries: "人気のテレビシリーズ",
      popularAnimes: "人気のアニメ",
      popularDoramas: "人気のドラマ",
      animes: "アニメ",
      doramas: "ドラマ",
      seeAllMovies: "すべての映画を見る",
      seeAllTVSeries: "すべてのシリーズを見る",
      seeAllAnimes: "すべてのアニメを見る",
      seeAllDoramas: "すべてのドラマを見る",
      settings: "設定",
      theme: "テーマ",
      themeSystem: "システム",
      themeLight: "ライト",
      themeDark: "ダーク",
      language: "言語",
      done: "完了",
      signOut: "サインアウト",
      whatDidYouThink: "どう思いましたか？",
      review: "レビュー",
      reviewed: "レビュー済み",
      shareYourOpinion: "ここにあなたの意見を共有してください...",
      containSpoilers: "ネタバレを含む",
      submitReview: "レビューを送信",
      editReview: "レビューを編集",
      reviewRequired: "レビューを書いてください。",
      reviewSuccess: "レビューが正常に送信されました！",
      reviewUpdateSuccess: "レビューが正常に更新されました！",
      reviewDeleteSuccess: "レビューが正常に削除されました！",
      tabReviews: "レビュー",
      reviewSingular: "レビュー",
      tabWhereToWatch: "視聴方法",
      tabCredits: "キャスト",
      tabRecommendations: "おすすめ",
      tabSimilar: "類似作品",
      tabImages: "画像",
      tabVideos: "動画",
      beFirstToReview: "最初にレビューを書いてください",
      seeAll: "すべてのレビューを見る",
      showMore: "もっと見る",
      nowPlaying: "上映中",
      popular: "人気",
      topRated: "高評価",
      upcoming: "近日公開",
      discover: "発見",
      airingToday: "本日放送",
      onTheAir: "放送中",
      images: "画像",
      backdrops: "背景",
      posters: "ポスター",
      noImagesFound: "画像が見つかりません。",
      deleteReview: "レビューを削除",
      deleteReviewConfirmation: "このレビューを削除してもよろしいですか？",
      delete: "削除",
      updateStatus: "ステータスを更新",
      watched: "視聴済み",
      watching: "視聴中",
      watchlist: "ウォッチリスト",
      dropped: "中断"
    ),
  ]
}

struct Strings {
  // Login
  let loginLabel: String
  let loginPlaceholder: String
  let passwordLabel: String
  let passwordPlaceholder: String
  let accessButton: String
  let doNotHaveAccount: String
  let createNow: String
  let loginRequired: String
  let passwordRequired: String
  let passwordLength: String
  let invalidCredentials: String
  let continueWithGoogle: String
  let continueWithApple: String
  let or: String
  // Sign Up
  let startNow: String
  let startYourJourney: String
  let emailLabel: String
  let emailPlaceholder: String
  let continueButton: String
  let alreadyHaveAccount: String
  let accessNow: String
  let selectUsername: String
  let selectUsernameDescription: String
  let usernamePlaceholder: String
  let finishSignUp: String
  let emailRequired: String
  let emailInvalid: String
  let usernameRequired: String
  let emailAlreadyTaken: String
  let usernameAlreadyTaken: String
  let signUpSuccess: String
  // Search
  let searchPlaceholder: String
  let movies: String
  let tvSeries: String
  let people: String
  let noResults: String
  let cancel: String
  let popularMovies: String
  let popularTVSeries: String
  let popularAnimes: String
  let popularDoramas: String
  let animes: String
  let doramas: String
  let seeAllMovies: String
  let seeAllTVSeries: String
  let seeAllAnimes: String
  let seeAllDoramas: String
  // Settings
  let settings: String
  let theme: String
  let themeSystem: String
  let themeLight: String
  let themeDark: String
  let language: String
  let done: String
  let signOut: String
  // Reviews
  let whatDidYouThink: String
  let review: String
  let reviewed: String
  let shareYourOpinion: String
  let containSpoilers: String
  let submitReview: String
  let editReview: String
  let reviewRequired: String
  let reviewSuccess: String
  let reviewUpdateSuccess: String
  let reviewDeleteSuccess: String
  // Tabs
  let tabReviews: String
  let reviewSingular: String
  let tabWhereToWatch: String
  let tabCredits: String
  let tabRecommendations: String
  let tabSimilar: String
  let tabImages: String
  let tabVideos: String
  // Review List
  let beFirstToReview: String
  let seeAll: String
  let showMore: String
  // Movie Categories
  let nowPlaying: String
  let popular: String
  let topRated: String
  let upcoming: String
  let discover: String
  // TV Series Categories
  let airingToday: String
  let onTheAir: String
  // Images
  let images: String
  let backdrops: String
  let posters: String
  let noImagesFound: String
  // Delete Review
  let deleteReview: String
  let deleteReviewConfirmation: String
  let delete: String
  // Status
  let updateStatus: String
  let watched: String
  let watching: String
  let watchlist: String
  let dropped: String
}
