//
//  Strings.swift
//  Plotwist
//

import Foundation

enum L10n {
  static var current: Strings { strings[Language.current] ?? strings[.enUS]! }

  private static let strings: [Language: Strings] = [
    .enUS: Strings(
      // Login
      loginLabel: "Email or username",
      loginPlaceholder: "Email or username",
      passwordLabel: "Password",
      passwordPlaceholder: "*********",
      accessButton: "Access",
      doNotHaveAccount: "Don't have an account?",
      createNow: "Create now",
      loginRequired: "Please enter your email or username.",
      passwordRequired: "Please enter your password.",
      passwordLength: "Your password must be at least 8 characters long.",
      invalidCredentials: "Invalid login credentials.",
      continueWithGoogle: "Continue with Google",
      continueWithApple: "Continue with Apple",
      or: "or",
      continueAsGuest: "Continue as guest",
      createAccount: "Create account",
      welcomeSubtitle: "Track movies, series, animes and doramas",
      welcomeTitle: "All your entertainment.\nOne place.",
      welcomeDescription: "Track, discover and share movies, series, animes and doramas. Join the community.",
      signInToAccessProfile: "Sign in to access your profile",
      signInToAccessProfileDescription: "Create an account to track your movies, series, and share reviews with the community.",
      // Sign Up
      startNow: "Start now",
      startYourJourney: "Start your journey in just a few steps.",
      emailLabel: "Email",
      emailPlaceholder: "email@domain.com",
      continueButton: "Continue",
      alreadyHaveAccount: "Already have an account?",
      accessNow: "Access now",
      selectUsername: "Select your username",
      selectUsernameDescription:
        "Choose your username and finish your sign-up to start using the platform.",
      usernamePlaceholder: "john-doe",
      finishSignUp: "Finish sign-up",
      emailRequired: "Please enter your email.",
      emailInvalid: "Please enter a valid email.",
      usernameRequired: "Please enter a username.",
      emailAlreadyTaken: "This email is already in use.",
      usernameAlreadyTaken: "This username is already taken.",
      signUpSuccess: "Registration successful. Welcome! 🎉",
      // Search
      searchPlaceholder: "Search movies, series, people...",
      movies: "Movies",
      tvSeries: "TV Series",
      people: "People",
      noResults: "No results found.",
      cancel: "Cancel",
      recentSearches: "Recent Searches",
      clearAll: "Clear",
      youAreLookingFor: "You are looking for:",
      popularMovies: "Popular movies",
      popularTVSeries: "Popular TV series",
      popularAnimes: "Popular animes",
      popularDoramas: "Popular doramas",
      animes: "Animes",
      doramas: "Doramas",
      seeAllMovies: "See all movies",
      seeAllTVSeries: "See all series",
      seeAllAnimes: "See all animes",
      seeAllDoramas: "See all doramas",
      settings: "Settings",
      theme: "Theme",
      themeSystem: "System",
      themeLight: "Light",
      themeDark: "Dark",
      language: "Language",
      done: "Done",
      signOut: "Sign Out",
      // Reviews
      whatDidYouThink: "What did you think?",
      review: "Review",
      reviewed: "Reviewed",
      shareYourOpinion: "Share your opinion here...",
      containSpoilers: "Contains spoilers",
      tapToReveal: "Tap to reveal",
      submitReview: "Submit review",
      editReview: "Edit review",
      reviewRequired: "Please write your review.",
      reviewSuccess: "Review submitted successfully!",
      reviewUpdateSuccess: "Review updated successfully!",
      reviewDeleteSuccess: "Review deleted successfully!",
      tabReviews: "Reviews",
      reviewSingular: "Review",
      tabWhereToWatch: "Where to Watch",
      tabCredits: "Credits",
      tabRecommendations: "Recommendations",
      tabSimilar: "Similar",
      tabImages: "Images",
      tabVideos: "Videos",
      beFirstToReview: "Be the first to leave your opinion",
      seeAll: "See all reviews",
      showMore: "Show more",
      // Movie Categories
      nowPlaying: "Now playing",
      popular: "Popular",
      topRated: "Top rated",
      upcoming: "Upcoming",
      discover: "Discover",
      // TV Series Categories
      airingToday: "Airing today",
      onTheAir: "On the air",
      // Images
      images: "Images",
      backdrops: "Backdrops",
      posters: "Posters",
      noImagesFound: "No images found.",
      deleteReview: "Delete Review",
      deleteReviewConfirmation: "Are you sure you want to delete this review?",
      delete: "Delete",
      // Status
      updateStatus: "Update Status",
      watched: "Watched",
      watching: "Watching",
      watchlist: "Watchlist",
      dropped: "Dropped",
      // Rewatch
      watchLog: "Watch Log",
      addRewatch: "Add Rewatch",
      firstTime: "1st time",
      nthTime: "%@ time",
      // Episode Progress
      markAsWatched: "Mark as watched",
      nextEpisode: "Next episode",
      previousEpisode: "Previous episode",
      nextSeason: "Next season",
      previousSeason: "Previous season",
      // Where to Watch
      stream: "Stream",
      rent: "Rent",
      buy: "Buy",
      unavailable: "Unavailable",
      // Profile
      profile: "Profile",
      memberSince: "Member since",
      editProfile: "Edit",
      accountData: "Account",
      information: "Information",
      preferences: "Preferences",
      editPicture: "Edit picture",
      name: "Name",
      username: "Username",
      region: "Region",
      streamingServices: "Streaming Services",
      notSet: "Not set",
      searchRegion: "Search region...",
      searchStreamingServices: "Search services...",
      selectRegionFirst: "Select a region first",
      servicesSelected: "%d selected",
      streamingServicesHint: "Showing services available in your selected region.",
      resultsBasedOnPreferences: "Results based on your preferences",
      collection: "Collection",
      reviews: "Reviews",
      profileNoReviewsTitle: "No reviews yet",
      profileNoReviewsSubtitle: "After watching a movie or series, share what you thought and your reviews will show up here.",
      soundtracks: "Soundtracks",
      biography: "Biography",
      biographyPlaceholder: "Tell us about yourself...",
      // Home
      goodMorning: "Good morning",
      goodAfternoon: "Good afternoon",
      goodEvening: "Good evening",
      continueWatching: "Continue watching",
      upNext: "Up next",
      // Collection
      partOf: "Part of",
      seeCollection: "See Collection",
      // Seasons
      tabSeasons: "Seasons",
      episodes: "Episodes",
      episodesCount: "%d episodes",
      episodesWatchedCount: "%d of %total watched",
      grid: "Grid",
      overview: "Overview",
      // Ratings
      ratingAwesome: "Awesome",
      ratingGreat: "Great",
      ratingGood: "Good",
      ratingBad: "Bad",
      ratingTerrible: "Terrible",
      // Onboarding
      onboardingWelcomeTitle: "Track, discover and\nnever miss a title 🍿",
      onboardingWelcomeSubtitle: "Organize your movies, series and anime in one place. Build the perfect watchlist tailored to you.",
      onboardingGetStarted: "Get started",
      onboardingNameTitle: "Let's personalize\nyour experience 👋",
      onboardingNameSubtitle: "Tell us your name so we can make Plotwist feel like yours",
      onboardingNamePlaceholder: "Your name",
      onboardingContentTypeTitle: "What kind of content\ndo you enjoy most? 🎬",
      onboardingMovies: "Movies",
      onboardingSeries: "TV Series",
      onboardingAnime: "Anime",
      onboardingDorama: "K-Drama",
      onboardingGenresTitle: "Pick your favorite genres 🎯",
      onboardingGenresSubtitle: "We'll use your taste to recommend titles you'll actually love",
      onboardingSelectGenres: "Select at least 1",
      onboardingMoreToGo: "more to go",
      onboardingSkip: "Skip for now",
      onboardingAddTitlesTitle: "Now the fun part! 🎬",
      onboardingAddTitlesSubtitle: "Add 5 titles to your watchlist",
      onboardingDiscoverTitle: "Swipe to build\nyour collection 🍿",
      onboardingDiscoverSubtitle: "Right to save, left to skip, up if watched, down if watching",
      onboardingWantToWatch: "Want to watch",
      onboardingAlreadyWatched: "Already watched",
      onboardingWatching: "Watching",
      onboardingNotInterested: "Not interested",
      onboardingNoMoreItems: "You've seen them all!",
      onboardingReadyToContinue: "Ready to continue!",
      onboardingAdded: "added",
      onboardingSearchPlaceholder: "Search for a title...",
      onboardingPopularNow: "Popular right now",
      onboardingAddMore: "Add more",
      onboardingContinueToApp: "Let's go!",
      onboardingCelebrationTitle: "You're all set! 🎉",
      onboardingCelebrationSubtitle: "Your personalized experience is ready. Enjoy Plotwist!",
      onboardingGoToHome: "Go to Home",
      onboardingLoginTitle: "Sign in to Plotwist",
      onboardingLoginSubtitle: "Create an account to review, track your progress, and sync across all your devices.",
      onboardingNotNow: "Not now",
      // Genres
      genreAction: "Action",
      genreAdventure: "Adventure",
      genreAnimation: "Animation",
      genreComedy: "Comedy",
      genreCrime: "Crime",
      genreDocumentary: "Documentary",
      genreDrama: "Drama",
      genreFantasy: "Fantasy",
      genreHistory: "History",
      genreHorror: "Horror",
      genreMusic: "Music",
      genreRomance: "Romance",
      genreSciFi: "Sci-Fi",
      genreThriller: "Thriller",
      genreWar: "War",
      genreWestern: "Western",
      genreActionAdventure: "Action & Adventure",
      genreSciFiFantasy: "Sci-Fi & Fantasy",
      genreWarPolitics: "War & Politics",
      genreMystery: "Mystery",
      genreFamily: "Family",
      genreReality: "Reality",
      // Notifications
      notificationPromptTitle: "Stay updated",
      notificationPromptSeries: "Get notified when new episodes drop",
      notificationPromptWatchlist: "Weekly reminder of your watchlist",
      notificationAllow: "Allow notifications",
      // Stats
      stats: "Stats",
      series: "Series",
      timeWatched: "Time Watched",
      hour: "hour",
      hours: "hours",
      days: "days",
      topGenres: "Top Genres",
      collectionBreakdown: "Collection Breakdown",
      couldNotLoadStats: "Could not load stats",
      tryAgain: "Try again",
      favoriteGenres: "Favorite Genres",
      content: "Content",
      genres: "Genres",
      collectionStatus: "Collection Status",
      itemsInCollection: "items in collection",
      bestReviews: "Best Reviews",
      daysOfContent: "days of content",
      othersGenres: "Others",
      // Home Engagement
      forYou: "For you",
      basedOnYourTaste: "Because you like %@",
      trendingThisWeek: "Trending this week",
      inTheaters: "In theaters",
      topRatedMovies: "Top rated movies",
      topRatedSeries: "Top rated series",
      topRatedAnimes: "Top rated animes",
      topRatedDoramas: "Top rated doramas",
      featured: "Featured",
      // Feedback
      feedbackTitle: "Help & Feedback",
      feedbackReportProblem: "Report a problem",
      feedbackSuggestImprovement: "Suggest improvement",
      feedbackTypeLabel: "Type",
      feedbackTypeBug: "Bug / Problem",
      feedbackTypeIdea: "Idea / Suggestion",
      feedbackDescriptionLabel: "Description",
      feedbackDescriptionPlaceholder: "Describe what happened or what you'd like to see...",
      feedbackScreenshotLabel: "Screenshot",
      feedbackAddScreenshot: "Add screenshot",
      feedbackSubmit: "Submit",
      feedbackSubmitSuccess: "Thank you for your feedback!",
      feedbackHelpTitle: "Help"
    ),
    .ptBR: Strings(
      loginLabel: "E-mail ou nome de usuário",
      loginPlaceholder: "E-mail ou nome de usuário",
      passwordLabel: "Senha",
      passwordPlaceholder: "*********",
      accessButton: "Acessar",
      doNotHaveAccount: "Não tem uma conta?",
      createNow: "Crie agora",
      loginRequired: "Por favor, insira seu e-mail ou nome de usuário.",
      passwordRequired: "Por favor, insira sua senha.",
      passwordLength: "Sua senha deve ter pelo menos 8 caracteres.",
      invalidCredentials: "Credenciais de login inválidas.",
      continueWithGoogle: "Continuar com Google",
      continueWithApple: "Continuar com Apple",
      or: "ou",
      continueAsGuest: "Continuar como convidado",
      createAccount: "Criar conta",
      welcomeSubtitle: "Acompanhe filmes, séries, animes e doramas",
      welcomeTitle: "Todo seu entretenimento.\nEm um só lugar.",
      welcomeDescription: "Acompanhe, descubra e compartilhe filmes, séries, animes e doramas. Junte-se à comunidade.",
      signInToAccessProfile: "Entre para acessar seu perfil",
      signInToAccessProfileDescription: "Crie uma conta para acompanhar seus filmes, séries e compartilhar avaliações com a comunidade.",
      startNow: "Comece agora",
      startYourJourney: "Comece sua jornada em poucos passos.",
      emailLabel: "E-mail",
      emailPlaceholder: "email@dominio.com",
      continueButton: "Continuar",
      alreadyHaveAccount: "Já tem uma conta?",
      accessNow: "Acesse agora",
      selectUsername: "Escolha seu nome de usuário",
      selectUsernameDescription:
        "Escolha seu nome de usuário e finalize seu cadastro para começar a usar a plataforma.",
      usernamePlaceholder: "joao-silva",
      finishSignUp: "Finalizar cadastro",
      emailRequired: "Por favor, insira seu e-mail.",
      emailInvalid: "Por favor, insira um e-mail válido.",
      usernameRequired: "Por favor, insira um nome de usuário.",
      emailAlreadyTaken: "Este e-mail já está em uso.",
      usernameAlreadyTaken: "Este nome de usuário já está em uso.",
      signUpSuccess: "Cadastro realizado com sucesso. Bem-vindo! 🎉",
      searchPlaceholder: "Buscar filmes, séries, pessoas...",
      movies: "Filmes",
      tvSeries: "Séries de TV",
      people: "Pessoas",
      noResults: "Nenhum resultado encontrado.",
      cancel: "Cancelar",
      recentSearches: "Pesquisas Recentes",
      clearAll: "Limpar",
      youAreLookingFor: "Você está procurando por:",
      popularMovies: "Filmes populares",
      popularTVSeries: "Séries populares",
      popularAnimes: "Animes populares",
      popularDoramas: "Doramas populares",
      animes: "Animes",
      doramas: "Doramas",
      seeAllMovies: "Ver todos os filmes",
      seeAllTVSeries: "Ver todas as séries",
      seeAllAnimes: "Ver todos os animes",
      seeAllDoramas: "Ver todos os doramas",
      settings: "Configurações",
      theme: "Tema",
      themeSystem: "Sistema",
      themeLight: "Claro",
      themeDark: "Escuro",
      language: "Idioma",
      done: "Concluído",
      signOut: "Sair",
      whatDidYouThink: "O que você achou?",
      review: "Avaliar",
      reviewed: "Avaliado",
      shareYourOpinion: "Compartilhe sua opinião aqui...",
      containSpoilers: "Contém spoilers",
      tapToReveal: "Toque para revelar",
      submitReview: "Enviar avaliação",
      editReview: "Editar avaliação",
      reviewRequired: "Por favor, escreva sua avaliação.",
      reviewSuccess: "Avaliação enviada com sucesso!",
      reviewUpdateSuccess: "Avaliação atualizada com sucesso!",
      reviewDeleteSuccess: "Avaliação excluída com sucesso!",
      tabReviews: "Avaliações",
      reviewSingular: "Avaliação",
      tabWhereToWatch: "Onde Assistir",
      tabCredits: "Elenco",
      tabRecommendations: "Recomendações",
      tabSimilar: "Similares",
      tabImages: "Imagens",
      tabVideos: "Vídeos",
      beFirstToReview: "Seja o primeiro a deixar sua opinião",
      seeAll: "Ver todas as avaliações",
      showMore: "Ver mais",
      nowPlaying: "Em cartaz",
      popular: "Popular",
      topRated: "Mais bem avaliados",
      upcoming: "Em breve",
      discover: "Descobrir",
      airingToday: "No ar hoje",
      onTheAir: "Em exibição",
      images: "Imagens",
      backdrops: "Backdrops",
      posters: "Pôsteres",
      noImagesFound: "Nenhuma imagem encontrada.",
      deleteReview: "Excluir Avaliação",
      deleteReviewConfirmation: "Tem certeza que deseja excluir esta avaliação?",
      delete: "Excluir",
      updateStatus: "Atualizar Status",
      watched: "Assistido",
      watching: "Assistindo",
      watchlist: "Lista",
      dropped: "Abandonado",
      watchLog: "Registro de visualizações",
      addRewatch: "Adicionar rewatch",
      firstTime: "1ª vez",
      nthTime: "%@ vez",
      markAsWatched: "Marcar como assistido",
      nextEpisode: "Próximo episódio",
      previousEpisode: "Episódio anterior",
      nextSeason: "Próxima temporada",
      previousSeason: "Temporada anterior",
      stream: "Streaming",
      rent: "Alugar",
      buy: "Comprar",
      unavailable: "Indisponível",
      profile: "Perfil",
      memberSince: "Membro desde",
      editProfile: "Editar",
      accountData: "Conta",
      information: "Informações",
      preferences: "Preferências",
      editPicture: "Editar foto",
      name: "Nome",
      username: "Nome de usuário",
      region: "Região",
      streamingServices: "Serviços de Streaming",
      notSet: "Não definido",
      searchRegion: "Buscar região...",
      searchStreamingServices: "Buscar serviços...",
      selectRegionFirst: "Selecione uma região primeiro",
      servicesSelected: "%d selecionados",
      streamingServicesHint: "Exibindo serviços disponíveis na região selecionada.",
      resultsBasedOnPreferences: "Resultados baseados nas suas preferências",
      collection: "Coleção",
      reviews: "Reviews",
      profileNoReviewsTitle: "Nenhuma review ainda",
      profileNoReviewsSubtitle: "Depois de assistir um filme ou série, compartilhe o que achou e suas reviews aparecerão aqui.",
      soundtracks: "Trilhas",
      biography: "Biografia",
      biographyPlaceholder: "Conte um pouco sobre você...",
      // Home
      goodMorning: "Bom dia",
      goodAfternoon: "Boa tarde",
      goodEvening: "Boa noite",
      continueWatching: "Continuar assistindo",
      upNext: "Para assistir",
      // Collection
      partOf: "Parte de",
      seeCollection: "Ver Coleção",
      // Seasons
      tabSeasons: "Temporadas",
      episodes: "Episódios",
      episodesCount: "%d episódios",
      episodesWatchedCount: "%d de %total assistidos",
      grid: "Grade",
      overview: "Visão Geral",
      // Ratings
      ratingAwesome: "Incrível",
      ratingGreat: "Ótimo",
      ratingGood: "Bom",
      ratingBad: "Ruim",
      ratingTerrible: "Péssimo",
      // Onboarding
      onboardingWelcomeTitle: "Organize, descubra e\nnunca perca um título 🍿",
      onboardingWelcomeSubtitle: "Seus filmes, séries e animes em um só lugar. Monte a watchlist perfeita para você.",
      onboardingGetStarted: "Começar",
      onboardingNameTitle: "Vamos personalizar\nsua experiência 👋",
      onboardingNameSubtitle: "Nos diga seu nome para deixar o Plotwist com a sua cara",
      onboardingNamePlaceholder: "Seu nome",
      onboardingContentTypeTitle: "Que tipo de conteúdo\nvocê mais curte? 🎬",
      onboardingMovies: "Filmes",
      onboardingSeries: "Séries",
      onboardingAnime: "Anime",
      onboardingDorama: "Doramas",
      onboardingGenresTitle: "Escolha seus gêneros favoritos 🎯",
      onboardingGenresSubtitle: "Vamos usar seu gosto para recomendar títulos que você vai amar",
      onboardingSelectGenres: "Selecione pelo menos 1",
      onboardingMoreToGo: "faltando",
      onboardingSkip: "Pular por agora",
      onboardingAddTitlesTitle: "Agora a parte divertida! 🎬",
      onboardingAddTitlesSubtitle: "Adicione 5 títulos à sua watchlist",
      onboardingDiscoverTitle: "Deslize para montar\nsua coleção 🍿",
      onboardingDiscoverSubtitle: "Direita para salvar, esquerda para pular, cima se já assistiu, baixo se assistindo",
      onboardingWantToWatch: "Quero assistir",
      onboardingAlreadyWatched: "Já assisti",
      onboardingWatching: "Assistindo",
      onboardingNotInterested: "Não tenho interesse",
      onboardingNoMoreItems: "Você viu todos!",
      onboardingReadyToContinue: "Pronto para continuar!",
      onboardingAdded: "adicionados",
      onboardingSearchPlaceholder: "Buscar um título...",
      onboardingPopularNow: "Popular agora",
      onboardingAddMore: "Adicione mais",
      onboardingContinueToApp: "Bora!",
      onboardingCelebrationTitle: "Tudo pronto! 🎉",
      onboardingCelebrationSubtitle: "Sua experiência personalizada está pronta. Aproveite o Plotwist!",
      onboardingGoToHome: "Ir para Home",
      onboardingLoginTitle: "Entre no Plotwist",
      onboardingLoginSubtitle: "Crie uma conta para avaliar, acompanhar seu progresso e sincronizar em todos os seus dispositivos.",
      onboardingNotNow: "Agora não",
      // Genres
      genreAction: "Ação",
      genreAdventure: "Aventura",
      genreAnimation: "Animação",
      genreComedy: "Comédia",
      genreCrime: "Crime",
      genreDocumentary: "Documentário",
      genreDrama: "Drama",
      genreFantasy: "Fantasia",
      genreHistory: "História",
      genreHorror: "Terror",
      genreMusic: "Musical",
      genreRomance: "Romance",
      genreSciFi: "Ficção Científica",
      genreThriller: "Suspense",
      genreWar: "Guerra",
      genreWestern: "Faroeste",
      genreActionAdventure: "Ação e Aventura",
      genreSciFiFantasy: "Ficção e Fantasia",
      genreWarPolitics: "Guerra e Política",
      genreMystery: "Mistério",
      genreFamily: "Família",
      genreReality: "Reality",
      // Notifications
      notificationPromptTitle: "Fique por dentro",
      notificationPromptSeries: "Saiba quando novos episódios saírem",
      notificationPromptWatchlist: "Lembrete semanal da sua watchlist",
      notificationAllow: "Permitir notificações",
      // Stats
      stats: "Estatísticas",
      series: "Séries",
      timeWatched: "Tempo Assistido",
      hour: "hora",
      hours: "horas",
      days: "dias",
      topGenres: "Gêneros Favoritos",
      collectionBreakdown: "Distribuição da Coleção",
      couldNotLoadStats: "Não foi possível carregar estatísticas",
      tryAgain: "Tentar novamente",
      favoriteGenres: "Gêneros Favoritos",
      content: "Conteúdo",
      genres: "Gêneros",
      collectionStatus: "Status da Coleção",
      itemsInCollection: "itens na coleção",
      bestReviews: "Melhores Reviews",
      daysOfContent: "dias de conteúdo",
      othersGenres: "Outros",
      // Home Engagement
      forYou: "Para você",
      basedOnYourTaste: "Porque você gosta de %@",
      trendingThisWeek: "Em alta esta semana",
      inTheaters: "Nos cinemas",
      topRatedMovies: "Filmes mais bem avaliados",
      topRatedSeries: "Séries mais bem avaliadas",
      topRatedAnimes: "Animes mais bem avaliados",
      topRatedDoramas: "Doramas mais bem avaliados",
      featured: "Destaque",
      // Feedback
      feedbackTitle: "Ajuda e Feedback",
      feedbackReportProblem: "Reportar um problema",
      feedbackSuggestImprovement: "Sugerir melhoria",
      feedbackTypeLabel: "Tipo",
      feedbackTypeBug: "Bug / Problema",
      feedbackTypeIdea: "Ideia / Sugestão",
      feedbackDescriptionLabel: "Descrição",
      feedbackDescriptionPlaceholder: "Descreva o que aconteceu ou o que gostaria de ver...",
      feedbackScreenshotLabel: "Captura de tela",
      feedbackAddScreenshot: "Adicionar captura",
      feedbackSubmit: "Enviar",
      feedbackSubmitSuccess: "Obrigado pelo seu feedback!",
      feedbackHelpTitle: "Ajuda"
    ),
    .esES: Strings(
      loginLabel: "Correo electrónico o nombre de usuario",
      loginPlaceholder: "Correo electrónico o nombre de usuario",
      passwordLabel: "Contraseña",
      passwordPlaceholder: "*********",
      accessButton: "Acceder",
      doNotHaveAccount: "¿No tienes una cuenta?",
      createNow: "Crea una ahora",
      loginRequired: "Por favor, introduce tu correo electrónico o nombre de usuario.",
      passwordRequired: "Por favor, introduce tu contraseña.",
      passwordLength: "Tu contraseña debe tener al menos 8 caracteres.",
      invalidCredentials: "Credenciales de inicio de sesión no válidas.",
      continueWithGoogle: "Continuar con Google",
      continueWithApple: "Continuar con Apple",
      or: "o",
      continueAsGuest: "Continuar como invitado",
      createAccount: "Crear cuenta",
      welcomeSubtitle: "Sigue películas, series, animes y doramas",
      welcomeTitle: "Todo tu entretenimiento.\nEn un solo lugar.",
      welcomeDescription: "Sigue, descubre y comparte películas, series, animes y doramas. Únete a la comunidad.",
      signInToAccessProfile: "Inicia sesión para acceder a tu perfil",
      signInToAccessProfileDescription: "Crea una cuenta para seguir tus películas, series y compartir reseñas con la comunidad.",
      startNow: "Empieza ahora",
      startYourJourney: "Comienza tu viaje en unos pocos pasos.",
      emailLabel: "Correo electrónico",
      emailPlaceholder: "email@dominio.com",
      continueButton: "Continuar",
      alreadyHaveAccount: "¿Ya tienes una cuenta?",
      accessNow: "Accede ahora",
      selectUsername: "Selecciona tu nombre de usuario",
      selectUsernameDescription:
        "Elige tu nombre de usuario y finaliza tu registro para comenzar a usar la plataforma.",
      usernamePlaceholder: "juan-perez",
      finishSignUp: "Finalizar registro",
      emailRequired: "Por favor, introduce tu correo electrónico.",
      emailInvalid: "Por favor, introduce un correo electrónico válido.",
      usernameRequired: "Por favor, introduce un nombre de usuario.",
      emailAlreadyTaken: "Este correo electrónico ya está en uso.",
      usernameAlreadyTaken: "Este nombre de usuario ya está en uso.",
      signUpSuccess: "Registro exitoso. ¡Bienvenido! 🎉",
      searchPlaceholder: "Buscar películas, series, personas...",
      movies: "Películas",
      tvSeries: "Series de TV",
      people: "Personas",
      noResults: "No se encontraron resultados.",
      cancel: "Cancelar",
      recentSearches: "Búsquedas Recientes",
      clearAll: "Limpiar",
      youAreLookingFor: "Estás buscando:",
      popularMovies: "Películas populares",
      popularTVSeries: "Series populares",
      popularAnimes: "Animes populares",
      popularDoramas: "Doramas populares",
      animes: "Animes",
      doramas: "Doramas",
      seeAllMovies: "Ver todas las películas",
      seeAllTVSeries: "Ver todas las series",
      seeAllAnimes: "Ver todos los animes",
      seeAllDoramas: "Ver todos los doramas",
      settings: "Configuración",
      theme: "Tema",
      themeSystem: "Sistema",
      themeLight: "Claro",
      themeDark: "Oscuro",
      language: "Idioma",
      done: "Listo",
      signOut: "Cerrar sesión",
      whatDidYouThink: "¿Qué te pareció?",
      review: "Reseñar",
      reviewed: "Reseñado",
      shareYourOpinion: "Comparte tu opinión aquí...",
      containSpoilers: "Contiene spoilers",
      tapToReveal: "Toca para revelar",
      submitReview: "Enviar reseña",
      editReview: "Editar reseña",
      reviewRequired: "Por favor, escribe tu reseña.",
      reviewSuccess: "¡Reseña enviada con éxito!",
      reviewUpdateSuccess: "¡Reseña actualizada con éxito!",
      reviewDeleteSuccess: "¡Reseña eliminada con éxito!",
      tabReviews: "Reseñas",
      reviewSingular: "Reseña",
      tabWhereToWatch: "Dónde Ver",
      tabCredits: "Créditos",
      tabRecommendations: "Recomendaciones",
      tabSimilar: "Similares",
      tabImages: "Imágenes",
      tabVideos: "Videos",
      beFirstToReview: "Sé el primero en dejar tu opinión",
      seeAll: "Ver todas las reseñas",
      showMore: "Ver más",
      nowPlaying: "En cartelera",
      popular: "Popular",
      topRated: "Mejor valoradas",
      upcoming: "Próximamente",
      discover: "Descubrir",
      airingToday: "En emisión hoy",
      onTheAir: "En emisión",
      images: "Imágenes",
      backdrops: "Fondos",
      posters: "Pósters",
      noImagesFound: "No se encontraron imágenes.",
      deleteReview: "Eliminar Reseña",
      deleteReviewConfirmation: "¿Estás seguro de que deseas eliminar esta reseña?",
      delete: "Eliminar",
      updateStatus: "Actualizar Estado",
      watched: "Visto",
      watching: "Viendo",
      watchlist: "Lista",
      dropped: "Abandonado",
      watchLog: "Registro de visualizaciones",
      addRewatch: "Agregar rewatch",
      firstTime: "1ª vez",
      nthTime: "%@ vez",
      markAsWatched: "Marcar como visto",
      nextEpisode: "Siguiente episodio",
      previousEpisode: "Episodio anterior",
      nextSeason: "Siguiente temporada",
      previousSeason: "Temporada anterior",
      stream: "Streaming",
      rent: "Alquilar",
      buy: "Comprar",
      unavailable: "No disponible",
      profile: "Perfil",
      memberSince: "Miembro desde",
      editProfile: "Editar",
      accountData: "Cuenta",
      information: "Información",
      preferences: "Preferencias",
      editPicture: "Editar foto",
      name: "Nombre",
      username: "Nombre de usuario",
      region: "Región",
      streamingServices: "Servicios de Streaming",
      notSet: "No definido",
      searchRegion: "Buscar región...",
      searchStreamingServices: "Buscar servicios...",
      selectRegionFirst: "Seleccione una región primero",
      servicesSelected: "%d seleccionados",
      streamingServicesHint: "Mostrando servicios disponibles en la región seleccionada.",
      resultsBasedOnPreferences: "Resultados según tus preferencias",
      collection: "Colección",
      reviews: "Reseñas",
      profileNoReviewsTitle: "Sin reseñas todavía",
      profileNoReviewsSubtitle: "Después de ver una película o serie, comparte lo que piensas y tus reseñas aparecerán aquí.",
      soundtracks: "Bandas Sonoras",
      biography: "Biografía",
      biographyPlaceholder: "Cuéntanos sobre ti...",
      // Home
      goodMorning: "Buenos días",
      goodAfternoon: "Buenas tardes",
      goodEvening: "Buenas noches",
      continueWatching: "Seguir viendo",
      upNext: "Próximos",
      // Collection
      partOf: "Parte de",
      seeCollection: "Ver Colección",
      // Seasons
      tabSeasons: "Temporadas",
      episodes: "Episodios",
      episodesCount: "%d episodios",
      episodesWatchedCount: "%d de %total vistos",
      grid: "Cuadrícula",
      overview: "Resumen",
      // Ratings
      ratingAwesome: "Increíble",
      ratingGreat: "Genial",
      ratingGood: "Bueno",
      ratingBad: "Malo",
      ratingTerrible: "Terrible",
      // Onboarding
      onboardingWelcomeTitle: "Organiza, descubre y\nnunca pierdas un título 🍿",
      onboardingWelcomeSubtitle: "Tus películas, series y anime en un solo lugar. Crea la watchlist perfecta para ti.",
      onboardingGetStarted: "Empezar",
      onboardingNameTitle: "Vamos a personalizar\ntu experiencia 👋",
      onboardingNameSubtitle: "Dinos tu nombre para que Plotwist se sienta tuyo",
      onboardingNamePlaceholder: "Tu nombre",
      onboardingContentTypeTitle: "¿Qué tipo de contenido\ndisfrutas más? 🎬",
      onboardingMovies: "Películas",
      onboardingSeries: "Series",
      onboardingAnime: "Anime",
      onboardingDorama: "K-Drama",
      onboardingGenresTitle: "Elige tus géneros favoritos 🎯",
      onboardingGenresSubtitle: "Usaremos tu gusto para recomendarte títulos que te encantarán",
      onboardingSelectGenres: "Selecciona al menos 1",
      onboardingMoreToGo: "más para continuar",
      onboardingSkip: "Saltar por ahora",
      onboardingAddTitlesTitle: "¡Ahora lo divertido! 🎬",
      onboardingAddTitlesSubtitle: "Agrega 5 títulos a tu watchlist",
      onboardingDiscoverTitle: "Desliza para crear\ntu colección 🍿",
      onboardingDiscoverSubtitle: "Derecha para guardar, izquierda para pasar, arriba si ya lo viste, abajo si lo estás viendo",
      onboardingWantToWatch: "Quiero ver",
      onboardingAlreadyWatched: "Ya lo vi",
      onboardingWatching: "Viendo",
      onboardingNotInterested: "No me interesa",
      onboardingNoMoreItems: "¡Los viste todos!",
      onboardingReadyToContinue: "¡Listo para continuar!",
      onboardingAdded: "agregados",
      onboardingSearchPlaceholder: "Buscar un título...",
      onboardingPopularNow: "Popular ahora",
      onboardingAddMore: "Agrega más",
      onboardingContinueToApp: "¡Vamos!",
      onboardingCelebrationTitle: "¡Todo listo! 🎉",
      onboardingCelebrationSubtitle: "Tu experiencia personalizada está lista. ¡Disfruta Plotwist!",
      onboardingGoToHome: "Ir a Home",
      onboardingLoginTitle: "Inicia sesión en Plotwist",
      onboardingLoginSubtitle: "Crea una cuenta para reseñar, seguir tu progreso y sincronizar en todos tus dispositivos.",
      onboardingNotNow: "Ahora no",
      // Genres
      genreAction: "Acción",
      genreAdventure: "Aventura",
      genreAnimation: "Animación",
      genreComedy: "Comedia",
      genreCrime: "Crimen",
      genreDocumentary: "Documental",
      genreDrama: "Drama",
      genreFantasy: "Fantasía",
      genreHistory: "Historia",
      genreHorror: "Terror",
      genreMusic: "Musical",
      genreRomance: "Romance",
      genreSciFi: "Ciencia Ficción",
      genreThriller: "Suspenso",
      genreWar: "Guerra",
      genreWestern: "Western",
      genreActionAdventure: "Acción y Aventura",
      genreSciFiFantasy: "Ciencia Ficción y Fantasía",
      genreWarPolitics: "Guerra y Política",
      genreMystery: "Misterio",
      genreFamily: "Familia",
      genreReality: "Reality",
      // Notifications
      notificationPromptTitle: "Mantente actualizado",
      notificationPromptSeries: "Recibe avisos cuando salgan nuevos episodios",
      notificationPromptWatchlist: "Recordatorio semanal de tu watchlist",
      notificationAllow: "Permitir notificaciones",
      // Stats
      stats: "Estadísticas",
      series: "Series",
      timeWatched: "Tiempo Visto",
      hour: "hora",
      hours: "horas",
      days: "días",
      topGenres: "Géneros Favoritos",
      collectionBreakdown: "Desglose de Colección",
      couldNotLoadStats: "No se pudieron cargar las estadísticas",
      tryAgain: "Intentar de nuevo",
      favoriteGenres: "Géneros Favoritos",
      content: "Contenido",
      genres: "Géneros",
      collectionStatus: "Estado de la Colección",
      itemsInCollection: "ítems en la colección",
      bestReviews: "Mejores Reseñas",
      daysOfContent: "días de contenido",
      othersGenres: "Otros",
      // Home Engagement
      forYou: "Para ti",
      basedOnYourTaste: "Porque te gusta %@",
      trendingThisWeek: "Tendencias de la semana",
      inTheaters: "En cartelera",
      topRatedMovies: "Películas mejor valoradas",
      topRatedSeries: "Series mejor valoradas",
      topRatedAnimes: "Animes mejor valorados",
      topRatedDoramas: "Doramas mejor valorados",
      featured: "Destacado",
      // Feedback
      feedbackTitle: "Ayuda y Comentarios",
      feedbackReportProblem: "Reportar un problema",
      feedbackSuggestImprovement: "Sugerir mejora",
      feedbackTypeLabel: "Tipo",
      feedbackTypeBug: "Bug / Problema",
      feedbackTypeIdea: "Idea / Sugerencia",
      feedbackDescriptionLabel: "Descripción",
      feedbackDescriptionPlaceholder: "Describe lo que pasó o lo que te gustaría ver...",
      feedbackScreenshotLabel: "Captura de pantalla",
      feedbackAddScreenshot: "Agregar captura",
      feedbackSubmit: "Enviar",
      feedbackSubmitSuccess: "¡Gracias por tu feedback!",
      feedbackHelpTitle: "Ayuda"
    ),
    .frFR: Strings(
      loginLabel: "E-mail ou nom d'utilisateur",
      loginPlaceholder: "E-mail ou nom d'utilisateur",
      passwordLabel: "Mot de passe",
      passwordPlaceholder: "*********",
      accessButton: "Accéder",
      doNotHaveAccount: "Vous n'avez pas de compte?",
      createNow: "Créez-en un maintenant",
      loginRequired: "Veuillez entrer votre e-mail ou nom d'utilisateur.",
      passwordRequired: "Veuillez entrer votre mot de passe.",
      passwordLength: "Votre mot de passe doit contenir au moins 8 caractères.",
      invalidCredentials: "Identifiants de connexion invalides.",
      continueWithGoogle: "Continuer avec Google",
      continueWithApple: "Continuer avec Apple",
      or: "ou",
      continueAsGuest: "Continuer en tant qu'invité",
      createAccount: "Créer un compte",
      welcomeSubtitle: "Suivez films, séries, animes et doramas",
      welcomeTitle: "Tout votre divertissement.\nEn un seul endroit.",
      welcomeDescription: "Suivez, découvrez et partagez films, séries, animes et doramas. Rejoignez la communauté.",
      signInToAccessProfile: "Connectez-vous pour accéder à votre profil",
      signInToAccessProfileDescription: "Créez un compte pour suivre vos films, séries et partager des avis avec la communauté.",
      startNow: "Commencez maintenant",
      startYourJourney: "Commencez votre voyage en quelques étapes.",
      emailLabel: "E-mail",
      emailPlaceholder: "email@domaine.com",
      continueButton: "Continuer",
      alreadyHaveAccount: "Vous avez déjà un compte?",
      accessNow: "Connectez-vous",
      selectUsername: "Choisissez votre nom d'utilisateur",
      selectUsernameDescription:
        "Choisissez votre nom d'utilisateur et terminez votre inscription pour commencer à utiliser la plateforme.",
      usernamePlaceholder: "jean-dupont",
      finishSignUp: "Terminer l'inscription",
      emailRequired: "Veuillez entrer votre e-mail.",
      emailInvalid: "Veuillez entrer un e-mail valide.",
      usernameRequired: "Veuillez entrer un nom d'utilisateur.",
      emailAlreadyTaken: "Cet e-mail est déjà utilisé.",
      usernameAlreadyTaken: "Ce nom d'utilisateur est déjà utilisé.",
      signUpSuccess: "Inscription réussie. Bienvenue! 🎉",
      searchPlaceholder: "Rechercher films, séries, personnes...",
      movies: "Films",
      tvSeries: "Séries TV",
      people: "Personnes",
      noResults: "Aucun résultat trouvé.",
      cancel: "Annuler",
      recentSearches: "Recherches Récentes",
      clearAll: "Effacer",
      youAreLookingFor: "Vous recherchez:",
      popularMovies: "Films populaires",
      popularTVSeries: "Séries populaires",
      popularAnimes: "Animes populaires",
      popularDoramas: "Doramas populaires",
      animes: "Animes",
      doramas: "Doramas",
      seeAllMovies: "Voir tous les films",
      seeAllTVSeries: "Voir toutes les séries",
      seeAllAnimes: "Voir tous les animes",
      seeAllDoramas: "Voir tous les doramas",
      settings: "Paramètres",
      theme: "Thème",
      themeSystem: "Système",
      themeLight: "Clair",
      themeDark: "Sombre",
      language: "Langue",
      done: "Terminé",
      signOut: "Déconnexion",
      whatDidYouThink: "Qu'en avez-vous pensé?",
      review: "Évaluer",
      reviewed: "Évalué",
      shareYourOpinion: "Partagez votre opinion ici...",
      containSpoilers: "Contient des spoilers",
      tapToReveal: "Appuyez pour révéler",
      submitReview: "Soumettre l'avis",
      editReview: "Modifier l'avis",
      reviewRequired: "Veuillez écrire votre avis.",
      reviewSuccess: "Avis soumis avec succès!",
      reviewUpdateSuccess: "Avis mis à jour avec succès!",
      reviewDeleteSuccess: "Avis supprimé avec succès!",
      tabReviews: "Avis",
      reviewSingular: "Avis",
      tabWhereToWatch: "Où Regarder",
      tabCredits: "Crédits",
      tabRecommendations: "Recommandations",
      tabSimilar: "Similaires",
      tabImages: "Images",
      tabVideos: "Vidéos",
      beFirstToReview: "Soyez le premier à donner votre avis",
      seeAll: "Voir tous les avis",
      showMore: "Voir plus",
      nowPlaying: "À l'affiche",
      popular: "Populaire",
      topRated: "Mieux notés",
      upcoming: "Prochainement",
      discover: "Découvrir",
      airingToday: "Diffusé aujourd'hui",
      onTheAir: "En cours",
      images: "Images",
      backdrops: "Fonds d'écran",
      posters: "Affiches",
      noImagesFound: "Aucune image trouvée.",
      deleteReview: "Supprimer l'avis",
      deleteReviewConfirmation: "Êtes-vous sûr de vouloir supprimer cet avis?",
      delete: "Supprimer",
      updateStatus: "Mettre à jour le statut",
      watched: "Vu",
      watching: "En cours",
      watchlist: "À voir",
      dropped: "Abandonné",
      watchLog: "Historique des visionnages",
      addRewatch: "Ajouter un revisionnage",
      firstTime: "1ère fois",
      nthTime: "%@ fois",
      markAsWatched: "Marquer comme vu",
      nextEpisode: "Épisode suivant",
      previousEpisode: "Épisode précédent",
      nextSeason: "Saison suivante",
      previousSeason: "Saison précédente",
      stream: "Streaming",
      rent: "Louer",
      buy: "Acheter",
      unavailable: "Indisponible",
      profile: "Profil",
      memberSince: "Membre depuis",
      editProfile: "Modifier",
      accountData: "Compte",
      information: "Informations",
      preferences: "Préférences",
      editPicture: "Modifier la photo",
      name: "Nom",
      username: "Nom d'utilisateur",
      region: "Région",
      streamingServices: "Services de Streaming",
      notSet: "Non défini",
      searchRegion: "Rechercher une région...",
      searchStreamingServices: "Rechercher des services...",
      selectRegionFirst: "Sélectionnez d'abord une région",
      servicesSelected: "%d sélectionnés",
      streamingServicesHint: "Affichage des services disponibles dans la région sélectionnée.",
      resultsBasedOnPreferences: "Résultats basés sur vos préférences",
      collection: "Collection",
      reviews: "Critiques",
      profileNoReviewsTitle: "Aucune critique pour l'instant",
      profileNoReviewsSubtitle: "Après avoir vu un film ou une série, partage ton avis et tes critiques apparaîtront ici.",
      soundtracks: "Bandes Sonores",
      biography: "Biographie",
      biographyPlaceholder: "Parlez-nous de vous...",
      // Home
      goodMorning: "Bonjour",
      goodAfternoon: "Bon après-midi",
      goodEvening: "Bonsoir",
      continueWatching: "Continuer à regarder",
      upNext: "À suivre",
      // Collection
      partOf: "Fait partie de",
      seeCollection: "Voir la Collection",
      // Seasons
      tabSeasons: "Saisons",
      episodes: "Épisodes",
      episodesCount: "%d épisodes",
      episodesWatchedCount: "%d sur %total vus",
      grid: "Grille",
      overview: "Aperçu",
      // Ratings
      ratingAwesome: "Incroyable",
      ratingGreat: "Génial",
      ratingGood: "Bon",
      ratingBad: "Mauvais",
      ratingTerrible: "Terrible",
      // Onboarding
      onboardingWelcomeTitle: "Organise, découvre et\nne rate plus un titre 🍿",
      onboardingWelcomeSubtitle: "Tes films, séries et animes au même endroit. Crée la watchlist parfaite pour toi.",
      onboardingGetStarted: "Commencer",
      onboardingNameTitle: "Personnalisons\nton expérience 👋",
      onboardingNameSubtitle: "Dis-nous ton prénom pour que Plotwist soit à ton image",
      onboardingNamePlaceholder: "Ton prénom",
      onboardingContentTypeTitle: "Quel type de contenu\npréfères-tu ? 🎬",
      onboardingMovies: "Films",
      onboardingSeries: "Séries",
      onboardingAnime: "Anime",
      onboardingDorama: "K-Drama",
      onboardingGenresTitle: "Choisis tes genres préférés 🎯",
      onboardingGenresSubtitle: "On utilisera tes goûts pour te recommander des titres que tu vas adorer",
      onboardingSelectGenres: "Sélectionne au moins 1",
      onboardingMoreToGo: "de plus",
      onboardingSkip: "Passer pour l'instant",
      onboardingAddTitlesTitle: "Maintenant le fun ! 🎬",
      onboardingAddTitlesSubtitle: "Ajoute 5 titres à ta watchlist",
      onboardingDiscoverTitle: "Glisse pour créer\nta collection 🍿",
      onboardingDiscoverSubtitle: "Droite pour sauver, gauche pour passer, haut si déjà vu, bas si en cours",
      onboardingWantToWatch: "Envie de voir",
      onboardingAlreadyWatched: "Déjà vu",
      onboardingWatching: "En cours",
      onboardingNotInterested: "Pas intéressé",
      onboardingNoMoreItems: "Tu as tout vu !",
      onboardingReadyToContinue: "Prêt à continuer !",
      onboardingAdded: "ajoutés",
      onboardingSearchPlaceholder: "Rechercher un titre...",
      onboardingPopularNow: "Populaire en ce moment",
      onboardingAddMore: "Ajoutez plus",
      onboardingContinueToApp: "C'est parti !",
      onboardingCelebrationTitle: "C'est prêt ! 🎉",
      onboardingCelebrationSubtitle: "Ton expérience personnalisée est prête. Profite de Plotwist !",
      onboardingGoToHome: "Aller à Home",
      onboardingLoginTitle: "Connectez-vous à Plotwist",
      onboardingLoginSubtitle: "Créez un compte pour évaluer, suivre votre progression et synchroniser sur tous vos appareils.",
      onboardingNotNow: "Pas maintenant",
      // Genres
      genreAction: "Action",
      genreAdventure: "Aventure",
      genreAnimation: "Animation",
      genreComedy: "Comédie",
      genreCrime: "Crime",
      genreDocumentary: "Documentaire",
      genreDrama: "Drame",
      genreFantasy: "Fantaisie",
      genreHistory: "Histoire",
      genreHorror: "Horreur",
      genreMusic: "Musique",
      genreRomance: "Romance",
      genreSciFi: "Science-Fiction",
      genreThriller: "Thriller",
      genreWar: "Guerre",
      genreWestern: "Western",
      genreActionAdventure: "Action et Aventure",
      genreSciFiFantasy: "Science-Fiction et Fantaisie",
      genreWarPolitics: "Guerre et Politique",
      genreMystery: "Mystère",
      genreFamily: "Famille",
      genreReality: "Télé-réalité",
      // Notifications
      notificationPromptTitle: "Restez informé",
      notificationPromptSeries: "Soyez notifié quand de nouveaux épisodes sortent",
      notificationPromptWatchlist: "Rappel hebdomadaire de votre watchlist",
      notificationAllow: "Autoriser les notifications",
      // Stats
      stats: "Statistiques",
      series: "Séries",
      timeWatched: "Temps Regardé",
      hour: "heure",
      hours: "heures",
      days: "jours",
      topGenres: "Genres Préférés",
      collectionBreakdown: "Répartition de Collection",
      couldNotLoadStats: "Impossible de charger les statistiques",
      tryAgain: "Réessayer",
      favoriteGenres: "Genres Préférés",
      content: "Contenu",
      genres: "Genres",
      collectionStatus: "Statut de la Collection",
      itemsInCollection: "éléments dans la collection",
      bestReviews: "Meilleures Critiques",
      daysOfContent: "jours de contenu",
      othersGenres: "Autres",
      // Home Engagement
      forYou: "Pour vous",
      basedOnYourTaste: "Parce que vous aimez %@",
      trendingThisWeek: "Tendances de la semaine",
      inTheaters: "Au cinéma",
      topRatedMovies: "Films les mieux notés",
      topRatedSeries: "Séries les mieux notées",
      topRatedAnimes: "Animes les mieux notés",
      topRatedDoramas: "Doramas les mieux notés",
      featured: "À la une",
      // Feedback
      feedbackTitle: "Aide et Retours",
      feedbackReportProblem: "Signaler un problème",
      feedbackSuggestImprovement: "Suggérer une amélioration",
      feedbackTypeLabel: "Type",
      feedbackTypeBug: "Bug / Problème",
      feedbackTypeIdea: "Idée / Suggestion",
      feedbackDescriptionLabel: "Description",
      feedbackDescriptionPlaceholder: "Décrivez ce qui s'est passé ou ce que vous aimeriez voir...",
      feedbackScreenshotLabel: "Capture d'écran",
      feedbackAddScreenshot: "Ajouter une capture",
      feedbackSubmit: "Envoyer",
      feedbackSubmitSuccess: "Merci pour vos retours !",
      feedbackHelpTitle: "Aide"
    ),
    .deDE: Strings(
      loginLabel: "E-Mail oder Benutzername",
      loginPlaceholder: "E-Mail oder Benutzername",
      passwordLabel: "Passwort",
      passwordPlaceholder: "*********",
      accessButton: "Zugreifen",
      doNotHaveAccount: "Haben Sie kein Konto?",
      createNow: "Jetzt erstellen",
      loginRequired: "Bitte geben Sie Ihre E-Mail-Adresse oder Ihren Benutzernamen ein.",
      passwordRequired: "Bitte geben Sie Ihr Passwort ein.",
      passwordLength: "Ihr Passwort muss mindestens 8 Zeichen lang sein.",
      invalidCredentials: "Ungültige Anmeldeinformationen.",
      continueWithGoogle: "Weiter mit Google",
      continueWithApple: "Weiter mit Apple",
      or: "oder",
      continueAsGuest: "Als Gast fortfahren",
      createAccount: "Konto erstellen",
      welcomeSubtitle: "Verfolge Filme, Serien, Animes und Doramas",
      welcomeTitle: "Deine Unterhaltung.\nAn einem Ort.",
      welcomeDescription: "Verfolge, entdecke und teile Filme, Serien, Animes und Doramas. Werde Teil der Community.",
      signInToAccessProfile: "Melden Sie sich an, um auf Ihr Profil zuzugreifen",
      signInToAccessProfileDescription: "Erstellen Sie ein Konto, um Ihre Filme und Serien zu verfolgen und Bewertungen mit der Community zu teilen.",
      startNow: "Jetzt starten",
      startYourJourney: "Beginnen Sie Ihre Reise in wenigen Schritten.",
      emailLabel: "E-Mail",
      emailPlaceholder: "email@domain.de",
      continueButton: "Weiter",
      alreadyHaveAccount: "Haben Sie bereits ein Konto?",
      accessNow: "Jetzt anmelden",
      selectUsername: "Wählen Sie Ihren Benutzernamen",
      selectUsernameDescription:
        "Wählen Sie Ihren Benutzernamen und schließen Sie Ihre Registrierung ab, um die Plattform zu nutzen.",
      usernamePlaceholder: "max-mustermann",
      finishSignUp: "Registrierung abschließen",
      emailRequired: "Bitte geben Sie Ihre E-Mail-Adresse ein.",
      emailInvalid: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
      usernameRequired: "Bitte geben Sie einen Benutzernamen ein.",
      emailAlreadyTaken: "Diese E-Mail-Adresse wird bereits verwendet.",
      usernameAlreadyTaken: "Dieser Benutzername ist bereits vergeben.",
      signUpSuccess: "Registrierung erfolgreich. Willkommen! 🎉",
      searchPlaceholder: "Filme, Serien, Personen suchen...",
      movies: "Filme",
      tvSeries: "TV-Serien",
      people: "Personen",
      noResults: "Keine Ergebnisse gefunden.",
      cancel: "Abbrechen",
      recentSearches: "Letzte Suchen",
      clearAll: "Löschen",
      youAreLookingFor: "Sie suchen nach:",
      popularMovies: "Beliebte Filme",
      popularTVSeries: "Beliebte Serien",
      popularAnimes: "Beliebte Animes",
      popularDoramas: "Beliebte Doramas",
      animes: "Animes",
      doramas: "Doramas",
      seeAllMovies: "Alle Filme anzeigen",
      seeAllTVSeries: "Alle Serien anzeigen",
      seeAllAnimes: "Alle Animes anzeigen",
      seeAllDoramas: "Alle Doramas anzeigen",
      settings: "Einstellungen",
      theme: "Design",
      themeSystem: "System",
      themeLight: "Hell",
      themeDark: "Dunkel",
      language: "Sprache",
      done: "Fertig",
      signOut: "Abmelden",
      whatDidYouThink: "Was haben Sie gedacht?",
      review: "Bewerten",
      reviewed: "Bewertet",
      shareYourOpinion: "Teilen Sie Ihre Meinung hier...",
      containSpoilers: "Enthält Spoiler",
      tapToReveal: "Zum Anzeigen tippen",
      submitReview: "Bewertung abschicken",
      editReview: "Bewertung bearbeiten",
      reviewRequired: "Bitte schreiben Sie Ihre Bewertung.",
      reviewSuccess: "Bewertung erfolgreich eingereicht!",
      reviewUpdateSuccess: "Bewertung erfolgreich aktualisiert!",
      reviewDeleteSuccess: "Bewertung erfolgreich gelöscht!",
      tabReviews: "Bewertungen",
      reviewSingular: "Bewertung",
      tabWhereToWatch: "Wo Ansehen",
      tabCredits: "Besetzung",
      tabRecommendations: "Empfehlungen",
      tabSimilar: "Ähnliche",
      tabImages: "Bilder",
      tabVideos: "Videos",
      beFirstToReview: "Sei der Erste, der seine Meinung teilt",
      seeAll: "Alle Bewertungen anzeigen",
      showMore: "Mehr anzeigen",
      nowPlaying: "Jetzt im Kino",
      popular: "Beliebt",
      topRated: "Bestbewertet",
      upcoming: "Demnächst",
      discover: "Entdecken",
      airingToday: "Heute im TV",
      onTheAir: "Auf Sendung",
      images: "Bilder",
      backdrops: "Hintergründe",
      posters: "Poster",
      noImagesFound: "Keine Bilder gefunden.",
      deleteReview: "Bewertung löschen",
      deleteReviewConfirmation: "Möchten Sie diese Bewertung wirklich löschen?",
      delete: "Löschen",
      updateStatus: "Status aktualisieren",
      watched: "Gesehen",
      watching: "Schaue ich",
      watchlist: "Watchlist",
      dropped: "Abgebrochen",
      watchLog: "Wiedergabeverlauf",
      addRewatch: "Rewatch hinzufügen",
      firstTime: "1. Mal",
      nthTime: "%@ Mal",
      markAsWatched: "Als gesehen markieren",
      nextEpisode: "Nächste Folge",
      previousEpisode: "Vorherige Folge",
      nextSeason: "Nächste Staffel",
      previousSeason: "Vorherige Staffel",
      stream: "Streaming",
      rent: "Leihen",
      buy: "Kaufen",
      unavailable: "Nicht verfügbar",
      profile: "Profil",
      memberSince: "Mitglied seit",
      editProfile: "Bearbeiten",
      accountData: "Konto",
      information: "Informationen",
      preferences: "Einstellungen",
      editPicture: "Bild bearbeiten",
      name: "Name",
      username: "Benutzername",
      region: "Region",
      streamingServices: "Streaming-Dienste",
      notSet: "Nicht festgelegt",
      searchRegion: "Region suchen...",
      searchStreamingServices: "Dienste suchen...",
      selectRegionFirst: "Wählen Sie zuerst eine Region",
      servicesSelected: "%d ausgewählt",
      streamingServicesHint: "Zeigt Dienste an, die in der ausgewählten Region verfügbar sind.",
      resultsBasedOnPreferences: "Ergebnisse basierend auf Ihren Präferenzen",
      collection: "Sammlung",
      reviews: "Bewertungen",
      profileNoReviewsTitle: "Noch keine Bewertungen",
      profileNoReviewsSubtitle: "Nachdem du einen Film oder eine Serie gesehen hast, teile deine Meinung und deine Bewertungen erscheinen hier.",
      soundtracks: "Soundtracks",
      biography: "Biografie",
      biographyPlaceholder: "Erzählen Sie uns von sich...",
      // Home
      goodMorning: "Guten Morgen",
      goodAfternoon: "Guten Tag",
      goodEvening: "Guten Abend",
      continueWatching: "Weiterschauen",
      upNext: "Als Nächstes",
      // Collection
      partOf: "Teil von",
      seeCollection: "Sammlung ansehen",
      // Seasons
      tabSeasons: "Staffeln",
      episodes: "Episoden",
      episodesCount: "%d Episoden",
      episodesWatchedCount: "%d von %total gesehen",
      grid: "Raster",
      overview: "Übersicht",
      // Ratings
      ratingAwesome: "Fantastisch",
      ratingGreat: "Toll",
      ratingGood: "Gut",
      ratingBad: "Schlecht",
      ratingTerrible: "Schrecklich",
      // Onboarding
      onboardingWelcomeTitle: "Verwalte, entdecke und\nverpasse keinen Titel 🍿",
      onboardingWelcomeSubtitle: "Deine Filme, Serien und Anime an einem Ort. Erstelle die perfekte Watchlist für dich.",
      onboardingGetStarted: "Loslegen",
      onboardingNameTitle: "Lass uns dein Erlebnis\npersonalisieren 👋",
      onboardingNameSubtitle: "Sag uns deinen Namen, damit sich Plotwist wie deins anfühlt",
      onboardingNamePlaceholder: "Dein Name",
      onboardingContentTypeTitle: "Welche Art von Inhalten\nmagst du am meisten? 🎬",
      onboardingMovies: "Filme",
      onboardingSeries: "Serien",
      onboardingAnime: "Anime",
      onboardingDorama: "K-Drama",
      onboardingGenresTitle: "Wähle deine Lieblingsgenres 🎯",
      onboardingGenresSubtitle: "Wir nutzen deinen Geschmack, um Titel zu empfehlen, die du lieben wirst",
      onboardingSelectGenres: "Mindestens 1 auswählen",
      onboardingMoreToGo: "noch übrig",
      onboardingSkip: "Erstmal überspringen",
      onboardingAddTitlesTitle: "Jetzt wird's spaßig! 🎬",
      onboardingAddTitlesSubtitle: "Füge 5 Titel zu deiner Watchlist hinzu",
      onboardingDiscoverTitle: "Wische, um deine\nSammlung aufzubauen 🍿",
      onboardingDiscoverSubtitle: "Rechts zum Speichern, links zum Überspringen, hoch wenn gesehen, runter wenn du es gerade schaust",
      onboardingWantToWatch: "Will ich sehen",
      onboardingAlreadyWatched: "Schon gesehen",
      onboardingWatching: "Schaue ich",
      onboardingNotInterested: "Kein Interesse",
      onboardingNoMoreItems: "Du hast alle gesehen!",
      onboardingReadyToContinue: "Bereit weiterzumachen!",
      onboardingAdded: "hinzugefügt",
      onboardingSearchPlaceholder: "Nach einem Titel suchen...",
      onboardingPopularNow: "Gerade beliebt",
      onboardingAddMore: "Mehr hinzufügen",
      onboardingContinueToApp: "Los geht's!",
      onboardingCelebrationTitle: "Alles bereit! 🎉",
      onboardingCelebrationSubtitle: "Dein personalisiertes Erlebnis ist bereit. Genieße Plotwist!",
      onboardingGoToHome: "Zu Home",
      onboardingLoginTitle: "Bei Plotwist anmelden",
      onboardingLoginSubtitle: "Erstelle ein Konto, um zu bewerten, deinen Fortschritt zu verfolgen und auf allen Geräten zu synchronisieren.",
      onboardingNotNow: "Jetzt nicht",
      // Genres
      genreAction: "Action",
      genreAdventure: "Abenteuer",
      genreAnimation: "Animation",
      genreComedy: "Komödie",
      genreCrime: "Krimi",
      genreDocumentary: "Dokumentation",
      genreDrama: "Drama",
      genreFantasy: "Fantasy",
      genreHistory: "Geschichte",
      genreHorror: "Horror",
      genreMusic: "Musik",
      genreRomance: "Romantik",
      genreSciFi: "Sci-Fi",
      genreThriller: "Thriller",
      genreWar: "Krieg",
      genreWestern: "Western",
      genreActionAdventure: "Action & Abenteuer",
      genreSciFiFantasy: "Sci-Fi & Fantasy",
      genreWarPolitics: "Krieg & Politik",
      genreMystery: "Mystery",
      genreFamily: "Familie",
      genreReality: "Reality",
      // Notifications
      notificationPromptTitle: "Bleib auf dem Laufenden",
      notificationPromptSeries: "Erhalte Benachrichtigungen bei neuen Episoden",
      notificationPromptWatchlist: "Wöchentliche Erinnerung an deine Watchlist",
      notificationAllow: "Benachrichtigungen erlauben",
      // Stats
      stats: "Statistiken",
      series: "Serien",
      timeWatched: "Gesehene Zeit",
      hour: "Stunde",
      hours: "Stunden",
      days: "Tage",
      topGenres: "Lieblingsgenres",
      collectionBreakdown: "Sammlungsübersicht",
      couldNotLoadStats: "Statistiken konnten nicht geladen werden",
      tryAgain: "Erneut versuchen",
      favoriteGenres: "Lieblingsgenres",
      content: "Inhalte",
      genres: "Genres",
      collectionStatus: "Sammlungsstatus",
      itemsInCollection: "Elemente in der Sammlung",
      bestReviews: "Beste Bewertungen",
      daysOfContent: "Tage an Inhalten",
      othersGenres: "Andere",
      // Home Engagement
      forYou: "Für dich",
      basedOnYourTaste: "Weil du %@ magst",
      trendingThisWeek: "Trends dieser Woche",
      inTheaters: "Im Kino",
      topRatedMovies: "Bestbewertete Filme",
      topRatedSeries: "Bestbewertete Serien",
      topRatedAnimes: "Bestbewertete Animes",
      topRatedDoramas: "Bestbewertete Doramas",
      featured: "Empfohlen",
      // Feedback
      feedbackTitle: "Hilfe & Feedback",
      feedbackReportProblem: "Problem melden",
      feedbackSuggestImprovement: "Verbesserung vorschlagen",
      feedbackTypeLabel: "Typ",
      feedbackTypeBug: "Bug / Problem",
      feedbackTypeIdea: "Idee / Vorschlag",
      feedbackDescriptionLabel: "Beschreibung",
      feedbackDescriptionPlaceholder: "Beschreiben Sie, was passiert ist oder was Sie sehen möchten...",
      feedbackScreenshotLabel: "Screenshot",
      feedbackAddScreenshot: "Screenshot hinzufügen",
      feedbackSubmit: "Absenden",
      feedbackSubmitSuccess: "Vielen Dank für Ihr Feedback!",
      feedbackHelpTitle: "Hilfe"
    ),
    .itIT: Strings(
      loginLabel: "E-mail o nome utente",
      loginPlaceholder: "E-mail o nome utente",
      passwordLabel: "Password",
      passwordPlaceholder: "*********",
      accessButton: "Accedi",
      doNotHaveAccount: "Non hai un account?",
      createNow: "Crea ora",
      loginRequired: "Inserisci il tuo indirizzo e-mail o nome utente.",
      passwordRequired: "Inserisci la tua password.",
      passwordLength: "La tua password deve contenere almeno 8 caratteri.",
      invalidCredentials: "Credenziali di accesso non valide.",
      continueWithGoogle: "Continua con Google",
      continueWithApple: "Continua con Apple",
      or: "o",
      continueAsGuest: "Continua come ospite",
      createAccount: "Crea account",
      welcomeSubtitle: "Segui film, serie, anime e dorama",
      welcomeTitle: "Tutto il tuo intrattenimento.\nIn un unico posto.",
      welcomeDescription: "Segui, scopri e condividi film, serie, anime e dorama. Unisciti alla community.",
      signInToAccessProfile: "Accedi per vedere il tuo profilo",
      signInToAccessProfileDescription: "Crea un account per seguire i tuoi film, serie e condividere recensioni con la community.",
      startNow: "Inizia ora",
      startYourJourney: "Inizia il tuo viaggio in pochi passi.",
      emailLabel: "E-mail",
      emailPlaceholder: "email@dominio.com",
      continueButton: "Continua",
      alreadyHaveAccount: "Hai già un account?",
      accessNow: "Accedi ora",
      selectUsername: "Scegli il tuo nome utente",
      selectUsernameDescription:
        "Scegli il tuo nome utente e completa la registrazione per iniziare a usare la piattaforma.",
      usernamePlaceholder: "mario-rossi",
      finishSignUp: "Completa registrazione",
      emailRequired: "Inserisci la tua e-mail.",
      emailInvalid: "Inserisci un'e-mail valida.",
      usernameRequired: "Inserisci un nome utente.",
      emailAlreadyTaken: "Questa email è già in uso.",
      usernameAlreadyTaken: "Questo nome utente è già in uso.",
      signUpSuccess: "Registrazione completata. Benvenuto! 🎉",
      searchPlaceholder: "Cerca film, serie, persone...",
      movies: "Film",
      tvSeries: "Serie TV",
      people: "Persone",
      noResults: "Nessun risultato trovato.",
      cancel: "Annulla",
      recentSearches: "Ricerche Recenti",
      clearAll: "Cancella",
      youAreLookingFor: "Stai cercando:",
      popularMovies: "Film popolari",
      popularTVSeries: "Serie popolari",
      popularAnimes: "Anime popolari",
      popularDoramas: "Dorama popolari",
      animes: "Anime",
      doramas: "Dorama",
      seeAllMovies: "Vedi tutti i film",
      seeAllTVSeries: "Vedi tutte le serie",
      seeAllAnimes: "Vedi tutti gli anime",
      seeAllDoramas: "Vedi tutti i dorama",
      settings: "Impostazioni",
      theme: "Tema",
      themeSystem: "Sistema",
      themeLight: "Chiaro",
      themeDark: "Scuro",
      language: "Lingua",
      done: "Fatto",
      signOut: "Esci",
      whatDidYouThink: "Cosa ne pensi?",
      review: "Recensire",
      reviewed: "Recensito",
      shareYourOpinion: "Condividi la tua opinione qui...",
      containSpoilers: "Contiene spoiler",
      tapToReveal: "Tocca per rivelare",
      submitReview: "Invia recensione",
      editReview: "Modifica recensione",
      reviewRequired: "Scrivi la tua recensione.",
      reviewSuccess: "Recensione inviata con successo!",
      reviewUpdateSuccess: "Recensione aggiornata con successo!",
      reviewDeleteSuccess: "Recensione eliminata con successo!",
      tabReviews: "Recensioni",
      reviewSingular: "Recensione",
      tabWhereToWatch: "Dove Guardare",
      tabCredits: "Cast",
      tabRecommendations: "Raccomandazioni",
      tabSimilar: "Simili",
      tabImages: "Immagini",
      tabVideos: "Video",
      beFirstToReview: "Sii il primo a lasciare la tua opinione",
      seeAll: "Vedi tutte le recensioni",
      showMore: "Mostra di più",
      nowPlaying: "In sala",
      popular: "Popolari",
      topRated: "Più votati",
      upcoming: "Prossimamente",
      discover: "Scopri",
      airingToday: "In onda oggi",
      onTheAir: "In onda",
      images: "Immagini",
      backdrops: "Sfondi",
      posters: "Locandine",
      noImagesFound: "Nessuna immagine trovata.",
      deleteReview: "Elimina recensione",
      deleteReviewConfirmation: "Sei sicuro di voler eliminare questa recensione?",
      delete: "Elimina",
      updateStatus: "Aggiorna stato",
      watched: "Visto",
      watching: "In visione",
      watchlist: "Da vedere",
      dropped: "Abbandonato",
      watchLog: "Cronologia visualizzazioni",
      addRewatch: "Aggiungi rewatch",
      firstTime: "1ª volta",
      nthTime: "%@ volta",
      markAsWatched: "Segna come visto",
      nextEpisode: "Prossimo episodio",
      previousEpisode: "Episodio precedente",
      nextSeason: "Prossima stagione",
      previousSeason: "Stagione precedente",
      stream: "Streaming",
      rent: "Noleggia",
      buy: "Acquista",
      unavailable: "Non disponibile",
      profile: "Profilo",
      memberSince: "Membro dal",
      editProfile: "Modifica",
      accountData: "Account",
      information: "Informazioni",
      preferences: "Preferenze",
      editPicture: "Modifica foto",
      name: "Nome",
      username: "Nome utente",
      region: "Regione",
      streamingServices: "Servizi di Streaming",
      notSet: "Non impostato",
      searchRegion: "Cerca regione...",
      searchStreamingServices: "Cerca servizi...",
      selectRegionFirst: "Seleziona prima una regione",
      servicesSelected: "%d selezionati",
      streamingServicesHint: "Mostra i servizi disponibili nella regione selezionata.",
      resultsBasedOnPreferences: "Risultati basati sulle tue preferenze",
      collection: "Collezione",
      reviews: "Recensioni",
      profileNoReviewsTitle: "Nessuna recensione ancora",
      profileNoReviewsSubtitle: "Dopo aver visto un film o una serie, condividi la tua opinione e le tue recensioni appariranno qui.",
      soundtracks: "Colonne Sonore",
      biography: "Biografia",
      biographyPlaceholder: "Raccontaci di te...",
      // Home
      goodMorning: "Buongiorno",
      goodAfternoon: "Buon pomeriggio",
      goodEvening: "Buonasera",
      continueWatching: "Continua a guardare",
      upNext: "Prossimi",
      // Collection
      partOf: "Parte di",
      seeCollection: "Vedi Collezione",
      // Seasons
      tabSeasons: "Stagioni",
      episodes: "Episodi",
      episodesCount: "%d episodi",
      episodesWatchedCount: "%d di %total visti",
      grid: "Griglia",
      overview: "Panoramica",
      // Ratings
      ratingAwesome: "Fantastico",
      ratingGreat: "Ottimo",
      ratingGood: "Buono",
      ratingBad: "Cattivo",
      ratingTerrible: "Terribile",
      // Onboarding
      onboardingWelcomeTitle: "Organizza, scopri e\nnon perderti un titolo 🍿",
      onboardingWelcomeSubtitle: "I tuoi film, serie e anime in un unico posto. Crea la watchlist perfetta per te.",
      onboardingGetStarted: "Iniziamo",
      onboardingNameTitle: "Personalizziamo\nla tua esperienza 👋",
      onboardingNameSubtitle: "Dicci il tuo nome così Plotwist sarà su misura per te",
      onboardingNamePlaceholder: "Il tuo nome",
      onboardingContentTypeTitle: "Che tipo di contenuti\nti piacciono di più? 🎬",
      onboardingMovies: "Film",
      onboardingSeries: "Serie TV",
      onboardingAnime: "Anime",
      onboardingDorama: "K-Drama",
      onboardingGenresTitle: "Scegli i tuoi generi preferiti 🎯",
      onboardingGenresSubtitle: "Useremo i tuoi gusti per consigliarti titoli che amerai",
      onboardingSelectGenres: "Seleziona almeno 1",
      onboardingMoreToGo: "ancora da scegliere",
      onboardingSkip: "Salta per ora",
      onboardingAddTitlesTitle: "Ora il bello! 🎬",
      onboardingAddTitlesSubtitle: "Aggiungi 5 titoli alla tua watchlist",
      onboardingDiscoverTitle: "Scorri per creare\nla tua collezione 🍿",
      onboardingDiscoverSubtitle: "Destra per salvare, sinistra per saltare, su se già visto, giù se lo stai guardando",
      onboardingWantToWatch: "Voglio vedere",
      onboardingAlreadyWatched: "Già visto",
      onboardingWatching: "Sto guardando",
      onboardingNotInterested: "Non mi interessa",
      onboardingNoMoreItems: "Li hai visti tutti!",
      onboardingReadyToContinue: "Pronto a continuare!",
      onboardingAdded: "aggiunti",
      onboardingSearchPlaceholder: "Cerca un titolo...",
      onboardingPopularNow: "Popolari adesso",
      onboardingAddMore: "Aggiungi altri",
      onboardingContinueToApp: "Andiamo!",
      onboardingCelebrationTitle: "Tutto pronto! 🎉",
      onboardingCelebrationSubtitle: "La tua esperienza personalizzata è pronta. Goditi Plotwist!",
      onboardingGoToHome: "Vai alla Home",
      onboardingLoginTitle: "Accedi a Plotwist",
      onboardingLoginSubtitle: "Crea un account per recensire, monitorare i tuoi progressi e sincronizzare su tutti i tuoi dispositivi.",
      onboardingNotNow: "Non ora",
      // Genres
      genreAction: "Azione",
      genreAdventure: "Avventura",
      genreAnimation: "Animazione",
      genreComedy: "Commedia",
      genreCrime: "Crime",
      genreDocumentary: "Documentario",
      genreDrama: "Dramma",
      genreFantasy: "Fantasy",
      genreHistory: "Storico",
      genreHorror: "Horror",
      genreMusic: "Musica",
      genreRomance: "Romantico",
      genreSciFi: "Fantascienza",
      genreThriller: "Thriller",
      genreWar: "Guerra",
      genreWestern: "Western",
      genreActionAdventure: "Azione e Avventura",
      genreSciFiFantasy: "Fantascienza e Fantasy",
      genreWarPolitics: "Guerra e Politica",
      genreMystery: "Mistero",
      genreFamily: "Famiglia",
      genreReality: "Reality",
      // Notifications
      notificationPromptTitle: "Resta aggiornato",
      notificationPromptSeries: "Ricevi notifiche per i nuovi episodi",
      notificationPromptWatchlist: "Promemoria settimanale della tua watchlist",
      notificationAllow: "Consenti notifiche",
      // Stats
      stats: "Statistiche",
      series: "Serie",
      timeWatched: "Tempo Guardato",
      hour: "ora",
      hours: "ore",
      days: "giorni",
      topGenres: "Generi Preferiti",
      collectionBreakdown: "Panoramica Collezione",
      couldNotLoadStats: "Impossibile caricare le statistiche",
      tryAgain: "Riprova",
      favoriteGenres: "Generi Preferiti",
      content: "Contenuti",
      genres: "Generi",
      collectionStatus: "Stato della Collezione",
      itemsInCollection: "elementi nella collezione",
      bestReviews: "Migliori Recensioni",
      daysOfContent: "giorni di contenuti",
      othersGenres: "Altri",
      // Home Engagement
      forYou: "Per te",
      basedOnYourTaste: "Perché ti piace %@",
      trendingThisWeek: "Tendenze della settimana",
      inTheaters: "Al cinema",
      topRatedMovies: "Film più votati",
      topRatedSeries: "Serie più votate",
      topRatedAnimes: "Anime più votati",
      topRatedDoramas: "Dorama più votati",
      featured: "In evidenza",
      // Feedback
      feedbackTitle: "Aiuto e Feedback",
      feedbackReportProblem: "Segnala un problema",
      feedbackSuggestImprovement: "Suggerisci un miglioramento",
      feedbackTypeLabel: "Tipo",
      feedbackTypeBug: "Bug / Problema",
      feedbackTypeIdea: "Idea / Suggerimento",
      feedbackDescriptionLabel: "Descrizione",
      feedbackDescriptionPlaceholder: "Descrivi cosa è successo o cosa vorresti vedere...",
      feedbackScreenshotLabel: "Screenshot",
      feedbackAddScreenshot: "Aggiungi screenshot",
      feedbackSubmit: "Invia",
      feedbackSubmitSuccess: "Grazie per il tuo feedback!",
      feedbackHelpTitle: "Aiuto"
    ),
    .jaJP: Strings(
      loginLabel: "メールアドレスまたはユーザー名",
      loginPlaceholder: "メールアドレスまたはユーザー名",
      passwordLabel: "パスワード",
      passwordPlaceholder: "*********",
      accessButton: "アクセス",
      doNotHaveAccount: "アカウントをお持ちではありませんか？",
      createNow: "今すぐ作成",
      loginRequired: "メールアドレスまたはユーザー名を入力してください。",
      passwordRequired: "パスワードを入力してください。",
      passwordLength: "パスワードは8文字以上でなければなりません。",
      invalidCredentials: "ログイン認証情報が無効です。",
      continueWithGoogle: "Googleで続ける",
      continueWithApple: "Appleで続ける",
      or: "または",
      continueAsGuest: "ゲストとして続ける",
      createAccount: "アカウント作成",
      welcomeSubtitle: "映画、ドラマ、アニメ、韓ドラを追跡",
      welcomeTitle: "すべてのエンタメを\nひとつの場所で。",
      welcomeDescription: "映画、ドラマ、アニメ、韓ドラを追跡、発見、共有。コミュニティに参加しよう。",
      signInToAccessProfile: "プロフィールにアクセスするにはログイン",
      signInToAccessProfileDescription: "アカウントを作成して、映画やドラマを追跡し、コミュニティとレビューを共有しましょう。",
      startNow: "今すぐ始める",
      startYourJourney: "数ステップで旅を始めましょう。",
      emailLabel: "メールアドレス",
      emailPlaceholder: "email@domain.com",
      continueButton: "続ける",
      alreadyHaveAccount: "すでにアカウントをお持ちですか？",
      accessNow: "ログイン",
      selectUsername: "ユーザー名を選択",
      selectUsernameDescription: "ユーザー名を選択し、プラットフォームの利用を開始するためにサインアップを完了してください。",
      usernamePlaceholder: "taro-yamada",
      finishSignUp: "登録を完了",
      emailRequired: "メールアドレスを入力してください。",
      emailInvalid: "有効なメールアドレスを入力してください。",
      usernameRequired: "ユーザー名を入力してください。",
      emailAlreadyTaken: "このメールアドレスは既に使用されています。",
      usernameAlreadyTaken: "このユーザー名は既に使用されています。",
      signUpSuccess: "登録が完了しました。ようこそ！🎉",
      searchPlaceholder: "映画、シリーズ、人物を検索...",
      movies: "映画",
      tvSeries: "テレビシリーズ",
      people: "人物",
      noResults: "結果が見つかりません。",
      cancel: "キャンセル",
      recentSearches: "最近の検索",
      clearAll: "クリア",
      youAreLookingFor: "検索中:",
      popularMovies: "人気の映画",
      popularTVSeries: "人気のテレビシリーズ",
      popularAnimes: "人気のアニメ",
      popularDoramas: "人気のドラマ",
      animes: "アニメ",
      doramas: "ドラマ",
      seeAllMovies: "すべての映画を見る",
      seeAllTVSeries: "すべてのシリーズを見る",
      seeAllAnimes: "すべてのアニメを見る",
      seeAllDoramas: "すべてのドラマを見る",
      settings: "設定",
      theme: "テーマ",
      themeSystem: "システム",
      themeLight: "ライト",
      themeDark: "ダーク",
      language: "言語",
      done: "完了",
      signOut: "サインアウト",
      whatDidYouThink: "どう思いましたか？",
      review: "レビュー",
      reviewed: "レビュー済み",
      shareYourOpinion: "ここにあなたの意見を共有してください...",
      containSpoilers: "ネタバレを含む",
      tapToReveal: "タップして表示",
      submitReview: "レビューを送信",
      editReview: "レビューを編集",
      reviewRequired: "レビューを書いてください。",
      reviewSuccess: "レビューが正常に送信されました！",
      reviewUpdateSuccess: "レビューが正常に更新されました！",
      reviewDeleteSuccess: "レビューが正常に削除されました！",
      tabReviews: "レビュー",
      reviewSingular: "レビュー",
      tabWhereToWatch: "視聴方法",
      tabCredits: "キャスト",
      tabRecommendations: "おすすめ",
      tabSimilar: "類似作品",
      tabImages: "画像",
      tabVideos: "動画",
      beFirstToReview: "最初にレビューを書いてください",
      seeAll: "すべてのレビューを見る",
      showMore: "もっと見る",
      nowPlaying: "上映中",
      popular: "人気",
      topRated: "高評価",
      upcoming: "近日公開",
      discover: "発見",
      airingToday: "本日放送",
      onTheAir: "放送中",
      images: "画像",
      backdrops: "背景",
      posters: "ポスター",
      noImagesFound: "画像が見つかりません。",
      deleteReview: "レビューを削除",
      deleteReviewConfirmation: "このレビューを削除してもよろしいですか？",
      delete: "削除",
      updateStatus: "ステータスを更新",
      watched: "視聴済み",
      watching: "視聴中",
      watchlist: "ウォッチリスト",
      dropped: "中断",
      watchLog: "視聴履歴",
      addRewatch: "再視聴を追加",
      firstTime: "1回目",
      nthTime: "%@回目",
      markAsWatched: "視聴済みにする",
      nextEpisode: "次のエピソード",
      previousEpisode: "前のエピソード",
      nextSeason: "次のシーズン",
      previousSeason: "前のシーズン",
      stream: "配信",
      rent: "レンタル",
      buy: "購入",
      unavailable: "利用不可",
      profile: "プロフィール",
      memberSince: "メンバー登録日",
      editProfile: "編集",
      accountData: "アカウント",
      information: "基本情報",
      preferences: "設定",
      editPicture: "写真を編集",
      name: "名前",
      username: "ユーザー名",
      region: "地域",
      streamingServices: "ストリーミング",
      notSet: "未設定",
      searchRegion: "地域を検索...",
      searchStreamingServices: "サービスを検索...",
      selectRegionFirst: "最初に地域を選択してください",
      servicesSelected: "%d 件選択",
      streamingServicesHint: "選択した地域で利用可能なサービスを表示しています。",
      resultsBasedOnPreferences: "設定に基づいた結果",
      collection: "コレクション",
      reviews: "レビュー",
      profileNoReviewsTitle: "まだレビューがありません",
      profileNoReviewsSubtitle: "映画やドラマを見た後、感想をシェアするとここにレビューが表示されます。",
      soundtracks: "サウンドトラック",
      biography: "自己紹介",
      biographyPlaceholder: "自己紹介を書いてください...",
      // Home
      goodMorning: "おはようございます",
      goodAfternoon: "こんにちは",
      goodEvening: "こんばんは",
      continueWatching: "視聴を続ける",
      upNext: "次に見る",
      // Collection
      partOf: "の一部",
      seeCollection: "コレクションを見る",
      // Seasons
      tabSeasons: "シーズン",
      episodes: "エピソード",
      episodesCount: "%d 話",
      episodesWatchedCount: "%total話中%d話視聴済み",
      grid: "グリッド",
      overview: "概要",
      // Ratings
      ratingAwesome: "最高",
      ratingGreat: "素晴らしい",
      ratingGood: "良い",
      ratingBad: "悪い",
      ratingTerrible: "最悪",
      // Onboarding
      onboardingWelcomeTitle: "整理して、発見して、\n見逃さない 🍿",
      onboardingWelcomeSubtitle: "映画、ドラマ、アニメをひとつの場所で管理。あなただけのウォッチリストを作ろう。",
      onboardingGetStarted: "はじめる",
      onboardingNameTitle: "あなたに合わせた\n体験にしよう 👋",
      onboardingNameSubtitle: "名前を教えてね。Plotwistをあなた専用にするよ",
      onboardingNamePlaceholder: "お名前",
      onboardingContentTypeTitle: "どんなコンテンツが\n一番好き？🎬",
      onboardingMovies: "映画",
      onboardingSeries: "ドラマ",
      onboardingAnime: "アニメ",
      onboardingDorama: "韓国ドラマ",
      onboardingGenresTitle: "好きなジャンルを選ぼう 🎯",
      onboardingGenresSubtitle: "あなたの好みに合わせて、きっと好きになる作品をおすすめするよ",
      onboardingSelectGenres: "1つ以上選択",
      onboardingMoreToGo: "つ残り",
      onboardingSkip: "今はスキップ",
      onboardingAddTitlesTitle: "お楽しみの時間！🎬",
      onboardingAddTitlesSubtitle: "ウォッチリストに5つ追加しよう",
      onboardingDiscoverTitle: "スワイプして\nコレクションを作ろう 🍿",
      onboardingDiscoverSubtitle: "右で保存、左でスキップ、上は視聴済み、下は視聴中",
      onboardingWantToWatch: "見たい",
      onboardingAlreadyWatched: "見た",
      onboardingWatching: "視聴中",
      onboardingNotInterested: "興味なし",
      onboardingNoMoreItems: "全部見たよ！",
      onboardingReadyToContinue: "準備OK！",
      onboardingAdded: "追加済み",
      onboardingSearchPlaceholder: "タイトルを検索...",
      onboardingPopularNow: "人気の作品",
      onboardingAddMore: "もっと追加",
      onboardingContinueToApp: "さあ始めよう！",
      onboardingCelebrationTitle: "準備完了！🎉",
      onboardingCelebrationSubtitle: "パーソナライズされた体験の準備完了。Plotwistを楽しもう！",
      onboardingGoToHome: "ホームへ",
      onboardingLoginTitle: "Plotwistにログイン",
      onboardingLoginSubtitle: "アカウントを作成して、レビュー、進捗管理、全デバイスでの同期を利用しましょう。",
      onboardingNotNow: "今はしない",
      // Genres
      genreAction: "アクション",
      genreAdventure: "アドベンチャー",
      genreAnimation: "アニメーション",
      genreComedy: "コメディ",
      genreCrime: "犯罪",
      genreDocumentary: "ドキュメンタリー",
      genreDrama: "ドラマ",
      genreFantasy: "ファンタジー",
      genreHistory: "歴史",
      genreHorror: "ホラー",
      genreMusic: "音楽",
      genreRomance: "ロマンス",
      genreSciFi: "SF",
      genreThriller: "スリラー",
      genreWar: "戦争",
      genreWestern: "西部劇",
      genreActionAdventure: "アクション＆アドベンチャー",
      genreSciFiFantasy: "SF＆ファンタジー",
      genreWarPolitics: "戦争＆政治",
      genreMystery: "ミステリー",
      genreFamily: "ファミリー",
      genreReality: "リアリティ",
      // Notifications
      notificationPromptTitle: "最新情報をチェック",
      notificationPromptSeries: "新しいエピソードの通知を受け取る",
      notificationPromptWatchlist: "ウォッチリストの週間リマインダー",
      notificationAllow: "通知を許可",
      // Stats
      stats: "統計",
      series: "シリーズ",
      timeWatched: "視聴時間",
      hour: "時間",
      hours: "時間",
      days: "日",
      topGenres: "お気に入りジャンル",
      collectionBreakdown: "コレクション内訳",
      couldNotLoadStats: "統計を読み込めませんでした",
      tryAgain: "再試行",
      favoriteGenres: "お気に入りジャンル",
      content: "コンテンツ",
      genres: "ジャンル",
      collectionStatus: "コレクションステータス",
      itemsInCollection: "アイテム",
      bestReviews: "ベストレビュー",
      daysOfContent: "日分のコンテンツ",
      othersGenres: "その他",
      // Home Engagement
      forYou: "あなたへ",
      basedOnYourTaste: "%@が好きだから",
      trendingThisWeek: "今週のトレンド",
      inTheaters: "上映中",
      topRatedMovies: "高評価の映画",
      topRatedSeries: "高評価のシリーズ",
      topRatedAnimes: "高評価のアニメ",
      topRatedDoramas: "高評価のドラマ",
      featured: "注目",
      // Feedback
      feedbackTitle: "ヘルプとフィードバック",
      feedbackReportProblem: "問題を報告",
      feedbackSuggestImprovement: "改善を提案",
      feedbackTypeLabel: "タイプ",
      feedbackTypeBug: "バグ / 問題",
      feedbackTypeIdea: "アイデア / 提案",
      feedbackDescriptionLabel: "説明",
      feedbackDescriptionPlaceholder: "何が起きたか、または何を見たいかを説明してください...",
      feedbackScreenshotLabel: "スクリーンショット",
      feedbackAddScreenshot: "スクリーンショットを追加",
      feedbackSubmit: "送信",
      feedbackSubmitSuccess: "フィードバックありがとうございます！",
      feedbackHelpTitle: "ヘルプ"
    ),
  ]
}

struct Strings {
  // Login
  let loginLabel: String
  let loginPlaceholder: String
  let passwordLabel: String
  let passwordPlaceholder: String
  let accessButton: String
  let doNotHaveAccount: String
  let createNow: String
  let loginRequired: String
  let passwordRequired: String
  let passwordLength: String
  let invalidCredentials: String
  let continueWithGoogle: String
  let continueWithApple: String
  let or: String
  let continueAsGuest: String
  let createAccount: String
  let welcomeSubtitle: String
  let welcomeTitle: String
  let welcomeDescription: String
  let signInToAccessProfile: String
  let signInToAccessProfileDescription: String
  // Sign Up
  let startNow: String
  let startYourJourney: String
  let emailLabel: String
  let emailPlaceholder: String
  let continueButton: String
  let alreadyHaveAccount: String
  let accessNow: String
  let selectUsername: String
  let selectUsernameDescription: String
  let usernamePlaceholder: String
  let finishSignUp: String
  let emailRequired: String
  let emailInvalid: String
  let usernameRequired: String
  let emailAlreadyTaken: String
  let usernameAlreadyTaken: String
  let signUpSuccess: String
  // Search
  let searchPlaceholder: String
  let movies: String
  let tvSeries: String
  let people: String
  let noResults: String
  let cancel: String
  let recentSearches: String
  let clearAll: String
  let youAreLookingFor: String
  let popularMovies: String
  let popularTVSeries: String
  let popularAnimes: String
  let popularDoramas: String
  let animes: String
  let doramas: String
  let seeAllMovies: String
  let seeAllTVSeries: String
  let seeAllAnimes: String
  let seeAllDoramas: String
  // Settings
  let settings: String
  let theme: String
  let themeSystem: String
  let themeLight: String
  let themeDark: String
  let language: String
  let done: String
  let signOut: String
  // Reviews
  let whatDidYouThink: String
  let review: String
  let reviewed: String
  let shareYourOpinion: String
  let containSpoilers: String
  let tapToReveal: String
  let submitReview: String
  let editReview: String
  let reviewRequired: String
  let reviewSuccess: String
  let reviewUpdateSuccess: String
  let reviewDeleteSuccess: String
  // Tabs
  let tabReviews: String
  let reviewSingular: String
  let tabWhereToWatch: String
  let tabCredits: String
  let tabRecommendations: String
  let tabSimilar: String
  let tabImages: String
  let tabVideos: String
  // Review List
  let beFirstToReview: String
  let seeAll: String
  let showMore: String
  // Movie Categories
  let nowPlaying: String
  let popular: String
  let topRated: String
  let upcoming: String
  let discover: String
  // TV Series Categories
  let airingToday: String
  let onTheAir: String
  // Images
  let images: String
  let backdrops: String
  let posters: String
  let noImagesFound: String
  // Delete Review
  let deleteReview: String
  let deleteReviewConfirmation: String
  let delete: String
  // Status
  let updateStatus: String
  let watched: String
  let watching: String
  let watchlist: String
  let dropped: String
  // Rewatch
  let watchLog: String
  let addRewatch: String
  let firstTime: String
  let nthTime: String
  // Episode Progress
  let markAsWatched: String
  let nextEpisode: String
  let previousEpisode: String
  let nextSeason: String
  let previousSeason: String
  // Where to Watch
  let stream: String
  let rent: String
  let buy: String
  let unavailable: String
  // Profile
  let profile: String
  let memberSince: String
  let editProfile: String
  let accountData: String
  let information: String
  let preferences: String
  let editPicture: String
  let name: String
  let username: String
  let region: String
  let streamingServices: String
  let notSet: String
  let searchRegion: String
  let searchStreamingServices: String
  let selectRegionFirst: String
  let servicesSelected: String
  let streamingServicesHint: String
  let resultsBasedOnPreferences: String
  // Profile Tabs
  let collection: String
  let reviews: String
  let profileNoReviewsTitle: String
  let profileNoReviewsSubtitle: String
  // Tab Bar
  let soundtracks: String
  // Biography
  let biography: String
  let biographyPlaceholder: String
  // Home
  let goodMorning: String
  let goodAfternoon: String
  let goodEvening: String
  let continueWatching: String
  let upNext: String
  // Collection
  let partOf: String
  let seeCollection: String
  // Seasons
  let tabSeasons: String
  let episodes: String
  let episodesCount: String
  let episodesWatchedCount: String
  let grid: String
  let overview: String
  // Ratings
  let ratingAwesome: String
  let ratingGreat: String
  let ratingGood: String
  let ratingBad: String
  let ratingTerrible: String
  // Onboarding
  let onboardingWelcomeTitle: String
  let onboardingWelcomeSubtitle: String
  let onboardingGetStarted: String
  let onboardingNameTitle: String
  let onboardingNameSubtitle: String
  let onboardingNamePlaceholder: String
  let onboardingContentTypeTitle: String
  let onboardingMovies: String
  let onboardingSeries: String
  let onboardingAnime: String
  let onboardingDorama: String
  let onboardingGenresTitle: String
  let onboardingGenresSubtitle: String
  let onboardingSelectGenres: String
  let onboardingMoreToGo: String
  let onboardingSkip: String
  let onboardingAddTitlesTitle: String
  let onboardingAddTitlesSubtitle: String
  let onboardingDiscoverTitle: String
  let onboardingDiscoverSubtitle: String
  let onboardingWantToWatch: String
  let onboardingAlreadyWatched: String
  let onboardingWatching: String
  let onboardingNotInterested: String
  let onboardingNoMoreItems: String
  let onboardingReadyToContinue: String
  let onboardingAdded: String
  let onboardingSearchPlaceholder: String
  let onboardingPopularNow: String
  let onboardingAddMore: String
  let onboardingContinueToApp: String
  let onboardingCelebrationTitle: String
  let onboardingCelebrationSubtitle: String
  let onboardingGoToHome: String
  let onboardingLoginTitle: String
  let onboardingLoginSubtitle: String
  let onboardingNotNow: String
  // Genres
  let genreAction: String
  let genreAdventure: String
  let genreAnimation: String
  let genreComedy: String
  let genreCrime: String
  let genreDocumentary: String
  let genreDrama: String
  let genreFantasy: String
  let genreHistory: String
  let genreHorror: String
  let genreMusic: String
  let genreRomance: String
  let genreSciFi: String
  let genreThriller: String
  let genreWar: String
  let genreWestern: String
  let genreActionAdventure: String
  let genreSciFiFantasy: String
  let genreWarPolitics: String
  let genreMystery: String
  let genreFamily: String
  let genreReality: String
  // Notifications
  let notificationPromptTitle: String
  let notificationPromptSeries: String
  let notificationPromptWatchlist: String
  let notificationAllow: String
  // Stats
  let stats: String
  let series: String
  let timeWatched: String
  let hour: String
  let hours: String
  let days: String
  let topGenres: String
  let collectionBreakdown: String
  let couldNotLoadStats: String
  let tryAgain: String
  let favoriteGenres: String
  let content: String
  let genres: String
  let collectionStatus: String
  let itemsInCollection: String
  let bestReviews: String
  let daysOfContent: String
  let othersGenres: String
  // Home Engagement
  let forYou: String
  let basedOnYourTaste: String
  let trendingThisWeek: String
  let inTheaters: String
  let topRatedMovies: String
  let topRatedSeries: String
  let topRatedAnimes: String
  let topRatedDoramas: String
  let featured: String
  // Feedback
  let feedbackTitle: String
  let feedbackReportProblem: String
  let feedbackSuggestImprovement: String
  let feedbackTypeLabel: String
  let feedbackTypeBug: String
  let feedbackTypeIdea: String
  let feedbackDescriptionLabel: String
  let feedbackDescriptionPlaceholder: String
  let feedbackScreenshotLabel: String
  let feedbackAddScreenshot: String
  let feedbackSubmit: String
  let feedbackSubmitSuccess: String
  let feedbackHelpTitle: String
}
