import type { Metadata } from 'next'
import { Space_Grotesk as SpaceGrotesk } from 'next/font/google'

import { ThemeProvider } from '@/components/theme-provider'
import { Toaster } from '@/components/ui/sonner'

import '../globals.css'
import { AppContextProvider } from '@/context/app/app'

const spaceGrotesk = SpaceGrotesk({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'TMDB',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: string }
}) {
  return (
    <html lang={params.lang} className={spaceGrotesk.className}>
      <body className="bg-background antialiased">
        <AppContextProvider>
          <ThemeProvider>{children}</ThemeProvider>
          <Toaster />
        </AppContextProvider>
      </body>
    </html>
  )
}
