import type { Metadata } from 'next'
import { Space_Grotesk as SpaceGrotesk } from 'next/font/google'

import { ThemeProvider } from '@/components/theme-provider'
import { Toaster } from '@/components/ui/sonner'

import '../globals.css'
import { AppContextProvider } from '@/context/app/app'
import { LanguageContextProvider } from '@/context/language'
import { Language } from '@/types/languages'
import { getDictionary } from '@/utils/dictionaries'

const spaceGrotesk = SpaceGrotesk({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'TMDB',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: Language }
}) {
  const dictionary = await getDictionary(params.lang)

  return (
    <html lang={params.lang} className={spaceGrotesk.className}>
      <body className="bg-background antialiased">
        <AppContextProvider>
          <LanguageContextProvider
            language={params.lang}
            dictionary={dictionary}
          >
            <ThemeProvider>{children}</ThemeProvider>
            <Toaster />
          </LanguageContextProvider>
        </AppContextProvider>
      </body>
    </html>
  )
}
