/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Plotwist
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  PostLogin200,
  PostLogin400,
  PostLoginBody
} from './endpoints.schemas';

import { axiosInstance } from '../services/axios-instance';





/**
 * User login with login and password
 */
export type postLoginResponse200 = {
  data: PostLogin200
  status: 200
}

export type postLoginResponse400 = {
  data: PostLogin400
  status: 400
}
    
export type postLoginResponseSuccess = (postLoginResponse200) & {
  headers: Headers;
};
export type postLoginResponseError = (postLoginResponse400) & {
  headers: Headers;
};

export type postLoginResponse = (postLoginResponseSuccess | postLoginResponseError)

export const getPostLoginUrl = () => {


  

  return `/login`
}

export const postLogin = async (postLoginBody: PostLoginBody, options?: RequestInit): Promise<postLoginResponse> => {
  
  return axiosInstance<postLoginResponse>(getPostLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postLoginBody,)
  }
);}




export const getPostLoginMutationOptions = <TError = PostLogin400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLogin>>, TError,{data: PostLoginBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postLogin>>, TError,{data: PostLoginBody}, TContext> => {

const mutationKey = ['postLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLogin>>, {data: PostLoginBody}> = (props) => {
          const {data} = props ?? {};

          return  postLogin(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postLogin>>>
    export type PostLoginMutationBody = PostLoginBody
    export type PostLoginMutationError = PostLogin400

    export const usePostLogin = <TError = PostLogin400,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLogin>>, TError,{data: PostLoginBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLogin>>,
        TError,
        {data: PostLoginBody},
        TContext
      > => {
      return useMutation(getPostLoginMutationOptions(options), queryClient);
    }
    