/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Event booster
 * OpenAPI spec version: 0.1.0
 */
import { axiosInstance } from '../services/axios-instance'

export const getHealthcheck = () => {
  return axiosInstance<void>({ url: `/healthcheck`, method: 'GET' })
}
