/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Plotwist
 * OpenAPI spec version: 0.1.0
 */
export type PostUsersCreateBody = {
  /** @minLength 3 */
  username: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** @minLength 8 */
  password: string;
};

export type PostUsersCreate201UserSubscriptionType = typeof PostUsersCreate201UserSubscriptionType[keyof typeof PostUsersCreate201UserSubscriptionType];


export const PostUsersCreate201UserSubscriptionType = {
  MEMBER: 'MEMBER',
  PRO: 'PRO',
} as const;

export type PostUsersCreate201User = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id?: string;
  username: string;
  email: string;
  createdAt?: string;
  /** @nullable */
  bannerUrl?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  /** @nullable */
  isLegacy?: boolean | null;
  /** @nullable */
  biography?: string | null;
  subscriptionType: PostUsersCreate201UserSubscriptionType;
};

/**
 * User created.
 */
export type PostUsersCreate201 = {
  user: PostUsersCreate201User;
};

/**
 * Email or username is already registered.
 */
export type PostUsersCreate409 = {
  message: string;
};

/**
 * Fail to hash password.
 */
export type PostUsersCreate500 = {
  message: string;
};

export type GetUsersAvailableUsernameParams = {
/**
 * @minLength 1
 */
username: string;
};

export type GetUsersAvailableUsername200 = {
  available: boolean;
};

/**
 * Username is already registered.
 */
export type GetUsersAvailableUsername409 = {
  message: string;
};

export type GetUsersAvailableEmailParams = {
/**
 * @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$
 */
email: string;
};

export type GetUsersAvailableEmail200 = {
  available: boolean;
};

/**
 * Email is already registered.
 */
export type GetUsersAvailableEmail409 = {
  message: string;
};

export type GetUsersUsername200UserSubscriptionType = typeof GetUsersUsername200UserSubscriptionType[keyof typeof GetUsersUsername200UserSubscriptionType];


export const GetUsersUsername200UserSubscriptionType = {
  MEMBER: 'MEMBER',
  PRO: 'PRO',
} as const;

export type GetUsersUsername200User = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  username: string;
  email: string;
  createdAt: string;
  /** @nullable */
  bannerUrl: string | null;
  /** @nullable */
  avatarUrl: string | null;
  /** @nullable */
  isLegacy: boolean | null;
  /** @nullable */
  biography: string | null;
  subscriptionType: GetUsersUsername200UserSubscriptionType;
};

export type GetUsersUsername200 = {
  user: GetUsersUsername200User;
};

export type GetUserById200UserSubscriptionType = typeof GetUserById200UserSubscriptionType[keyof typeof GetUserById200UserSubscriptionType];


export const GetUserById200UserSubscriptionType = {
  MEMBER: 'MEMBER',
  PRO: 'PRO',
} as const;

export type GetUserById200User = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  username: string;
  email: string;
  createdAt: string;
  /** @nullable */
  bannerUrl: string | null;
  /** @nullable */
  avatarUrl: string | null;
  /** @nullable */
  isLegacy: boolean | null;
  /** @nullable */
  biography: string | null;
  subscriptionType: GetUserById200UserSubscriptionType;
};

export type GetUserById200 = {
  user: GetUserById200User;
};

export type GetMe200UserSubscriptionType = typeof GetMe200UserSubscriptionType[keyof typeof GetMe200UserSubscriptionType];


export const GetMe200UserSubscriptionType = {
  MEMBER: 'MEMBER',
  PRO: 'PRO',
} as const;

export type GetMe200User = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  username: string;
  email: string;
  createdAt: string;
  /** @nullable */
  bannerUrl: string | null;
  /** @nullable */
  avatarUrl: string | null;
  /** @nullable */
  isLegacy: boolean | null;
  /** @nullable */
  biography: string | null;
  subscriptionType: GetMe200UserSubscriptionType;
};

export type GetMe200 = {
  user: GetMe200User;
};

export type PatchUserBody = {
  bannerUrl?: string;
  avatarUrl?: string;
  username?: string;
  biography?: string;
};

export type PatchUser200User = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  username: string;
  email: string;
  createdAt: string;
  /** @nullable */
  bannerUrl: string | null;
  /** @nullable */
  avatarUrl: string | null;
  /** @nullable */
  isLegacy: boolean | null;
  /** @nullable */
  biography: string | null;
};

export type PatchUser200 = {
  user: PatchUser200User;
};

export type PatchUserPasswordBody = {
  password: string;
  token: string;
};

export type PatchUserPassword200Status = typeof PatchUserPassword200Status[keyof typeof PatchUserPassword200Status];


export const PatchUserPassword200Status = {
  password_set: 'password_set',
} as const;

export type PatchUserPassword200 = {
  status: PatchUserPassword200Status;
};

export type UpdateUserPreferencesBody = {
  watchProvidersIds: number[];
  watchRegion: string;
};

export type UpdateUserPreferences200UserPreferences = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  /** @nullable */
  watchProvidersIds: number[] | null;
  /** @nullable */
  watchRegion: string | null;
};

export type UpdateUserPreferences200 = {
  userPreferences: UpdateUserPreferences200UserPreferences;
};

/**
 * @nullable
 */
export type GetUserPreferences200UserPreferences = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  /** @nullable */
  watchProvidersIds: number[] | null;
  /** @nullable */
  watchRegion: string | null;
} | null;

export type GetUserPreferences200 = {
  /** @nullable */
  userPreferences: GetUserPreferences200UserPreferences;
};

export type GetUsersSearchParams = {
username: string;
};

export type GetUsersSearch200UsersItem = {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
  isFollowed: boolean;
};

export type GetUsersSearch200 = {
  users: GetUsersSearch200UsersItem[];
};

export type PostListBodyVisibility = typeof PostListBodyVisibility[keyof typeof PostListBodyVisibility];


export const PostListBodyVisibility = {
  PUBLIC: 'PUBLIC',
  NETWORK: 'NETWORK',
  PRIVATE: 'PRIVATE',
} as const;

export type PostListBody = {
  title: string;
  /** @nullable */
  description?: string | null;
  visibility: PostListBodyVisibility;
};

export type PostList201ListVisibility = typeof PostList201ListVisibility[keyof typeof PostList201ListVisibility];


export const PostList201ListVisibility = {
  PUBLIC: 'PUBLIC',
  NETWORK: 'NETWORK',
  PRIVATE: 'PRIVATE',
} as const;

export type PostList201List = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  title: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  /** @nullable */
  description: string | null;
  /** @nullable */
  bannerUrl: string | null;
  visibility: PostList201ListVisibility;
  createdAt: string;
};

/**
 * List created.
 */
export type PostList201 = {
  list: PostList201List;
};

/**
 * User not found
 */
export type PostList404 = {
  message: string;
};

export type GetListsParams = {
visibility?: GetListsVisibility;
userId?: string;
limit?: number;
hasBanner?: boolean;
};

export type GetListsVisibility = typeof GetListsVisibility[keyof typeof GetListsVisibility];


export const GetListsVisibility = {
  PUBLIC: 'PUBLIC',
  NETWORK: 'NETWORK',
  PRIVATE: 'PRIVATE',
} as const;

export type GetLists200ListsItemVisibility = typeof GetLists200ListsItemVisibility[keyof typeof GetLists200ListsItemVisibility];


export const GetLists200ListsItemVisibility = {
  PUBLIC: 'PUBLIC',
  NETWORK: 'NETWORK',
  PRIVATE: 'PRIVATE',
} as const;

export type GetLists200ListsItemItemsItemMediaType = typeof GetLists200ListsItemItemsItemMediaType[keyof typeof GetLists200ListsItemItemsItemMediaType];


export const GetLists200ListsItemItemsItemMediaType = {
  TV_SHOW: 'TV_SHOW',
  MOVIE: 'MOVIE',
} as const;

export type GetLists200ListsItemItemsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  mediaType: GetLists200ListsItemItemsItemMediaType;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  tmdbId: number;
};

export type GetLists200ListsItemUser = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};

export type GetLists200ListsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  title: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  /** @nullable */
  description: string | null;
  /** @nullable */
  bannerUrl: string | null;
  visibility: GetLists200ListsItemVisibility;
  createdAt: string;
  likeCount: number;
  hasLiked: boolean;
  items: GetLists200ListsItemItemsItem[];
  user: GetLists200ListsItemUser;
};

export type GetLists200 = {
  lists: GetLists200ListsItem[];
};

export type GetLists404 = {
  message: string;
};

/**
 * @nullable
 */
export type DeleteListId204 = typeof DeleteListId204[keyof typeof DeleteListId204] | null;


export const DeleteListId204 = {
} as const;

/**
 * List not found.
 */
export type DeleteListId404 = {
  message: string;
};

export type PutListIdBodyVisibility = typeof PutListIdBodyVisibility[keyof typeof PutListIdBodyVisibility];


export const PutListIdBodyVisibility = {
  PUBLIC: 'PUBLIC',
  NETWORK: 'NETWORK',
  PRIVATE: 'PRIVATE',
} as const;

export type PutListIdBody = {
  title: string;
  /** @nullable */
  description?: string | null;
  visibility: PutListIdBodyVisibility;
};

export type PutListId200ListVisibility = typeof PutListId200ListVisibility[keyof typeof PutListId200ListVisibility];


export const PutListId200ListVisibility = {
  PUBLIC: 'PUBLIC',
  NETWORK: 'NETWORK',
  PRIVATE: 'PRIVATE',
} as const;

export type PutListId200List = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  title: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  /** @nullable */
  description: string | null;
  /** @nullable */
  bannerUrl: string | null;
  visibility: PutListId200ListVisibility;
  createdAt: string;
};

export type PutListId200 = {
  list: PutListId200List;
};

/**
 * List not found.
 */
export type PutListId404 = {
  message: string;
};

export type GetListById200ListVisibility = typeof GetListById200ListVisibility[keyof typeof GetListById200ListVisibility];


export const GetListById200ListVisibility = {
  PUBLIC: 'PUBLIC',
  NETWORK: 'NETWORK',
  PRIVATE: 'PRIVATE',
} as const;

/**
 * @nullable
 */
export type GetListById200ListUserLike = {
  id: string;
  entityId: string;
  userId: string;
  createdAt: string;
} | null;

export type GetListById200List = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  title: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  /** @nullable */
  description: string | null;
  /** @nullable */
  bannerUrl: string | null;
  visibility: GetListById200ListVisibility;
  createdAt: string;
  likeCount: number;
  /** @nullable */
  userLike: GetListById200ListUserLike;
};

export type GetListById200 = {
  list: GetListById200List;
};

/**
 * List not found.
 */
export type GetListById404 = {
  message: string;
};

export type PatchListBannerBody = {
  bannerUrl: string;
  listId: string;
};

export type PatchListBanner200ListVisibility = typeof PatchListBanner200ListVisibility[keyof typeof PatchListBanner200ListVisibility];


export const PatchListBanner200ListVisibility = {
  PUBLIC: 'PUBLIC',
  NETWORK: 'NETWORK',
  PRIVATE: 'PRIVATE',
} as const;

export type PatchListBanner200List = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  title: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  /** @nullable */
  description: string | null;
  /** @nullable */
  bannerUrl: string | null;
  visibility: PatchListBanner200ListVisibility;
  createdAt: string;
};

export type PatchListBanner200 = {
  list: PatchListBanner200List;
};

export type GetListProgress200 = {
  total: number;
  completed: number;
  percentage: number;
};

export type PostLoginBody = {
  /** @minLength 3 */
  login: string;
  /** @minLength 8 */
  password: string;
  url?: string;
};

export type PostLogin200 = {
  token?: string;
  status?: string;
};

/**
 * Invalid login or password.
 */
export type PostLogin400 = {
  message: string;
};

export type PostReviewBodyMediaType = typeof PostReviewBodyMediaType[keyof typeof PostReviewBodyMediaType];


export const PostReviewBodyMediaType = {
  TV_SHOW: 'TV_SHOW',
  MOVIE: 'MOVIE',
} as const;

/**
 * @nullable
 */
export type PostReviewBodyLanguage = typeof PostReviewBodyLanguage[keyof typeof PostReviewBodyLanguage] | null;


export const PostReviewBodyLanguage = {
  'en-US': 'en-US',
  'es-ES': 'es-ES',
  'fr-FR': 'fr-FR',
  'it-IT': 'it-IT',
  'de-DE': 'de-DE',
  'pt-BR': 'pt-BR',
  'ja-JP': 'ja-JP',
} as const;

export type PostReviewBody = {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  tmdbId: number;
  mediaType: PostReviewBodyMediaType;
  review: string;
  /**
   * @minimum -8388608
   * @maximum 8388607
   */
  rating: number;
  hasSpoilers?: boolean;
  /** @nullable */
  language?: PostReviewBodyLanguage;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  seasonNumber?: number | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  episodeNumber?: number | null;
};

export type PostReview201ReviewMediaType = typeof PostReview201ReviewMediaType[keyof typeof PostReview201ReviewMediaType];


export const PostReview201ReviewMediaType = {
  TV_SHOW: 'TV_SHOW',
  MOVIE: 'MOVIE',
} as const;

/**
 * @nullable
 */
export type PostReview201ReviewLanguage = typeof PostReview201ReviewLanguage[keyof typeof PostReview201ReviewLanguage] | null;


export const PostReview201ReviewLanguage = {
  'en-US': 'en-US',
  'es-ES': 'es-ES',
  'fr-FR': 'fr-FR',
  'it-IT': 'it-IT',
  'de-DE': 'de-DE',
  'pt-BR': 'pt-BR',
  'ja-JP': 'ja-JP',
} as const;

export type PostReview201Review = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id?: string;
  createdAt?: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  tmdbId: number;
  mediaType: PostReview201ReviewMediaType;
  review: string;
  /**
   * @minimum -8388608
   * @maximum 8388607
   */
  rating: number;
  hasSpoilers?: boolean;
  /** @nullable */
  language?: PostReview201ReviewLanguage;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  seasonNumber?: number | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  episodeNumber?: number | null;
};

/**
 * Review created.
 */
export type PostReview201 = {
  review: PostReview201Review;
};

/**
 * User not found
 */
export type PostReview404 = {
  message: string;
};

export type GetReviewParams = {
mediaType: GetReviewMediaType;
tmdbId: string;
seasonNumber?: string;
episodeNumber?: string;
};

export type GetReviewMediaType = typeof GetReviewMediaType[keyof typeof GetReviewMediaType];


export const GetReviewMediaType = {
  TV_SHOW: 'TV_SHOW',
  MOVIE: 'MOVIE',
} as const;

/**
 * @nullable
 */
export type GetReview200Review = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  createdAt: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  tmdbId: number;
  mediaType: 'TV_SHOW' | 'MOVIE';
  review: string;
  /**
   * @minimum -8388608
   * @maximum 8388607
   */
  rating: number;
  hasSpoilers: boolean;
  /** @nullable */
  language: 'en-US' | 'es-ES' | 'fr-FR' | 'it-IT' | 'de-DE' | 'pt-BR' | 'ja-JP' | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  seasonNumber: number | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  episodeNumber: number | null;
} | null;

export type GetReview200 = {
  /** @nullable */
  review: GetReview200Review;
};

export type GetReviewsParams = {
language?: GetReviewsLanguage;
tmdbId?: string;
userId?: string;
limit?: string;
page?: string;
mediaType?: GetReviewsMediaType;
orderBy?: GetReviewsOrderBy;
interval?: GetReviewsInterval;
seasonNumber?: string;
episodeNumber?: string;
};

export type GetReviewsLanguage = typeof GetReviewsLanguage[keyof typeof GetReviewsLanguage];


export const GetReviewsLanguage = {
  'en-US': 'en-US',
  'es-ES': 'es-ES',
  'fr-FR': 'fr-FR',
  'de-DE': 'de-DE',
  'it-IT': 'it-IT',
  'pt-BR': 'pt-BR',
  'ja-JP': 'ja-JP',
} as const;

export type GetReviewsMediaType = typeof GetReviewsMediaType[keyof typeof GetReviewsMediaType];


export const GetReviewsMediaType = {
  MOVIE: 'MOVIE',
  TV_SHOW: 'TV_SHOW',
} as const;

export type GetReviewsOrderBy = typeof GetReviewsOrderBy[keyof typeof GetReviewsOrderBy];


export const GetReviewsOrderBy = {
  likeCount: 'likeCount',
  createdAt: 'createdAt',
} as const;

export type GetReviewsInterval = typeof GetReviewsInterval[keyof typeof GetReviewsInterval];


export const GetReviewsInterval = {
  TODAY: 'TODAY',
  THIS_WEEK: 'THIS_WEEK',
  THIS_MONTH: 'THIS_MONTH',
  ALL_TIME: 'ALL_TIME',
} as const;

export type GetReviews200ItemMediaType = typeof GetReviews200ItemMediaType[keyof typeof GetReviews200ItemMediaType];


export const GetReviews200ItemMediaType = {
  TV_SHOW: 'TV_SHOW',
  MOVIE: 'MOVIE',
} as const;

/**
 * @nullable
 */
export type GetReviews200ItemLanguage = typeof GetReviews200ItemLanguage[keyof typeof GetReviews200ItemLanguage] | null;


export const GetReviews200ItemLanguage = {
  'en-US': 'en-US',
  'es-ES': 'es-ES',
  'fr-FR': 'fr-FR',
  'it-IT': 'it-IT',
  'de-DE': 'de-DE',
  'pt-BR': 'pt-BR',
  'ja-JP': 'ja-JP',
} as const;

export type GetReviews200ItemUser = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};

/**
 * @nullable
 */
export type GetReviews200ItemUserLike = {
  id: string;
  entityId: string;
  userId: string;
  createdAt: string;
} | null;

export type GetReviews200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  createdAt: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  tmdbId: number;
  mediaType: GetReviews200ItemMediaType;
  review: string;
  /**
   * @minimum -8388608
   * @maximum 8388607
   */
  rating: number;
  hasSpoilers: boolean;
  /** @nullable */
  language: GetReviews200ItemLanguage;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  seasonNumber: number | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  episodeNumber: number | null;
  user: GetReviews200ItemUser;
  likeCount: number;
  replyCount: number;
  /** @nullable */
  userLike: GetReviews200ItemUserLike;
};

export type PutReviewByIdBody = {
  /**
   * @minimum -8388608
   * @maximum 8388607
   */
  rating: number;
  review: string;
  hasSpoilers?: boolean;
};

export type PutReviewById200MediaType = typeof PutReviewById200MediaType[keyof typeof PutReviewById200MediaType];


export const PutReviewById200MediaType = {
  TV_SHOW: 'TV_SHOW',
  MOVIE: 'MOVIE',
} as const;

/**
 * @nullable
 */
export type PutReviewById200Language = typeof PutReviewById200Language[keyof typeof PutReviewById200Language] | null;


export const PutReviewById200Language = {
  'en-US': 'en-US',
  'es-ES': 'es-ES',
  'fr-FR': 'fr-FR',
  'it-IT': 'it-IT',
  'de-DE': 'de-DE',
  'pt-BR': 'pt-BR',
  'ja-JP': 'ja-JP',
} as const;

export type PutReviewById200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  createdAt: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  tmdbId: number;
  mediaType: PutReviewById200MediaType;
  review: string;
  /**
   * @minimum -8388608
   * @maximum 8388607
   */
  rating: number;
  hasSpoilers: boolean;
  /** @nullable */
  language: PutReviewById200Language;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  seasonNumber: number | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  episodeNumber: number | null;
};

export type GetDetailedReviewsParams = {
language?: GetDetailedReviewsLanguage;
tmdbId?: string;
userId?: string;
limit?: string;
page?: string;
mediaType?: GetDetailedReviewsMediaType;
orderBy?: GetDetailedReviewsOrderBy;
interval?: GetDetailedReviewsInterval;
seasonNumber?: string;
episodeNumber?: string;
};

export type GetDetailedReviewsLanguage = typeof GetDetailedReviewsLanguage[keyof typeof GetDetailedReviewsLanguage];


export const GetDetailedReviewsLanguage = {
  'en-US': 'en-US',
  'es-ES': 'es-ES',
  'fr-FR': 'fr-FR',
  'de-DE': 'de-DE',
  'it-IT': 'it-IT',
  'pt-BR': 'pt-BR',
  'ja-JP': 'ja-JP',
} as const;

export type GetDetailedReviewsMediaType = typeof GetDetailedReviewsMediaType[keyof typeof GetDetailedReviewsMediaType];


export const GetDetailedReviewsMediaType = {
  MOVIE: 'MOVIE',
  TV_SHOW: 'TV_SHOW',
} as const;

export type GetDetailedReviewsOrderBy = typeof GetDetailedReviewsOrderBy[keyof typeof GetDetailedReviewsOrderBy];


export const GetDetailedReviewsOrderBy = {
  likeCount: 'likeCount',
  createdAt: 'createdAt',
} as const;

export type GetDetailedReviewsInterval = typeof GetDetailedReviewsInterval[keyof typeof GetDetailedReviewsInterval];


export const GetDetailedReviewsInterval = {
  TODAY: 'TODAY',
  THIS_WEEK: 'THIS_WEEK',
  THIS_MONTH: 'THIS_MONTH',
  ALL_TIME: 'ALL_TIME',
} as const;

export type GetDetailedReviews200ReviewsItemMediaType = typeof GetDetailedReviews200ReviewsItemMediaType[keyof typeof GetDetailedReviews200ReviewsItemMediaType];


export const GetDetailedReviews200ReviewsItemMediaType = {
  TV_SHOW: 'TV_SHOW',
  MOVIE: 'MOVIE',
} as const;

/**
 * @nullable
 */
export type GetDetailedReviews200ReviewsItemLanguage = typeof GetDetailedReviews200ReviewsItemLanguage[keyof typeof GetDetailedReviews200ReviewsItemLanguage] | null;


export const GetDetailedReviews200ReviewsItemLanguage = {
  'en-US': 'en-US',
  'es-ES': 'es-ES',
  'fr-FR': 'fr-FR',
  'it-IT': 'it-IT',
  'de-DE': 'de-DE',
  'pt-BR': 'pt-BR',
  'ja-JP': 'ja-JP',
} as const;

export type GetDetailedReviews200ReviewsItemUser = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};

/**
 * @nullable
 */
export type GetDetailedReviews200ReviewsItemUserLike = {
  id: string;
  entityId: string;
  userId: string;
  createdAt: string;
} | null;

export type GetDetailedReviews200ReviewsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  createdAt: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  tmdbId: number;
  mediaType: GetDetailedReviews200ReviewsItemMediaType;
  review: string;
  /**
   * @minimum -8388608
   * @maximum 8388607
   */
  rating: number;
  hasSpoilers: boolean;
  /** @nullable */
  language: GetDetailedReviews200ReviewsItemLanguage;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  seasonNumber: number | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  episodeNumber: number | null;
  user: GetDetailedReviews200ReviewsItemUser;
  likeCount: number;
  replyCount: number;
  /** @nullable */
  userLike: GetDetailedReviews200ReviewsItemUserLike;
  title: string;
  /** @nullable */
  posterPath: string | null;
  /** @nullable */
  backdropPath: string | null;
};

export type GetDetailedReviews200Pagination = {
  page: number;
  limit: number;
  hasMore: boolean;
};

export type GetDetailedReviews200 = {
  reviews: GetDetailedReviews200ReviewsItem[];
  pagination: GetDetailedReviews200Pagination;
};

export type PostListItemBodyMediaType = typeof PostListItemBodyMediaType[keyof typeof PostListItemBodyMediaType];


export const PostListItemBodyMediaType = {
  TV_SHOW: 'TV_SHOW',
  MOVIE: 'MOVIE',
} as const;

export type PostListItemBody = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  listId: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  tmdbId: number;
  mediaType: PostListItemBodyMediaType;
};

export type PostListItem201ListItemMediaType = typeof PostListItem201ListItemMediaType[keyof typeof PostListItem201ListItemMediaType];


export const PostListItem201ListItemMediaType = {
  TV_SHOW: 'TV_SHOW',
  MOVIE: 'MOVIE',
} as const;

export type PostListItem201ListItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  listId: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  tmdbId: number;
  mediaType: PostListItem201ListItemMediaType;
  createdAt: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  position: number | null;
};

export type PostListItem201 = {
  listItem: PostListItem201ListItem;
};

export type GetListItemsByListIdParams = {
language?: GetListItemsByListIdLanguage;
};

export type GetListItemsByListIdLanguage = typeof GetListItemsByListIdLanguage[keyof typeof GetListItemsByListIdLanguage];


export const GetListItemsByListIdLanguage = {
  'en-US': 'en-US',
  'es-ES': 'es-ES',
  'fr-FR': 'fr-FR',
  'de-DE': 'de-DE',
  'it-IT': 'it-IT',
  'pt-BR': 'pt-BR',
  'ja-JP': 'ja-JP',
} as const;

export type GetListItemsByListId200ItemMediaType = typeof GetListItemsByListId200ItemMediaType[keyof typeof GetListItemsByListId200ItemMediaType];


export const GetListItemsByListId200ItemMediaType = {
  TV_SHOW: 'TV_SHOW',
  MOVIE: 'MOVIE',
} as const;

export type GetListItemsByListId200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  listId: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  tmdbId: number;
  mediaType: GetListItemsByListId200ItemMediaType;
  createdAt: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  position: number | null;
  title: string;
  /** @nullable */
  posterPath: string | null;
  /** @nullable */
  backdropPath: string | null;
};

export type UpdateListItemsPositionsBodyListItemsItem = {
  id: string;
  position: number;
};

export type UpdateListItemsPositionsBody = {
  listItems: UpdateListItemsPositionsBodyListItemsItem[];
};

export type PutUserItemBodyMediaType = typeof PutUserItemBodyMediaType[keyof typeof PutUserItemBodyMediaType];


export const PutUserItemBodyMediaType = {
  TV_SHOW: 'TV_SHOW',
  MOVIE: 'MOVIE',
} as const;

export type PutUserItemBodyStatus = typeof PutUserItemBodyStatus[keyof typeof PutUserItemBodyStatus];


export const PutUserItemBodyStatus = {
  WATCHLIST: 'WATCHLIST',
  WATCHED: 'WATCHED',
  WATCHING: 'WATCHING',
  DROPPED: 'DROPPED',
} as const;

export type PutUserItemBody = {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  tmdbId: number;
  mediaType: PutUserItemBodyMediaType;
  status: PutUserItemBodyStatus;
};

export type PutUserItem201UserItemMediaType = typeof PutUserItem201UserItemMediaType[keyof typeof PutUserItem201UserItemMediaType];


export const PutUserItem201UserItemMediaType = {
  TV_SHOW: 'TV_SHOW',
  MOVIE: 'MOVIE',
} as const;

export type PutUserItem201UserItemStatus = typeof PutUserItem201UserItemStatus[keyof typeof PutUserItem201UserItemStatus];


export const PutUserItem201UserItemStatus = {
  WATCHLIST: 'WATCHLIST',
  WATCHED: 'WATCHED',
  WATCHING: 'WATCHING',
  DROPPED: 'DROPPED',
} as const;

export type PutUserItem201UserItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  tmdbId: number;
  mediaType: PutUserItem201UserItemMediaType;
  status: PutUserItem201UserItemStatus;
  addedAt: string;
  updatedAt: string;
};

export type PutUserItem201 = {
  userItem: PutUserItem201UserItem;
};

export type GetUserItemParams = {
mediaType: GetUserItemMediaType;
tmdbId: string;
};

export type GetUserItemMediaType = typeof GetUserItemMediaType[keyof typeof GetUserItemMediaType];


export const GetUserItemMediaType = {
  TV_SHOW: 'TV_SHOW',
  MOVIE: 'MOVIE',
} as const;

export type GetUserItem200UserItemMediaType = typeof GetUserItem200UserItemMediaType[keyof typeof GetUserItem200UserItemMediaType];


export const GetUserItem200UserItemMediaType = {
  TV_SHOW: 'TV_SHOW',
  MOVIE: 'MOVIE',
} as const;

export type GetUserItem200UserItemStatus = typeof GetUserItem200UserItemStatus[keyof typeof GetUserItem200UserItemStatus];


export const GetUserItem200UserItemStatus = {
  WATCHLIST: 'WATCHLIST',
  WATCHED: 'WATCHED',
  WATCHING: 'WATCHING',
  DROPPED: 'DROPPED',
} as const;

export type GetUserItem200UserItemWatchEntriesItem = {
  id: string;
  watchedAt: string;
};

export type GetUserItem200UserItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  tmdbId: number;
  mediaType: GetUserItem200UserItemMediaType;
  status: GetUserItem200UserItemStatus;
  addedAt: string;
  updatedAt: string;
  watchEntries?: GetUserItem200UserItemWatchEntriesItem[];
};

export type GetUserItem200 = {
  userItem?: GetUserItem200UserItem;
};

export type GetUserItemsBodyStatus = typeof GetUserItemsBodyStatus[keyof typeof GetUserItemsBodyStatus];


export const GetUserItemsBodyStatus = {
  WATCHLIST: 'WATCHLIST',
  WATCHED: 'WATCHED',
  WATCHING: 'WATCHING',
  DROPPED: 'DROPPED',
  ALL: 'ALL',
} as const;

export type GetUserItemsBodyMediaTypeItem = typeof GetUserItemsBodyMediaTypeItem[keyof typeof GetUserItemsBodyMediaTypeItem];


export const GetUserItemsBodyMediaTypeItem = {
  TV_SHOW: 'TV_SHOW',
  MOVIE: 'MOVIE',
} as const;

export type GetUserItemsBodyOrderBy = typeof GetUserItemsBodyOrderBy[keyof typeof GetUserItemsBodyOrderBy];


export const GetUserItemsBodyOrderBy = {
  addedAtdesc: 'addedAt.desc',
  addedAtasc: 'addedAt.asc',
  updatedAtdesc: 'updatedAt.desc',
  updatedAtasc: 'updatedAt.asc',
  ratingdesc: 'rating.desc',
  ratingasc: 'rating.asc',
} as const;

export type GetUserItemsBodyLanguage = typeof GetUserItemsBodyLanguage[keyof typeof GetUserItemsBodyLanguage];


export const GetUserItemsBodyLanguage = {
  'en-US': 'en-US',
  'es-ES': 'es-ES',
  'fr-FR': 'fr-FR',
  'de-DE': 'de-DE',
  'it-IT': 'it-IT',
  'pt-BR': 'pt-BR',
  'ja-JP': 'ja-JP',
} as const;

export type GetUserItemsBody = {
  status: GetUserItemsBodyStatus;
  userId: string;
  rating?: string[];
  mediaType: GetUserItemsBodyMediaTypeItem[];
  orderBy: GetUserItemsBodyOrderBy;
  onlyItemsWithoutReview?: boolean;
  language?: GetUserItemsBodyLanguage;
  cursor?: string;
  pageSize?: string;
};

export type GetUserItems200UserItemsItemMediaType = typeof GetUserItems200UserItemsItemMediaType[keyof typeof GetUserItems200UserItemsItemMediaType];


export const GetUserItems200UserItemsItemMediaType = {
  TV_SHOW: 'TV_SHOW',
  MOVIE: 'MOVIE',
} as const;

export type GetUserItems200UserItemsItemStatus = typeof GetUserItems200UserItemsItemStatus[keyof typeof GetUserItems200UserItemsItemStatus];


export const GetUserItems200UserItemsItemStatus = {
  WATCHLIST: 'WATCHLIST',
  WATCHED: 'WATCHED',
  WATCHING: 'WATCHING',
  DROPPED: 'DROPPED',
} as const;

export type GetUserItems200UserItemsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  tmdbId: number;
  mediaType: GetUserItems200UserItemsItemMediaType;
  status: GetUserItems200UserItemsItemStatus;
  addedAt: string;
  updatedAt: string;
  title: string;
  /** @nullable */
  posterPath: string | null;
  /** @nullable */
  backdropPath: string | null;
};

export type GetUserItems200 = {
  userItems: GetUserItems200UserItemsItem[];
  /** @nullable */
  nextCursor: string | null;
};

export type GetAllUserItemsParams = {
userId: string;
status: GetAllUserItemsStatus;
};

export type GetAllUserItemsStatus = typeof GetAllUserItemsStatus[keyof typeof GetAllUserItemsStatus];


export const GetAllUserItemsStatus = {
  WATCHLIST: 'WATCHLIST',
  WATCHED: 'WATCHED',
  WATCHING: 'WATCHING',
  DROPPED: 'DROPPED',
  ALL: 'ALL',
} as const;

export type GetAllUserItems200UserItemsItemMediaType = typeof GetAllUserItems200UserItemsItemMediaType[keyof typeof GetAllUserItems200UserItemsItemMediaType];


export const GetAllUserItems200UserItemsItemMediaType = {
  TV_SHOW: 'TV_SHOW',
  MOVIE: 'MOVIE',
} as const;

export type GetAllUserItems200UserItemsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  mediaType: GetAllUserItems200UserItemsItemMediaType;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  tmdbId: number;
};

export type GetAllUserItems200 = {
  userItems: GetAllUserItems200UserItemsItem[];
};

export type GetUserItemsCountParams = {
userId: string;
};

export type GetUserItemsCount200 = {
  count: number;
};

export type PostReviewReplyBody = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  reviewId: string;
  reply: string;
};

export type PostReviewReply201ReviewReply = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  createdAt: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  reply: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  reviewId: string;
};

/**
 * Review reply created.
 */
export type PostReviewReply201 = {
  reviewReply: PostReviewReply201ReviewReply;
};

/**
 * Review or user not found
 */
export type PostReviewReply404 = {
  message: string;
};

export type GetReviewRepliesParams = {
reviewId: string;
};

export type GetReviewReplies200ItemUser = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};

/**
 * @nullable
 */
export type GetReviewReplies200ItemUserLike = {
  id: string;
  entityId: string;
  userId: string;
  createdAt: string;
} | null;

export type GetReviewReplies200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  createdAt: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  reply: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  reviewId: string;
  user: GetReviewReplies200ItemUser;
  likeCount: number;
  /** @nullable */
  userLike: GetReviewReplies200ItemUserLike;
};

export type PutReviewReplyByIdBody = {
  reply: string;
};

export type PutReviewReplyById200ReviewReply = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  createdAt: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  reply: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  reviewId: string;
};

export type PutReviewReplyById200 = {
  reviewReply: PutReviewReplyById200ReviewReply;
};

export type PutSocialLinksBody = {[key: string]: string | ''};

export type GetSocialLinksParams = {
userId: string;
};

export type GetSocialLinks200SocialLinksItemPlatform = typeof GetSocialLinks200SocialLinksItemPlatform[keyof typeof GetSocialLinks200SocialLinksItemPlatform];


export const GetSocialLinks200SocialLinksItemPlatform = {
  INSTAGRAM: 'INSTAGRAM',
  TIKTOK: 'TIKTOK',
  YOUTUBE: 'YOUTUBE',
  X: 'X',
} as const;

export type GetSocialLinks200SocialLinksItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  platform: GetSocialLinks200SocialLinksItemPlatform;
  url: string;
  createdAt: string;
};

export type GetSocialLinks200 = {
  socialLinks: GetSocialLinks200SocialLinksItem[];
};

export type PostUserEpisodesBodyItem = {
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  tmdbId: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  seasonNumber: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  episodeNumber: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  runtime?: number;
};

export type PostUserEpisodes201Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  tmdbId: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  seasonNumber: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  episodeNumber: number;
  watchedAt: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  runtime: number;
};

/**
 * User episodes already registered.
 */
export type PostUserEpisodes409 = {
  message: string;
};

export type GetUserEpisodesParams = {
tmdbId: string;
};

export type GetUserEpisodes200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  tmdbId: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  seasonNumber: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  episodeNumber: number;
  watchedAt: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  runtime: number;
};

export type DeleteUserEpisodesBody = {
  ids: string[];
};

/**
 * @nullable
 */
export type DeleteUserEpisodes204 = typeof DeleteUserEpisodes204[keyof typeof DeleteUserEpisodes204] | null;


export const DeleteUserEpisodes204 = {
} as const;

export type PostLikeBodyEntityType = typeof PostLikeBodyEntityType[keyof typeof PostLikeBodyEntityType];


export const PostLikeBodyEntityType = {
  REVIEW: 'REVIEW',
  REPLY: 'REPLY',
  LIST: 'LIST',
} as const;

export type PostLikeBody = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  entityId: string;
  entityType: PostLikeBodyEntityType;
};

export type PostLike201LikeEntityType = typeof PostLike201LikeEntityType[keyof typeof PostLike201LikeEntityType];


export const PostLike201LikeEntityType = {
  REVIEW: 'REVIEW',
  REPLY: 'REPLY',
  LIST: 'LIST',
} as const;

export type PostLike201Like = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  entityId: string;
  entityType: PostLike201LikeEntityType;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  createdAt: string;
};

export type PostLike201 = {
  like: PostLike201Like;
};

export type GetLikesEntityId200LikesItemEntityType = typeof GetLikesEntityId200LikesItemEntityType[keyof typeof GetLikesEntityId200LikesItemEntityType];


export const GetLikesEntityId200LikesItemEntityType = {
  REVIEW: 'REVIEW',
  REPLY: 'REPLY',
  LIST: 'LIST',
} as const;

export type GetLikesEntityId200LikesItemUserSubscriptionType = typeof GetLikesEntityId200LikesItemUserSubscriptionType[keyof typeof GetLikesEntityId200LikesItemUserSubscriptionType];


export const GetLikesEntityId200LikesItemUserSubscriptionType = {
  MEMBER: 'MEMBER',
  PRO: 'PRO',
} as const;

export type GetLikesEntityId200LikesItemUser = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
  subscriptionType: GetLikesEntityId200LikesItemUserSubscriptionType;
};

export type GetLikesEntityId200LikesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  entityId: string;
  entityType: GetLikesEntityId200LikesItemEntityType;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  createdAt: string;
  user: GetLikesEntityId200LikesItemUser;
};

export type GetLikesEntityId200 = {
  likes: GetLikesEntityId200LikesItem[];
};

export type GetUserIdStats200 = {
  followersCount: number;
  followingCount: number;
  watchedMoviesCount: number;
  watchedSeriesCount: number;
};

export type GetUserIdTotalHours200 = {
  totalHours: number;
};

export type GetUserIdReviewsCount200 = {
  reviewsCount: number;
};

export type GetUserIdMostWatchedSeriesParams = {
language?: GetUserIdMostWatchedSeriesLanguage;
};

export type GetUserIdMostWatchedSeriesLanguage = typeof GetUserIdMostWatchedSeriesLanguage[keyof typeof GetUserIdMostWatchedSeriesLanguage];


export const GetUserIdMostWatchedSeriesLanguage = {
  'en-US': 'en-US',
  'es-ES': 'es-ES',
  'fr-FR': 'fr-FR',
  'de-DE': 'de-DE',
  'it-IT': 'it-IT',
  'pt-BR': 'pt-BR',
  'ja-JP': 'ja-JP',
} as const;

export type GetUserIdMostWatchedSeries200MostWatchedSeriesItem = {
  id: number;
  episodes: number;
  title: string;
  /** @nullable */
  posterPath: string | null;
  /** @nullable */
  backdropPath: string | null;
};

export type GetUserIdMostWatchedSeries200 = {
  mostWatchedSeries: GetUserIdMostWatchedSeries200MostWatchedSeriesItem[];
};

export type GetUserIdWatchedGenresParams = {
language?: GetUserIdWatchedGenresLanguage;
};

export type GetUserIdWatchedGenresLanguage = typeof GetUserIdWatchedGenresLanguage[keyof typeof GetUserIdWatchedGenresLanguage];


export const GetUserIdWatchedGenresLanguage = {
  'en-US': 'en-US',
  'es-ES': 'es-ES',
  'fr-FR': 'fr-FR',
  'de-DE': 'de-DE',
  'it-IT': 'it-IT',
  'pt-BR': 'pt-BR',
  'ja-JP': 'ja-JP',
} as const;

export type GetUserIdWatchedGenres200GenresItem = {
  name: string;
  count: number;
  percentage: number;
};

export type GetUserIdWatchedGenres200 = {
  genres: GetUserIdWatchedGenres200GenresItem[];
};

export type GetUserIdWatchedCastParams = {
language?: GetUserIdWatchedCastLanguage;
};

export type GetUserIdWatchedCastLanguage = typeof GetUserIdWatchedCastLanguage[keyof typeof GetUserIdWatchedCastLanguage];


export const GetUserIdWatchedCastLanguage = {
  'en-US': 'en-US',
  'es-ES': 'es-ES',
  'fr-FR': 'fr-FR',
  'de-DE': 'de-DE',
  'it-IT': 'it-IT',
  'pt-BR': 'pt-BR',
  'ja-JP': 'ja-JP',
} as const;

export type GetUserIdWatchedCast200WatchedCastItem = {
  id: string;
  name: string;
  count: number;
  percentage: number;
  /** @nullable */
  profilePath: string | null;
};

export type GetUserIdWatchedCast200 = {
  watchedCast: GetUserIdWatchedCast200WatchedCastItem[];
};

export type GetUserIdWatchedCountriesParams = {
language?: GetUserIdWatchedCountriesLanguage;
};

export type GetUserIdWatchedCountriesLanguage = typeof GetUserIdWatchedCountriesLanguage[keyof typeof GetUserIdWatchedCountriesLanguage];


export const GetUserIdWatchedCountriesLanguage = {
  'en-US': 'en-US',
  'es-ES': 'es-ES',
  'fr-FR': 'fr-FR',
  'de-DE': 'de-DE',
  'it-IT': 'it-IT',
  'pt-BR': 'pt-BR',
  'ja-JP': 'ja-JP',
} as const;

export type GetUserIdWatchedCountries200WatchedCountriesItem = {
  name: string;
  count: number;
  percentage: number;
};

export type GetUserIdWatchedCountries200 = {
  watchedCountries: GetUserIdWatchedCountries200WatchedCountriesItem[];
};

export type GetUserIdBestReviewsParams = {
language?: GetUserIdBestReviewsLanguage;
};

export type GetUserIdBestReviewsLanguage = typeof GetUserIdBestReviewsLanguage[keyof typeof GetUserIdBestReviewsLanguage];


export const GetUserIdBestReviewsLanguage = {
  'en-US': 'en-US',
  'es-ES': 'es-ES',
  'fr-FR': 'fr-FR',
  'de-DE': 'de-DE',
  'it-IT': 'it-IT',
  'pt-BR': 'pt-BR',
  'ja-JP': 'ja-JP',
} as const;

export type GetUserIdBestReviews200BestReviewsItemMediaType = typeof GetUserIdBestReviews200BestReviewsItemMediaType[keyof typeof GetUserIdBestReviews200BestReviewsItemMediaType];


export const GetUserIdBestReviews200BestReviewsItemMediaType = {
  TV_SHOW: 'TV_SHOW',
  MOVIE: 'MOVIE',
} as const;

/**
 * @nullable
 */
export type GetUserIdBestReviews200BestReviewsItemLanguage = typeof GetUserIdBestReviews200BestReviewsItemLanguage[keyof typeof GetUserIdBestReviews200BestReviewsItemLanguage] | null;


export const GetUserIdBestReviews200BestReviewsItemLanguage = {
  'en-US': 'en-US',
  'es-ES': 'es-ES',
  'fr-FR': 'fr-FR',
  'it-IT': 'it-IT',
  'de-DE': 'de-DE',
  'pt-BR': 'pt-BR',
  'ja-JP': 'ja-JP',
} as const;

export type GetUserIdBestReviews200BestReviewsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  createdAt: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  tmdbId: number;
  mediaType: GetUserIdBestReviews200BestReviewsItemMediaType;
  review: string;
  /**
   * @minimum -8388608
   * @maximum 8388607
   */
  rating: number;
  hasSpoilers: boolean;
  /** @nullable */
  language: GetUserIdBestReviews200BestReviewsItemLanguage;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  seasonNumber: number | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   * @nullable
   */
  episodeNumber: number | null;
  title: string;
  /** @nullable */
  posterPath: string | null;
  /** @nullable */
  date: string | null;
};

export type GetUserIdBestReviews200 = {
  bestReviews: GetUserIdBestReviews200BestReviewsItem[];
};

export type GetUserIdItemsStatus200UserItemsItemStatus = typeof GetUserIdItemsStatus200UserItemsItemStatus[keyof typeof GetUserIdItemsStatus200UserItemsItemStatus];


export const GetUserIdItemsStatus200UserItemsItemStatus = {
  WATCHLIST: 'WATCHLIST',
  WATCHED: 'WATCHED',
  WATCHING: 'WATCHING',
  DROPPED: 'DROPPED',
} as const;

export type GetUserIdItemsStatus200UserItemsItem = {
  status: GetUserIdItemsStatus200UserItemsItemStatus;
  count: number;
  percentage: number;
};

export type GetUserIdItemsStatus200 = {
  userItems: GetUserIdItemsStatus200UserItemsItem[];
};

export type PostImageParams = {
folder: PostImageFolder;
fileName?: string;
};

export type PostImageFolder = typeof PostImageFolder[keyof typeof PostImageFolder];


export const PostImageFolder = {
  banner: 'banner',
  avatar: 'avatar',
  list: 'list',
} as const;

export type PostImageBody = {
  file: Blob;
};

export type PostImage201 = {
  url: string;
};

export type PostFollowBody = {
  userId: string;
};

export type GetFollowParams = {
userId: string;
};

/**
 * @nullable
 */
export type GetFollow200Follow = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  followerId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  followedId: string;
  createdAt: string;
} | null;

export type GetFollow200 = {
  /** @nullable */
  follow: GetFollow200Follow;
};

export type DeleteFollowBody = {
  userId: string;
};

export type GetFollowersParams = {
followedId?: string;
followerId?: string;
pageSize?: string;
cursor?: string;
};

export type GetFollowers200FollowersItemSubscriptionType = typeof GetFollowers200FollowersItemSubscriptionType[keyof typeof GetFollowers200FollowersItemSubscriptionType];


export const GetFollowers200FollowersItemSubscriptionType = {
  PRO: 'PRO',
  MEMBER: 'MEMBER',
} as const;

export type GetFollowers200FollowersItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  followerId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  followedId: string;
  createdAt: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
  subscriptionType: GetFollowers200FollowersItemSubscriptionType;
};

export type GetFollowers200 = {
  followers: GetFollowers200FollowersItem[];
  /** @nullable */
  nextCursor: string | null;
};

export type PostImportParams = {
provider: PostImportProvider;
};

export type PostImportProvider = typeof PostImportProvider[keyof typeof PostImportProvider];


export const PostImportProvider = {
  MY_ANIME_LIST: 'MY_ANIME_LIST',
  LETTERBOXD: 'LETTERBOXD',
} as const;

export type PostImportBody = {
  file: Blob;
};

export type PostImport200 = {
  message: string;
};

export type PostImport422 = {
  message: string;
};

export type GetImportImportId200SeriesItemImportStatus = typeof GetImportImportId200SeriesItemImportStatus[keyof typeof GetImportImportId200SeriesItemImportStatus];


export const GetImportImportId200SeriesItemImportStatus = {
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  NOT_STARTED: 'NOT_STARTED',
} as const;

export type GetImportImportId200SeriesItemUserItemStatus = typeof GetImportImportId200SeriesItemUserItemStatus[keyof typeof GetImportImportId200SeriesItemUserItemStatus];


export const GetImportImportId200SeriesItemUserItemStatus = {
  WATCHLIST: 'WATCHLIST',
  WATCHED: 'WATCHED',
  WATCHING: 'WATCHING',
  DROPPED: 'DROPPED',
} as const;

export type GetImportImportId200SeriesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  importId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  importStatus: GetImportImportId200SeriesItemImportStatus;
  createdAt: string;
  updatedAt: string;
  name: string;
  /** @nullable */
  tmdbId: number | null;
  /** @nullable */
  startDate: string | null;
  /** @nullable */
  endDate: string | null;
  userItemStatus: GetImportImportId200SeriesItemUserItemStatus;
  /** @nullable */
  watchedEpisodes: number | null;
  /** @nullable */
  seriesEpisodes: number | null;
};

export type GetImportImportId200MoviesItemImportStatus = typeof GetImportImportId200MoviesItemImportStatus[keyof typeof GetImportImportId200MoviesItemImportStatus];


export const GetImportImportId200MoviesItemImportStatus = {
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  NOT_STARTED: 'NOT_STARTED',
} as const;

export type GetImportImportId200MoviesItemUserItemStatus = typeof GetImportImportId200MoviesItemUserItemStatus[keyof typeof GetImportImportId200MoviesItemUserItemStatus];


export const GetImportImportId200MoviesItemUserItemStatus = {
  WATCHLIST: 'WATCHLIST',
  WATCHED: 'WATCHED',
  WATCHING: 'WATCHING',
  DROPPED: 'DROPPED',
} as const;

export type GetImportImportId200MoviesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  importId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  importStatus: GetImportImportId200MoviesItemImportStatus;
  createdAt: string;
  updatedAt: string;
  name: string;
  /** @nullable */
  tmdbId: number | null;
  /** @nullable */
  endDate: string | null;
  userItemStatus: GetImportImportId200MoviesItemUserItemStatus;
};

export type GetImportImportId200ImportStatus = typeof GetImportImportId200ImportStatus[keyof typeof GetImportImportId200ImportStatus];


export const GetImportImportId200ImportStatus = {
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  PARTIAL: 'PARTIAL',
  NOT_STARTED: 'NOT_STARTED',
} as const;

export type GetImportImportId200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  itemsCount: number;
  series: GetImportImportId200SeriesItem[];
  movies: GetImportImportId200MoviesItem[];
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  provider: string;
  importStatus: GetImportImportId200ImportStatus;
  createdAt: string;
  updatedAt: string;
};

/**
 * Import not found.
 */
export type GetImportImportId404 = {
  message: string;
};

export type GetUserActivitiesParams = {
cursor?: string;
pageSize?: string;
language?: GetUserActivitiesLanguage;
};

export type GetUserActivitiesLanguage = typeof GetUserActivitiesLanguage[keyof typeof GetUserActivitiesLanguage];


export const GetUserActivitiesLanguage = {
  'en-US': 'en-US',
  'es-ES': 'es-ES',
  'fr-FR': 'fr-FR',
  'de-DE': 'de-DE',
  'it-IT': 'it-IT',
  'pt-BR': 'pt-BR',
  'ja-JP': 'ja-JP',
} as const;

export type GetUserActivities200UserActivitiesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  metadata: string | number | boolean | null | {[key: string]: unknown} | unknown[];
  createdAt: string;
  owner: {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};
  activityType: 'ADD_ITEM' | 'DELETE_ITEM';
  entityType: 'LIST';
  entityId: string;
  additionalInfo: {
  tmdbId: number;
  mediaType: 'TV_SHOW' | 'MOVIE';
  /** @nullable */
  listId: string | null;
  /** @nullable */
  listTitle: string | null;
  title: string;
};
} | {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  metadata: string | number | boolean | null | {[key: string]: unknown} | unknown[];
  createdAt: string;
  owner: {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};
  activityType: 'FOLLOW_USER' | 'UNFOLLOW_USER';
  /** @nullable */
  entityType:  | null;
  /** @nullable */
  entityId:  | null;
  additionalInfo: {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};
} | {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  metadata: string | number | boolean | null | {[key: string]: unknown} | unknown[];
  createdAt: string;
  owner: {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};
  activityType: 'CREATE_LIST' | 'LIKE_LIST';
  entityType: 'LIST';
  entityId: string;
  additionalInfo: {
  id: string;
  title: string;
};
} | {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  metadata: string | number | boolean | null | {[key: string]: unknown} | unknown[];
  createdAt: string;
  owner: {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};
  activityType: 'LIKE_REVIEW' | 'CREATE_REVIEW';
  entityType: 'REVIEW';
  entityId: string;
  additionalInfo: {
  id: string;
  review: string;
  rating: number;
  /** @nullable */
  seasonNumber: number | null;
  /** @nullable */
  episodeNumber: number | null;
  tmdbId: number;
  mediaType: 'TV_SHOW' | 'MOVIE';
  title: string;
  author: {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};
};
} | {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  metadata: string | number | boolean | null | {[key: string]: unknown} | unknown[];
  createdAt: string;
  owner: {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};
  activityType: 'LIKE_REPLY' | 'CREATE_REPLY';
  entityType: 'REPLY';
  entityId: string;
  additionalInfo: {
  id: string;
  reply: string;
  review: {
  id: string;
  review: string;
  rating: number;
  /** @nullable */
  seasonNumber: number | null;
  /** @nullable */
  episodeNumber: number | null;
  tmdbId: number;
  mediaType: 'TV_SHOW' | 'MOVIE';
  title: string;
  author: {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};
};
};
} | {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  metadata: string | number | boolean | null | {[key: string]: unknown} | unknown[];
  createdAt: string;
  owner: {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};
  activityType: 'WATCH_EPISODE';
  /** @nullable */
  entityType:  | null;
  /** @nullable */
  entityId:  | null;
  additionalInfo: {
  episodes: {
  tmdbId: number;
  seasonNumber: number;
  episodeNumber: number;
  runtime: number;
}[];
  title: string;
  tmdbId: number;
};
} | {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  metadata: string | number | boolean | null | {[key: string]: unknown} | unknown[];
  createdAt: string;
  owner: {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};
  activityType: 'CHANGE_STATUS';
  /** @nullable */
  entityType:  | null;
  /** @nullable */
  entityId:  | null;
  additionalInfo: {
  tmdbId: number;
  mediaType: 'TV_SHOW' | 'MOVIE';
  status: string;
  title: string;
};
} | {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  metadata: string | number | boolean | null | {[key: string]: unknown} | unknown[];
  createdAt: string;
  owner: {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};
  activityType: 'CREATE_ACCOUNT';
  /** @nullable */
  entityType:  | null;
  /** @nullable */
  entityId:  | null;
};

export type GetUserActivities200 = {
  userActivities: GetUserActivities200UserActivitiesItem[];
  /** @nullable */
  nextCursor: string | null;
};

export type GetNetworkActivitiesParams = {
cursor?: string;
pageSize?: string;
userId: string;
language?: GetNetworkActivitiesLanguage;
};

export type GetNetworkActivitiesLanguage = typeof GetNetworkActivitiesLanguage[keyof typeof GetNetworkActivitiesLanguage];


export const GetNetworkActivitiesLanguage = {
  'en-US': 'en-US',
  'es-ES': 'es-ES',
  'fr-FR': 'fr-FR',
  'de-DE': 'de-DE',
  'it-IT': 'it-IT',
  'pt-BR': 'pt-BR',
  'ja-JP': 'ja-JP',
} as const;

export type GetNetworkActivities200UserActivitiesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  metadata: string | number | boolean | null | {[key: string]: unknown} | unknown[];
  createdAt: string;
  owner: {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};
  activityType: 'ADD_ITEM' | 'DELETE_ITEM';
  entityType: 'LIST';
  entityId: string;
  additionalInfo: {
  tmdbId: number;
  mediaType: 'TV_SHOW' | 'MOVIE';
  /** @nullable */
  listId: string | null;
  /** @nullable */
  listTitle: string | null;
  title: string;
};
} | {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  metadata: string | number | boolean | null | {[key: string]: unknown} | unknown[];
  createdAt: string;
  owner: {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};
  activityType: 'FOLLOW_USER' | 'UNFOLLOW_USER';
  /** @nullable */
  entityType:  | null;
  /** @nullable */
  entityId:  | null;
  additionalInfo: {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};
} | {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  metadata: string | number | boolean | null | {[key: string]: unknown} | unknown[];
  createdAt: string;
  owner: {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};
  activityType: 'CREATE_LIST' | 'LIKE_LIST';
  entityType: 'LIST';
  entityId: string;
  additionalInfo: {
  id: string;
  title: string;
};
} | {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  metadata: string | number | boolean | null | {[key: string]: unknown} | unknown[];
  createdAt: string;
  owner: {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};
  activityType: 'LIKE_REVIEW' | 'CREATE_REVIEW';
  entityType: 'REVIEW';
  entityId: string;
  additionalInfo: {
  id: string;
  review: string;
  rating: number;
  /** @nullable */
  seasonNumber: number | null;
  /** @nullable */
  episodeNumber: number | null;
  tmdbId: number;
  mediaType: 'TV_SHOW' | 'MOVIE';
  title: string;
  author: {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};
};
} | {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  metadata: string | number | boolean | null | {[key: string]: unknown} | unknown[];
  createdAt: string;
  owner: {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};
  activityType: 'LIKE_REPLY' | 'CREATE_REPLY';
  entityType: 'REPLY';
  entityId: string;
  additionalInfo: {
  id: string;
  reply: string;
  review: {
  id: string;
  review: string;
  rating: number;
  /** @nullable */
  seasonNumber: number | null;
  /** @nullable */
  episodeNumber: number | null;
  tmdbId: number;
  mediaType: 'TV_SHOW' | 'MOVIE';
  title: string;
  author: {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};
};
};
} | {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  metadata: string | number | boolean | null | {[key: string]: unknown} | unknown[];
  createdAt: string;
  owner: {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};
  activityType: 'WATCH_EPISODE';
  /** @nullable */
  entityType:  | null;
  /** @nullable */
  entityId:  | null;
  additionalInfo: {
  episodes: {
  tmdbId: number;
  seasonNumber: number;
  episodeNumber: number;
  runtime: number;
}[];
  title: string;
  tmdbId: number;
};
} | {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  metadata: string | number | boolean | null | {[key: string]: unknown} | unknown[];
  createdAt: string;
  owner: {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};
  activityType: 'CHANGE_STATUS';
  /** @nullable */
  entityType:  | null;
  /** @nullable */
  entityId:  | null;
  additionalInfo: {
  tmdbId: number;
  mediaType: 'TV_SHOW' | 'MOVIE';
  status: string;
  title: string;
};
} | {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userId: string;
  metadata: string | number | boolean | null | {[key: string]: unknown} | unknown[];
  createdAt: string;
  owner: {
  id: string;
  username: string;
  /** @nullable */
  avatarUrl: string | null;
};
  activityType: 'CREATE_ACCOUNT';
  /** @nullable */
  entityType:  | null;
  /** @nullable */
  entityId:  | null;
};

export type GetNetworkActivities200 = {
  userActivities: GetNetworkActivities200UserActivitiesItem[];
  /** @nullable */
  nextCursor: string | null;
};

export type DeleteUserSubscriptionBodyWhen = typeof DeleteUserSubscriptionBodyWhen[keyof typeof DeleteUserSubscriptionBodyWhen];


export const DeleteUserSubscriptionBodyWhen = {
  now: 'now',
  at_end_of_current_period: 'at_end_of_current_period',
} as const;

export type DeleteUserSubscriptionBody = {
  when: DeleteUserSubscriptionBodyWhen;
  reason?: string;
};

export type DeleteUserSubscription200 = {
  message: string;
};

export type PostWatchEntryBody = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userItemId: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  watchedAt?: string;
};

export type PostWatchEntry201WatchEntry = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userItemId: string;
  watchedAt: string;
  createdAt: string;
};

export type PostWatchEntry201 = {
  watchEntry: PostWatchEntry201WatchEntry;
};

export type GetWatchEntriesParams = {
/**
 * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
 */
userItemId: string;
};

export type GetWatchEntries200WatchEntriesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userItemId: string;
  watchedAt: string;
  createdAt: string;
};

export type GetWatchEntries200 = {
  watchEntries: GetWatchEntries200WatchEntriesItem[];
};

export type PutWatchEntryIdBody = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  watchedAt: string;
};

export type PutWatchEntryId200WatchEntry = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userItemId: string;
  watchedAt: string;
  createdAt: string;
};

export type PutWatchEntryId200 = {
  watchEntry: PutWatchEntryId200WatchEntry;
};

