/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Plotwist
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteListId204,
  DeleteListId404,
  GetListById200,
  GetListById404,
  GetListProgress200,
  GetLists200,
  GetLists404,
  GetListsParams,
  PatchListBanner200,
  PatchListBannerBody,
  PostList201,
  PostList404,
  PostListBody,
  PutListId200,
  PutListId404,
  PutListIdBody
} from './endpoints.schemas';

import { axiosInstance } from '../services/axios-instance';





/**
 * Create a list
 */
export type postListResponse201 = {
  data: PostList201
  status: 201
}

export type postListResponse404 = {
  data: PostList404
  status: 404
}
    
export type postListResponseSuccess = (postListResponse201) & {
  headers: Headers;
};
export type postListResponseError = (postListResponse404) & {
  headers: Headers;
};

export type postListResponse = (postListResponseSuccess | postListResponseError)

export const getPostListUrl = () => {


  

  return `/list`
}

export const postList = async (postListBody: PostListBody, options?: RequestInit): Promise<postListResponse> => {
  
  return axiosInstance<postListResponse>(getPostListUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postListBody,)
  }
);}




export const getPostListMutationOptions = <TError = PostList404,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postList>>, TError,{data: PostListBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postList>>, TError,{data: PostListBody}, TContext> => {

const mutationKey = ['postList'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postList>>, {data: PostListBody}> = (props) => {
          const {data} = props ?? {};

          return  postList(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostListMutationResult = NonNullable<Awaited<ReturnType<typeof postList>>>
    export type PostListMutationBody = PostListBody
    export type PostListMutationError = PostList404

    export const usePostList = <TError = PostList404,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postList>>, TError,{data: PostListBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postList>>,
        TError,
        {data: PostListBody},
        TContext
      > => {
      return useMutation(getPostListMutationOptions(options), queryClient);
    }
    /**
 * Get lists
 */
export type getListsResponse200 = {
  data: GetLists200
  status: 200
}

export type getListsResponse404 = {
  data: GetLists404
  status: 404
}
    
export type getListsResponseSuccess = (getListsResponse200) & {
  headers: Headers;
};
export type getListsResponseError = (getListsResponse404) & {
  headers: Headers;
};

export type getListsResponse = (getListsResponseSuccess | getListsResponseError)

export const getGetListsUrl = (params?: GetListsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/lists?${stringifiedParams}` : `/lists`
}

export const getLists = async (params?: GetListsParams, options?: RequestInit): Promise<getListsResponse> => {
  
  return axiosInstance<getListsResponse>(getGetListsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetListsQueryKey = (params?: GetListsParams,) => {
    return [
    `/lists`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetListsQueryOptions = <TData = Awaited<ReturnType<typeof getLists>>, TError = GetLists404>(params?: GetListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLists>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetListsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLists>>> = ({ signal }) => getLists(params, { signal });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLists>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetListsQueryResult = NonNullable<Awaited<ReturnType<typeof getLists>>>
export type GetListsQueryError = GetLists404


export function useGetLists<TData = Awaited<ReturnType<typeof getLists>>, TError = GetLists404>(
 params: undefined |  GetListsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLists>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLists>>,
          TError,
          Awaited<ReturnType<typeof getLists>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLists<TData = Awaited<ReturnType<typeof getLists>>, TError = GetLists404>(
 params?: GetListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLists>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLists>>,
          TError,
          Awaited<ReturnType<typeof getLists>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLists<TData = Awaited<ReturnType<typeof getLists>>, TError = GetLists404>(
 params?: GetListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLists>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetLists<TData = Awaited<ReturnType<typeof getLists>>, TError = GetLists404>(
 params?: GetListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLists>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetListsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetListsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getLists>>, TError = GetLists404>(params?: GetListsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getLists>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetListsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLists>>> = ({ signal }) => getLists(params, { signal });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getLists>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetListsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getLists>>>
export type GetListsSuspenseQueryError = GetLists404


export function useGetListsSuspense<TData = Awaited<ReturnType<typeof getLists>>, TError = GetLists404>(
 params: undefined |  GetListsParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getLists>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListsSuspense<TData = Awaited<ReturnType<typeof getLists>>, TError = GetLists404>(
 params?: GetListsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getLists>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListsSuspense<TData = Awaited<ReturnType<typeof getLists>>, TError = GetLists404>(
 params?: GetListsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getLists>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetListsSuspense<TData = Awaited<ReturnType<typeof getLists>>, TError = GetLists404>(
 params?: GetListsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getLists>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetListsSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Delete list
 */
export type deleteListIdResponse204 = {
  data: DeleteListId204
  status: 204
}

export type deleteListIdResponse404 = {
  data: DeleteListId404
  status: 404
}
    
export type deleteListIdResponseSuccess = (deleteListIdResponse204) & {
  headers: Headers;
};
export type deleteListIdResponseError = (deleteListIdResponse404) & {
  headers: Headers;
};

export type deleteListIdResponse = (deleteListIdResponseSuccess | deleteListIdResponseError)

export const getDeleteListIdUrl = (id: string,) => {


  

  return `/list/${id}`
}

export const deleteListId = async (id: string, options?: RequestInit): Promise<deleteListIdResponse> => {
  
  return axiosInstance<deleteListIdResponse>(getDeleteListIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteListIdMutationOptions = <TError = DeleteListId404,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteListId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteListId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteListId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteListId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteListId(id,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteListIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteListId>>>
    
    export type DeleteListIdMutationError = DeleteListId404

    export const useDeleteListId = <TError = DeleteListId404,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteListId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteListId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteListIdMutationOptions(options), queryClient);
    }
    /**
 * Update list
 */
export type putListIdResponse200 = {
  data: PutListId200
  status: 200
}

export type putListIdResponse404 = {
  data: PutListId404
  status: 404
}
    
export type putListIdResponseSuccess = (putListIdResponse200) & {
  headers: Headers;
};
export type putListIdResponseError = (putListIdResponse404) & {
  headers: Headers;
};

export type putListIdResponse = (putListIdResponseSuccess | putListIdResponseError)

export const getPutListIdUrl = (id: string,) => {


  

  return `/list/${id}`
}

export const putListId = async (id: string,
    putListIdBody: PutListIdBody, options?: RequestInit): Promise<putListIdResponse> => {
  
  return axiosInstance<putListIdResponse>(getPutListIdUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      putListIdBody,)
  }
);}




export const getPutListIdMutationOptions = <TError = PutListId404,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putListId>>, TError,{id: string;data: PutListIdBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putListId>>, TError,{id: string;data: PutListIdBody}, TContext> => {

const mutationKey = ['putListId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putListId>>, {id: string;data: PutListIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  putListId(id,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PutListIdMutationResult = NonNullable<Awaited<ReturnType<typeof putListId>>>
    export type PutListIdMutationBody = PutListIdBody
    export type PutListIdMutationError = PutListId404

    export const usePutListId = <TError = PutListId404,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putListId>>, TError,{id: string;data: PutListIdBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putListId>>,
        TError,
        {id: string;data: PutListIdBody},
        TContext
      > => {
      return useMutation(getPutListIdMutationOptions(options), queryClient);
    }
    /**
 * Get list by ID
 */
export type getListByIdResponse200 = {
  data: GetListById200
  status: 200
}

export type getListByIdResponse404 = {
  data: GetListById404
  status: 404
}
    
export type getListByIdResponseSuccess = (getListByIdResponse200) & {
  headers: Headers;
};
export type getListByIdResponseError = (getListByIdResponse404) & {
  headers: Headers;
};

export type getListByIdResponse = (getListByIdResponseSuccess | getListByIdResponseError)

export const getGetListByIdUrl = (id: string,) => {


  

  return `/list/by/${id}`
}

export const getListById = async (id: string, options?: RequestInit): Promise<getListByIdResponse> => {
  
  return axiosInstance<getListByIdResponse>(getGetListByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetListByIdQueryKey = (id: string,) => {
    return [
    `/list/by/${id}`
    ] as const;
    }

    
export const getGetListByIdQueryOptions = <TData = Awaited<ReturnType<typeof getListById>>, TError = GetListById404>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetListByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getListById>>> = ({ signal }) => getListById(id, { signal });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getListById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetListByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getListById>>>
export type GetListByIdQueryError = GetListById404


export function useGetListById<TData = Awaited<ReturnType<typeof getListById>>, TError = GetListById404>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListById>>,
          TError,
          Awaited<ReturnType<typeof getListById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListById<TData = Awaited<ReturnType<typeof getListById>>, TError = GetListById404>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListById>>,
          TError,
          Awaited<ReturnType<typeof getListById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListById<TData = Awaited<ReturnType<typeof getListById>>, TError = GetListById404>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetListById<TData = Awaited<ReturnType<typeof getListById>>, TError = GetListById404>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetListByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetListByIdSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getListById>>, TError = GetListById404>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getListById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetListByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getListById>>> = ({ signal }) => getListById(id, { signal });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getListById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetListByIdSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getListById>>>
export type GetListByIdSuspenseQueryError = GetListById404


export function useGetListByIdSuspense<TData = Awaited<ReturnType<typeof getListById>>, TError = GetListById404>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getListById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListByIdSuspense<TData = Awaited<ReturnType<typeof getListById>>, TError = GetListById404>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getListById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListByIdSuspense<TData = Awaited<ReturnType<typeof getListById>>, TError = GetListById404>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getListById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetListByIdSuspense<TData = Awaited<ReturnType<typeof getListById>>, TError = GetListById404>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getListById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetListByIdSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update list banner by ID
 */
export type patchListBannerResponse200 = {
  data: PatchListBanner200
  status: 200
}
    
export type patchListBannerResponseSuccess = (patchListBannerResponse200) & {
  headers: Headers;
};
;

export type patchListBannerResponse = (patchListBannerResponseSuccess)

export const getPatchListBannerUrl = () => {


  

  return `/list/banner`
}

export const patchListBanner = async (patchListBannerBody: PatchListBannerBody, options?: RequestInit): Promise<patchListBannerResponse> => {
  
  return axiosInstance<patchListBannerResponse>(getPatchListBannerUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      patchListBannerBody,)
  }
);}




export const getPatchListBannerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchListBanner>>, TError,{data: PatchListBannerBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchListBanner>>, TError,{data: PatchListBannerBody}, TContext> => {

const mutationKey = ['patchListBanner'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchListBanner>>, {data: PatchListBannerBody}> = (props) => {
          const {data} = props ?? {};

          return  patchListBanner(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PatchListBannerMutationResult = NonNullable<Awaited<ReturnType<typeof patchListBanner>>>
    export type PatchListBannerMutationBody = PatchListBannerBody
    export type PatchListBannerMutationError = unknown

    export const usePatchListBanner = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchListBanner>>, TError,{data: PatchListBannerBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchListBanner>>,
        TError,
        {data: PatchListBannerBody},
        TContext
      > => {
      return useMutation(getPatchListBannerMutationOptions(options), queryClient);
    }
    /**
 * Get list progress
 */
export type getListProgressResponse200 = {
  data: GetListProgress200
  status: 200
}
    
export type getListProgressResponseSuccess = (getListProgressResponse200) & {
  headers: Headers;
};
;

export type getListProgressResponse = (getListProgressResponseSuccess)

export const getGetListProgressUrl = (id: string,) => {


  

  return `/list/${id}/progress`
}

export const getListProgress = async (id: string, options?: RequestInit): Promise<getListProgressResponse> => {
  
  return axiosInstance<getListProgressResponse>(getGetListProgressUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetListProgressQueryKey = (id: string,) => {
    return [
    `/list/${id}/progress`
    ] as const;
    }

    
export const getGetListProgressQueryOptions = <TData = Awaited<ReturnType<typeof getListProgress>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListProgress>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetListProgressQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getListProgress>>> = ({ signal }) => getListProgress(id, { signal });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getListProgress>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetListProgressQueryResult = NonNullable<Awaited<ReturnType<typeof getListProgress>>>
export type GetListProgressQueryError = unknown


export function useGetListProgress<TData = Awaited<ReturnType<typeof getListProgress>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListProgress>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListProgress>>,
          TError,
          Awaited<ReturnType<typeof getListProgress>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListProgress<TData = Awaited<ReturnType<typeof getListProgress>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListProgress>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getListProgress>>,
          TError,
          Awaited<ReturnType<typeof getListProgress>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListProgress<TData = Awaited<ReturnType<typeof getListProgress>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListProgress>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetListProgress<TData = Awaited<ReturnType<typeof getListProgress>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getListProgress>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetListProgressQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetListProgressSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getListProgress>>, TError = unknown>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getListProgress>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetListProgressQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getListProgress>>> = ({ signal }) => getListProgress(id, { signal });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getListProgress>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetListProgressSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getListProgress>>>
export type GetListProgressSuspenseQueryError = unknown


export function useGetListProgressSuspense<TData = Awaited<ReturnType<typeof getListProgress>>, TError = unknown>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getListProgress>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListProgressSuspense<TData = Awaited<ReturnType<typeof getListProgress>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getListProgress>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetListProgressSuspense<TData = Awaited<ReturnType<typeof getListProgress>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getListProgress>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetListProgressSuspense<TData = Awaited<ReturnType<typeof getListProgress>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getListProgress>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetListProgressSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




