/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Event booster
 * OpenAPI spec version: 0.1.0
 */
import type { PostRegisterListBody } from './endpoints.schemas'
import { axiosInstance } from '../services/axios-instance'

/**
 * Register a list
 */
export const postRegisterList = (
  postRegisterListBody: PostRegisterListBody,
) => {
  return axiosInstance<void>({
    url: `/register-list`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: postRegisterListBody,
  })
}
export type PostRegisterListResult = NonNullable<
  Awaited<ReturnType<typeof postRegisterList>>
>
