/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Plotwist
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DeleteUserSubscription200,
  DeleteUserSubscriptionBody
} from './endpoints.schemas';

import { axiosInstance } from '../services/axios-instance';





/**
 * Delete user subscription
 */
export type deleteUserSubscriptionResponse200 = {
  data: DeleteUserSubscription200
  status: 200
}
    
export type deleteUserSubscriptionResponseSuccess = (deleteUserSubscriptionResponse200) & {
  headers: Headers;
};
;

export type deleteUserSubscriptionResponse = (deleteUserSubscriptionResponseSuccess)

export const getDeleteUserSubscriptionUrl = () => {


  

  return `/user/subscription`
}

export const deleteUserSubscription = async (deleteUserSubscriptionBody: DeleteUserSubscriptionBody, options?: RequestInit): Promise<deleteUserSubscriptionResponse> => {
  
  return axiosInstance<deleteUserSubscriptionResponse>(getDeleteUserSubscriptionUrl(),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      deleteUserSubscriptionBody,)
  }
);}




export const getDeleteUserSubscriptionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserSubscription>>, TError,{data: DeleteUserSubscriptionBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteUserSubscription>>, TError,{data: DeleteUserSubscriptionBody}, TContext> => {

const mutationKey = ['deleteUserSubscription'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUserSubscription>>, {data: DeleteUserSubscriptionBody}> = (props) => {
          const {data} = props ?? {};

          return  deleteUserSubscription(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserSubscriptionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUserSubscription>>>
    export type DeleteUserSubscriptionMutationBody = DeleteUserSubscriptionBody
    export type DeleteUserSubscriptionMutationError = unknown

    export const useDeleteUserSubscription = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserSubscription>>, TError,{data: DeleteUserSubscriptionBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUserSubscription>>,
        TError,
        {data: DeleteUserSubscriptionBody},
        TContext
      > => {
      return useMutation(getDeleteUserSubscriptionMutationOptions(options), queryClient);
    }
    