/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Plotwist
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import { customFetch } from '../services/api-client';
import type { ErrorType } from '../services/api-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Proxy TMDB API requests with Redis caching
 */
export type getTmdbPathResponse200 = {
  data: void
  status: 200
}

export type getTmdbPathResponseSuccess = (getTmdbPathResponse200) & {
  headers: Headers;
};
;

export type getTmdbPathResponse = (getTmdbPathResponseSuccess)

export const getGetTmdbPathUrl = (path: string,) => {


  

  return `/tmdb/${path}+`
}

export const getTmdbPath = async (path: string, options?: RequestInit): Promise<getTmdbPathResponse> => {
  
  return customFetch<getTmdbPathResponse>(getGetTmdbPathUrl(path),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetTmdbPathQueryKey = (path: string,) => {
    return [
    `/tmdb/${path}+`
    ] as const;
    }

    
export const getGetTmdbPathQueryOptions = <TData = Awaited<ReturnType<typeof getTmdbPath>>, TError = ErrorType<unknown>>(path: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTmdbPath>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTmdbPathQueryKey(path);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTmdbPath>>> = ({ signal }) => getTmdbPath(path, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(path), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTmdbPath>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTmdbPathQueryResult = NonNullable<Awaited<ReturnType<typeof getTmdbPath>>>
export type GetTmdbPathQueryError = ErrorType<unknown>


export function useGetTmdbPath<TData = Awaited<ReturnType<typeof getTmdbPath>>, TError = ErrorType<unknown>>(
 path: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTmdbPath>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTmdbPath>>,
          TError,
          Awaited<ReturnType<typeof getTmdbPath>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTmdbPath<TData = Awaited<ReturnType<typeof getTmdbPath>>, TError = ErrorType<unknown>>(
 path: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTmdbPath>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTmdbPath>>,
          TError,
          Awaited<ReturnType<typeof getTmdbPath>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTmdbPath<TData = Awaited<ReturnType<typeof getTmdbPath>>, TError = ErrorType<unknown>>(
 path: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTmdbPath>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTmdbPath<TData = Awaited<ReturnType<typeof getTmdbPath>>, TError = ErrorType<unknown>>(
 path: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTmdbPath>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTmdbPathQueryOptions(path,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetTmdbPathSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getTmdbPath>>, TError = ErrorType<unknown>>(path: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTmdbPath>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTmdbPathQueryKey(path);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTmdbPath>>> = ({ signal }) => getTmdbPath(path, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTmdbPath>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTmdbPathSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getTmdbPath>>>
export type GetTmdbPathSuspenseQueryError = ErrorType<unknown>


export function useGetTmdbPathSuspense<TData = Awaited<ReturnType<typeof getTmdbPath>>, TError = ErrorType<unknown>>(
 path: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTmdbPath>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTmdbPathSuspense<TData = Awaited<ReturnType<typeof getTmdbPath>>, TError = ErrorType<unknown>>(
 path: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTmdbPath>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTmdbPathSuspense<TData = Awaited<ReturnType<typeof getTmdbPath>>, TError = ErrorType<unknown>>(
 path: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTmdbPath>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTmdbPathSuspense<TData = Awaited<ReturnType<typeof getTmdbPath>>, TError = ErrorType<unknown>>(
 path: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTmdbPath>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTmdbPathSuspenseQueryOptions(path,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




