/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Plotwist
 * OpenAPI spec version: 0.1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query'
import type {
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query'
import type {
  GetNetworkActivities200,
  GetNetworkActivitiesParams,
  GetUserActivities200,
  GetUserActivitiesAnualSummary200,
  GetUserActivitiesAnualSummaryParams,
  GetUserActivitiesParams
} from './endpoints.schemas'
import { axiosInstance } from '../services/axios-instance';




/**
 * Get user activities
 */
export const getUserActivities = (
    userId: string,
    params?: GetUserActivitiesParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<GetUserActivities200>(
      {url: `/user/${userId}/activities`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetUserActivitiesQueryKey = (userId: string,
    params?: GetUserActivitiesParams,) => {
    return [`/user/${userId}/activities`, ...(params ? [params]: [])] as const;
    }

    
export const getGetUserActivitiesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getUserActivities>>>, TError = unknown>(userId: string,
    params?: GetUserActivitiesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserActivitiesQueryKey(userId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserActivities>>> = ({ signal }) => getUserActivities(userId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUserActivitiesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getUserActivities>>>
export type GetUserActivitiesInfiniteQueryError = unknown


export function useGetUserActivitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getUserActivities>>>, TError = unknown>(
 userId: string,
    params: undefined |  GetUserActivitiesParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserActivities>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetUserActivitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getUserActivities>>>, TError = unknown>(
 userId: string,
    params?: GetUserActivitiesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserActivities>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetUserActivitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getUserActivities>>>, TError = unknown>(
 userId: string,
    params?: GetUserActivitiesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>>, }

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }

export function useGetUserActivitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getUserActivities>>>, TError = unknown>(
 userId: string,
    params?: GetUserActivitiesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>>, }

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetUserActivitiesInfiniteQueryOptions(userId,params,options)

  const query = useInfiniteQuery(queryOptions) as  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Delete user activity
 */
export const deleteUserActivity = (
    activityId: string,
 ) => {
      
      
      return axiosInstance<void>(
      {url: `/user/activities/${activityId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteUserActivityMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserActivity>>, TError,{activityId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteUserActivity>>, TError,{activityId: string}, TContext> => {
const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUserActivity>>, {activityId: string}> = (props) => {
          const {activityId} = props ?? {};

          return  deleteUserActivity(activityId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserActivityMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUserActivity>>>
    
    export type DeleteUserActivityMutationError = unknown

    export const useDeleteUserActivity = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserActivity>>, TError,{activityId: string}, TContext>, }
): UseMutationResult<
        Awaited<ReturnType<typeof deleteUserActivity>>,
        TError,
        {activityId: string},
        TContext
      > => {

      const mutationOptions = getDeleteUserActivityMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Get network activities
 */
export const getNetworkActivities = (
    params: GetNetworkActivitiesParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<GetNetworkActivities200>(
      {url: `/network/activities`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetNetworkActivitiesQueryKey = (params: GetNetworkActivitiesParams,) => {
    return [`/network/activities`, ...(params ? [params]: [])] as const;
    }

    
export const getGetNetworkActivitiesQueryOptions = <TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(params: GetNetworkActivitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNetworkActivitiesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNetworkActivities>>> = ({ signal }) => getNetworkActivities(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData> & { queryKey: QueryKey }
}

export type GetNetworkActivitiesQueryResult = NonNullable<Awaited<ReturnType<typeof getNetworkActivities>>>
export type GetNetworkActivitiesQueryError = unknown


export function useGetNetworkActivities<TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(
 params: GetNetworkActivitiesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNetworkActivities>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetNetworkActivities<TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(
 params: GetNetworkActivitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNetworkActivities>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetNetworkActivities<TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(
 params: GetNetworkActivitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useGetNetworkActivities<TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(
 params: GetNetworkActivitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetNetworkActivitiesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetNetworkActivitiesSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(params: GetNetworkActivitiesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNetworkActivitiesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNetworkActivities>>> = ({ signal }) => getNetworkActivities(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData> & { queryKey: QueryKey }
}

export type GetNetworkActivitiesSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getNetworkActivities>>>
export type GetNetworkActivitiesSuspenseQueryError = unknown


export function useGetNetworkActivitiesSuspense<TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(
 params: GetNetworkActivitiesParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>>, }

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetNetworkActivitiesSuspense<TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(
 params: GetNetworkActivitiesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>>, }

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetNetworkActivitiesSuspense<TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(
 params: GetNetworkActivitiesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>>, }

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useGetNetworkActivitiesSuspense<TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(
 params: GetNetworkActivitiesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>>, }

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetNetworkActivitiesSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions) as  UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Get user activities anual summary
 */
export const getUserActivitiesAnualSummary = (
    userId: string,
    params: GetUserActivitiesAnualSummaryParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<GetUserActivitiesAnualSummary200>(
      {url: `/user/${userId}/activities/anual-summary`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetUserActivitiesAnualSummaryQueryKey = (userId: string,
    params: GetUserActivitiesAnualSummaryParams,) => {
    return [`/user/${userId}/activities/anual-summary`, ...(params ? [params]: [])] as const;
    }

    
export const getGetUserActivitiesAnualSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>, TError = unknown>(userId: string,
    params: GetUserActivitiesAnualSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserActivitiesAnualSummaryQueryKey(userId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>> = ({ signal }) => getUserActivitiesAnualSummary(userId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUserActivitiesAnualSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>>
export type GetUserActivitiesAnualSummaryQueryError = unknown


export function useGetUserActivitiesAnualSummary<TData = Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>, TError = unknown>(
 userId: string,
    params: GetUserActivitiesAnualSummaryParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetUserActivitiesAnualSummary<TData = Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>, TError = unknown>(
 userId: string,
    params: GetUserActivitiesAnualSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>,
          TError,
          TData
        > , 'initialData'
      >, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetUserActivitiesAnualSummary<TData = Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>, TError = unknown>(
 userId: string,
    params: GetUserActivitiesAnualSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useGetUserActivitiesAnualSummary<TData = Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>, TError = unknown>(
 userId: string,
    params: GetUserActivitiesAnualSummaryParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>, TError, TData>>, }

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetUserActivitiesAnualSummaryQueryOptions(userId,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetUserActivitiesAnualSummarySuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>, TError = unknown>(userId: string,
    params: GetUserActivitiesAnualSummaryParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserActivitiesAnualSummaryQueryKey(userId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>> = ({ signal }) => getUserActivitiesAnualSummary(userId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>, TError, TData> & { queryKey: QueryKey }
}

export type GetUserActivitiesAnualSummarySuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>>
export type GetUserActivitiesAnualSummarySuspenseQueryError = unknown


export function useGetUserActivitiesAnualSummarySuspense<TData = Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>, TError = unknown>(
 userId: string,
    params: GetUserActivitiesAnualSummaryParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>, TError, TData>>, }

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetUserActivitiesAnualSummarySuspense<TData = Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>, TError = unknown>(
 userId: string,
    params: GetUserActivitiesAnualSummaryParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>, TError, TData>>, }

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetUserActivitiesAnualSummarySuspense<TData = Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>, TError = unknown>(
 userId: string,
    params: GetUserActivitiesAnualSummaryParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>, TError, TData>>, }

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey }

export function useGetUserActivitiesAnualSummarySuspense<TData = Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>, TError = unknown>(
 userId: string,
    params: GetUserActivitiesAnualSummaryParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserActivitiesAnualSummary>>, TError, TData>>, }

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetUserActivitiesAnualSummarySuspenseQueryOptions(userId,params,options)

  const query = useSuspenseQuery(queryOptions) as  UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



