/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Plotwist
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  GetUserFavoriteCheck200,
  GetUserFavoriteCheckParams,
  GetUserFavorites200,
  GetUserFavoritesParams,
  PutUserFavorite200,
  PutUserFavoriteBody
} from './endpoints.schemas';

import { customFetch } from '../services/api-client';
import type { ErrorType , BodyType } from '../services/api-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Toggle favorite (add or remove)
 */
export type putUserFavoriteResponse200 = {
  data: PutUserFavorite200
  status: 200
}

export type putUserFavoriteResponseSuccess = (putUserFavoriteResponse200) & {
  headers: Headers;
};
;

export type putUserFavoriteResponse = (putUserFavoriteResponseSuccess)

export const getPutUserFavoriteUrl = () => {


  

  return `/user/favorite`
}

export const putUserFavorite = async (putUserFavoriteBody: PutUserFavoriteBody, options?: RequestInit): Promise<putUserFavoriteResponse> => {
  
  return customFetch<putUserFavoriteResponse>(getPutUserFavoriteUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      putUserFavoriteBody,)
  }
);}
  



export const getPutUserFavoriteMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUserFavorite>>, TError,{data: BodyType<PutUserFavoriteBody>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof putUserFavorite>>, TError,{data: BodyType<PutUserFavoriteBody>}, TContext> => {

const mutationKey = ['putUserFavorite'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putUserFavorite>>, {data: BodyType<PutUserFavoriteBody>}> = (props) => {
          const {data} = props ?? {};

          return  putUserFavorite(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PutUserFavoriteMutationResult = NonNullable<Awaited<ReturnType<typeof putUserFavorite>>>
    export type PutUserFavoriteMutationBody = BodyType<PutUserFavoriteBody>
    export type PutUserFavoriteMutationError = ErrorType<unknown>

    export const usePutUserFavorite = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUserFavorite>>, TError,{data: BodyType<PutUserFavoriteBody>}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putUserFavorite>>,
        TError,
        {data: BodyType<PutUserFavoriteBody>},
        TContext
      > => {
      return useMutation(getPutUserFavoriteMutationOptions(options), queryClient);
    }
    /**
 * Get user favorites
 */
export type getUserFavoritesResponse200 = {
  data: GetUserFavorites200
  status: 200
}

export type getUserFavoritesResponseSuccess = (getUserFavoritesResponse200) & {
  headers: Headers;
};
;

export type getUserFavoritesResponse = (getUserFavoritesResponseSuccess)

export const getGetUserFavoritesUrl = (params: GetUserFavoritesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/user/favorites?${stringifiedParams}` : `/user/favorites`
}

export const getUserFavorites = async (params: GetUserFavoritesParams, options?: RequestInit): Promise<getUserFavoritesResponse> => {
  
  return customFetch<getUserFavoritesResponse>(getGetUserFavoritesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetUserFavoritesQueryKey = (params?: GetUserFavoritesParams,) => {
    return [
    `/user/favorites`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetUserFavoritesQueryOptions = <TData = Awaited<ReturnType<typeof getUserFavorites>>, TError = ErrorType<unknown>>(params: GetUserFavoritesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserFavorites>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserFavoritesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserFavorites>>> = ({ signal }) => getUserFavorites(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserFavorites>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserFavoritesQueryResult = NonNullable<Awaited<ReturnType<typeof getUserFavorites>>>
export type GetUserFavoritesQueryError = ErrorType<unknown>


export function useGetUserFavorites<TData = Awaited<ReturnType<typeof getUserFavorites>>, TError = ErrorType<unknown>>(
 params: GetUserFavoritesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserFavorites>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserFavorites>>,
          TError,
          Awaited<ReturnType<typeof getUserFavorites>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserFavorites<TData = Awaited<ReturnType<typeof getUserFavorites>>, TError = ErrorType<unknown>>(
 params: GetUserFavoritesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserFavorites>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserFavorites>>,
          TError,
          Awaited<ReturnType<typeof getUserFavorites>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserFavorites<TData = Awaited<ReturnType<typeof getUserFavorites>>, TError = ErrorType<unknown>>(
 params: GetUserFavoritesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserFavorites>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserFavorites<TData = Awaited<ReturnType<typeof getUserFavorites>>, TError = ErrorType<unknown>>(
 params: GetUserFavoritesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserFavorites>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserFavoritesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetUserFavoritesSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getUserFavorites>>, TError = ErrorType<unknown>>(params: GetUserFavoritesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserFavorites>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserFavoritesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserFavorites>>> = ({ signal }) => getUserFavorites(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserFavorites>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserFavoritesSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getUserFavorites>>>
export type GetUserFavoritesSuspenseQueryError = ErrorType<unknown>


export function useGetUserFavoritesSuspense<TData = Awaited<ReturnType<typeof getUserFavorites>>, TError = ErrorType<unknown>>(
 params: GetUserFavoritesParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserFavorites>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserFavoritesSuspense<TData = Awaited<ReturnType<typeof getUserFavorites>>, TError = ErrorType<unknown>>(
 params: GetUserFavoritesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserFavorites>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserFavoritesSuspense<TData = Awaited<ReturnType<typeof getUserFavorites>>, TError = ErrorType<unknown>>(
 params: GetUserFavoritesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserFavorites>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserFavoritesSuspense<TData = Awaited<ReturnType<typeof getUserFavorites>>, TError = ErrorType<unknown>>(
 params: GetUserFavoritesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserFavorites>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserFavoritesSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Check if item is favorited
 */
export type getUserFavoriteCheckResponse200 = {
  data: GetUserFavoriteCheck200
  status: 200
}

export type getUserFavoriteCheckResponseSuccess = (getUserFavoriteCheckResponse200) & {
  headers: Headers;
};
;

export type getUserFavoriteCheckResponse = (getUserFavoriteCheckResponseSuccess)

export const getGetUserFavoriteCheckUrl = (params: GetUserFavoriteCheckParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/user/favorite/check?${stringifiedParams}` : `/user/favorite/check`
}

export const getUserFavoriteCheck = async (params: GetUserFavoriteCheckParams, options?: RequestInit): Promise<getUserFavoriteCheckResponse> => {
  
  return customFetch<getUserFavoriteCheckResponse>(getGetUserFavoriteCheckUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetUserFavoriteCheckQueryKey = (params?: GetUserFavoriteCheckParams,) => {
    return [
    `/user/favorite/check`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetUserFavoriteCheckQueryOptions = <TData = Awaited<ReturnType<typeof getUserFavoriteCheck>>, TError = ErrorType<unknown>>(params: GetUserFavoriteCheckParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserFavoriteCheck>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserFavoriteCheckQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserFavoriteCheck>>> = ({ signal }) => getUserFavoriteCheck(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserFavoriteCheck>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserFavoriteCheckQueryResult = NonNullable<Awaited<ReturnType<typeof getUserFavoriteCheck>>>
export type GetUserFavoriteCheckQueryError = ErrorType<unknown>


export function useGetUserFavoriteCheck<TData = Awaited<ReturnType<typeof getUserFavoriteCheck>>, TError = ErrorType<unknown>>(
 params: GetUserFavoriteCheckParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserFavoriteCheck>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserFavoriteCheck>>,
          TError,
          Awaited<ReturnType<typeof getUserFavoriteCheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserFavoriteCheck<TData = Awaited<ReturnType<typeof getUserFavoriteCheck>>, TError = ErrorType<unknown>>(
 params: GetUserFavoriteCheckParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserFavoriteCheck>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserFavoriteCheck>>,
          TError,
          Awaited<ReturnType<typeof getUserFavoriteCheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserFavoriteCheck<TData = Awaited<ReturnType<typeof getUserFavoriteCheck>>, TError = ErrorType<unknown>>(
 params: GetUserFavoriteCheckParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserFavoriteCheck>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserFavoriteCheck<TData = Awaited<ReturnType<typeof getUserFavoriteCheck>>, TError = ErrorType<unknown>>(
 params: GetUserFavoriteCheckParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserFavoriteCheck>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserFavoriteCheckQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export const getGetUserFavoriteCheckSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getUserFavoriteCheck>>, TError = ErrorType<unknown>>(params: GetUserFavoriteCheckParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserFavoriteCheck>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserFavoriteCheckQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserFavoriteCheck>>> = ({ signal }) => getUserFavoriteCheck(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserFavoriteCheck>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserFavoriteCheckSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getUserFavoriteCheck>>>
export type GetUserFavoriteCheckSuspenseQueryError = ErrorType<unknown>


export function useGetUserFavoriteCheckSuspense<TData = Awaited<ReturnType<typeof getUserFavoriteCheck>>, TError = ErrorType<unknown>>(
 params: GetUserFavoriteCheckParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserFavoriteCheck>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserFavoriteCheckSuspense<TData = Awaited<ReturnType<typeof getUserFavoriteCheck>>, TError = ErrorType<unknown>>(
 params: GetUserFavoriteCheckParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserFavoriteCheck>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserFavoriteCheckSuspense<TData = Awaited<ReturnType<typeof getUserFavoriteCheck>>, TError = ErrorType<unknown>>(
 params: GetUserFavoriteCheckParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserFavoriteCheck>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserFavoriteCheckSuspense<TData = Awaited<ReturnType<typeof getUserFavoriteCheck>>, TError = ErrorType<unknown>>(
 params: GetUserFavoriteCheckParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserFavoriteCheck>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserFavoriteCheckSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




