/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Plotwist
 * OpenAPI spec version: 0.1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  GetNetworkActivities200,
  GetNetworkActivitiesParams,
  GetUserActivities200,
  GetUserActivitiesParams
} from './endpoints.schemas';

import { axiosInstance } from '../services/axios-instance';





/**
 * Get user activities
 */
export const getUserActivities = (
    userId: string,
    params?: GetUserActivitiesParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<GetUserActivities200>(
      {url: `/user/${userId}/activities`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetUserActivitiesInfiniteQueryKey = (userId?: string,
    params?: GetUserActivitiesParams,) => {
    return [
    'infinite', `/user/${userId}/activities`, ...(params ? [params]: [])
    ] as const;
    }

export const getGetUserActivitiesQueryKey = (userId?: string,
    params?: GetUserActivitiesParams,) => {
    return [
    `/user/${userId}/activities`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetUserActivitiesInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getUserActivities>>>, TError = unknown>(userId: string,
    params?: GetUserActivitiesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserActivitiesInfiniteQueryKey(userId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserActivities>>> = ({ signal }) => getUserActivities(userId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserActivitiesInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getUserActivities>>>
export type GetUserActivitiesInfiniteQueryError = unknown


export function useGetUserActivitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getUserActivities>>>, TError = unknown>(
 userId: string,
    params: undefined |  GetUserActivitiesParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserActivities>>,
          TError,
          Awaited<ReturnType<typeof getUserActivities>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserActivitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getUserActivities>>>, TError = unknown>(
 userId: string,
    params?: GetUserActivitiesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserActivities>>,
          TError,
          Awaited<ReturnType<typeof getUserActivities>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserActivitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getUserActivities>>>, TError = unknown>(
 userId: string,
    params?: GetUserActivitiesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserActivitiesInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getUserActivities>>>, TError = unknown>(
 userId: string,
    params?: GetUserActivitiesParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserActivitiesInfiniteQueryOptions(userId,params,options)

  const query = useInfiniteQuery(queryOptions, queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getGetUserActivitiesQueryOptions = <TData = Awaited<ReturnType<typeof getUserActivities>>, TError = unknown>(userId: string,
    params?: GetUserActivitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserActivitiesQueryKey(userId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserActivities>>> = ({ signal }) => getUserActivities(userId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserActivitiesQueryResult = NonNullable<Awaited<ReturnType<typeof getUserActivities>>>
export type GetUserActivitiesQueryError = unknown


export function useGetUserActivities<TData = Awaited<ReturnType<typeof getUserActivities>>, TError = unknown>(
 userId: string,
    params: undefined |  GetUserActivitiesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserActivities>>,
          TError,
          Awaited<ReturnType<typeof getUserActivities>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserActivities<TData = Awaited<ReturnType<typeof getUserActivities>>, TError = unknown>(
 userId: string,
    params?: GetUserActivitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserActivities>>,
          TError,
          Awaited<ReturnType<typeof getUserActivities>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserActivities<TData = Awaited<ReturnType<typeof getUserActivities>>, TError = unknown>(
 userId: string,
    params?: GetUserActivitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserActivities<TData = Awaited<ReturnType<typeof getUserActivities>>, TError = unknown>(
 userId: string,
    params?: GetUserActivitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserActivitiesQueryOptions(userId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getGetUserActivitiesSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getUserActivities>>, TError = unknown>(userId: string,
    params?: GetUserActivitiesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserActivitiesQueryKey(userId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserActivities>>> = ({ signal }) => getUserActivities(userId,params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserActivitiesSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getUserActivities>>>
export type GetUserActivitiesSuspenseQueryError = unknown


export function useGetUserActivitiesSuspense<TData = Awaited<ReturnType<typeof getUserActivities>>, TError = unknown>(
 userId: string,
    params: undefined |  GetUserActivitiesParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserActivitiesSuspense<TData = Awaited<ReturnType<typeof getUserActivities>>, TError = unknown>(
 userId: string,
    params?: GetUserActivitiesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserActivitiesSuspense<TData = Awaited<ReturnType<typeof getUserActivities>>, TError = unknown>(
 userId: string,
    params?: GetUserActivitiesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserActivitiesSuspense<TData = Awaited<ReturnType<typeof getUserActivities>>, TError = unknown>(
 userId: string,
    params?: GetUserActivitiesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getUserActivities>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserActivitiesSuspenseQueryOptions(userId,params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Delete user activity
 */
export const deleteUserActivity = (
    activityId: string,
 ) => {
      
      
      return axiosInstance<void>(
      {url: `/user/activities/${activityId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteUserActivityMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserActivity>>, TError,{activityId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteUserActivity>>, TError,{activityId: string}, TContext> => {

const mutationKey = ['deleteUserActivity'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUserActivity>>, {activityId: string}> = (props) => {
          const {activityId} = props ?? {};

          return  deleteUserActivity(activityId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserActivityMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUserActivity>>>
    
    export type DeleteUserActivityMutationError = unknown

    export const useDeleteUserActivity = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUserActivity>>, TError,{activityId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUserActivity>>,
        TError,
        {activityId: string},
        TContext
      > => {

      const mutationOptions = getDeleteUserActivityMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get network activities
 */
export const getNetworkActivities = (
    params: GetNetworkActivitiesParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<GetNetworkActivities200>(
      {url: `/network/activities`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetNetworkActivitiesQueryKey = (params?: GetNetworkActivitiesParams,) => {
    return [
    `/network/activities`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetNetworkActivitiesQueryOptions = <TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(params: GetNetworkActivitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNetworkActivitiesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNetworkActivities>>> = ({ signal }) => getNetworkActivities(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNetworkActivitiesQueryResult = NonNullable<Awaited<ReturnType<typeof getNetworkActivities>>>
export type GetNetworkActivitiesQueryError = unknown


export function useGetNetworkActivities<TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(
 params: GetNetworkActivitiesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNetworkActivities>>,
          TError,
          Awaited<ReturnType<typeof getNetworkActivities>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNetworkActivities<TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(
 params: GetNetworkActivitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNetworkActivities>>,
          TError,
          Awaited<ReturnType<typeof getNetworkActivities>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNetworkActivities<TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(
 params: GetNetworkActivitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetNetworkActivities<TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(
 params: GetNetworkActivitiesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetNetworkActivitiesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getGetNetworkActivitiesSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(params: GetNetworkActivitiesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNetworkActivitiesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNetworkActivities>>> = ({ signal }) => getNetworkActivities(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNetworkActivitiesSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getNetworkActivities>>>
export type GetNetworkActivitiesSuspenseQueryError = unknown


export function useGetNetworkActivitiesSuspense<TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(
 params: GetNetworkActivitiesParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNetworkActivitiesSuspense<TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(
 params: GetNetworkActivitiesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNetworkActivitiesSuspense<TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(
 params: GetNetworkActivitiesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetNetworkActivitiesSuspense<TData = Awaited<ReturnType<typeof getNetworkActivities>>, TError = unknown>(
 params: GetNetworkActivitiesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getNetworkActivities>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetNetworkActivitiesSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




